import type { Technology } from '../types';
import { defineTech } from './builder';

export const AI_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'pgvector',
    name: 'pgvector',
    category: 'ai',
    tagline: 'Extension de busqueda vectorial y similitud semantica nativa para PostgreSQL.',
    description: 'Permite almacenar embeddings vectoriales y realizar busquedas de similitud (L2, producto interno, distancia coseno) con indices HNSW e IVFFlat directamente en tus tablas SQL.',
    website: 'https://github.com/pgvector/pgvector',
    license: 'PostgreSQL',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Postgres Native',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Extension 100% gratuita y de codigo abierto para cualquier instancia de PostgreSQL.' },
    tradeoffs: {
      pros: ['No requiere contratar, mantener ni sincronizar una base de datos vectorial separada', 'Permite unir filtros relacionales SQL complejos con busquedas vectoriales en una sola consulta', 'Soporte estandar en Supabase, Neon, AWS RDS y Azure Postgres'],
      cons: ['Para catalogos con decenas de millones de vectores de alta dimension, el consumo de RAM de los indices HNSW puede exigir servidores mayores', 'Rendimiento de QPS ligeramente inferior a motores vectoriales en memoria dedicados'],
      sacrifices: ['Sacrificas optimizacion hiperespecifica a escala de cientos de millones de vectores por simplicidad relacional insuperable.'],
      idealFor: ['Startups y SaaS que ya usan PostgreSQL', 'Sistemas RAG (Retrieval-Augmented Generation) de tamano medio', 'Recomendaciones semanticas'],
      avoidIf: ['Indexacion de miles de millones de vectores con cientos de actualizaciones concurrentes por segundo'],
    },
  }),
  defineTech({
    id: 'qdrant',
    name: 'Qdrant',
    category: 'ai',
    tagline: 'Base de datos vectorial de alto rendimiento escrita en Rust con filtrado por metadatos.',
    description: 'Motor de busqueda vectorial disenado para cargas de produccion, con almacenamiento en disco cuantificado, busqueda de vecinos mas cercanos y filtrado avanzado de payloads.',
    website: 'https://qdrant.tech/',
    license: 'Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Rust Engine',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Cluster de 1 GB en Qdrant Cloud gratis o auto-alojamiento ilimitado en Docker.' },
    tradeoffs: {
      pros: ['Eficiencia de memoria y velocidad de inferencia lideres gracias a su construccion en Rust', 'Filtrado de cargas utiles (payloads) extremadamente rapido sin degradar la busqueda vectorial', 'Soporta cuantificacion escalar y binaria para almacenar millones de vectores con poca memoria RAM'],
      cons: ['Requiere gestionar un servicio de base de datos adicional junto a la base de datos relacional principal', 'Consistencia eventual en clusters distribuidos masivos'],
      sacrifices: ['Sacrificas tener un unico almacen relacional a cambio de velocidad y capacidades vectoriales puras.'],
      idealFor: ['Sistemas de busqueda semantica de gran escala', 'RAG corporativo con millones de fragmentos de texto', 'Motores de recomendacion visual'],
      avoidIf: ['Proyectos simples con menos de 10,000 documentos donde pgvector basta'],
    },
  }),
  defineTech({
    id: 'pinecone',
    name: 'Pinecone',
    category: 'ai',
    tagline: 'Base de datos vectorial en la nube totalmente gestionada y serverless.',
    description: 'Pionera en bases de datos vectoriales como servicio, disenada para ofrecer busquedas de similitud a baja latencia con autoscaling instantaneo y cero tareas de mantenimiento de infraestructura.',
    website: 'https://www.pinecone.io/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Managed Vector DB',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Indice serverless gratuito con 2 GB de almacenamiento de vectores.' },
    tradeoffs: {
      pros: ['Cero gestion de servidores, sharding o memoria con su nueva arquitectura serverless', 'Facilidad de arranque absoluta: crear indice y subir vectores en menos de 5 minutos', 'Latencia de busqueda uniforme y predecible a escala global'],
      cons: ['Solucion propietaria y de codigo cerrado (sin opcion de ejecucion local on-premise)', 'Costo por peticion que puede aumentar con millones de consultas diarias intensivas'],
      sacrifices: ['Sacrificas soberania de codigo y datos en servidores propios por conveniencia total de gestion.'],
      idealFor: ['Equipos sin ingenieros de infraestructura dedicados', 'Prototipos y aplicaciones comerciales que necesitan arrancar hoy'],
      avoidIf: ['Empresas bancarias o medicas con requisitos estrictos de auto-alojamiento en local'],
    },
  }),
  defineTech({
    id: 'chroma',
    name: 'Chroma',
    category: 'ai',
    tagline: 'Base de datos vectorial nativa para IA, orientada a desarrolladores de Python y TypeScript.',
    description: 'Base de datos vectorial de codigo abierto pensada para arrancar en minutos con una experiencia de desarrollo trivial, embebible directamente en aplicaciones o ejecutable en modo cliente-servidor.',
    website: 'https://www.trychroma.com/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'AI Native DB',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito sin limitaciones artificiales.' },
    tradeoffs: {
      pros: ['Instalacion y configuracion en una sola linea de comando (pip install chromadb o npm)', 'Generacion automatica de embeddings integrada sin necesidad de llamar a APIs externas manualmente', 'Ideal para desarrollo rapido, notebooks y pruebas locales'],
      cons: ['Historicamente menos adaptado a cargas masivas distribuidas de petabytes que Milvus o Qdrant', 'Menos caracteristicas avanzadas de particionado multi-tenant'],
      sacrifices: ['Sacrificas escalabilidad a nivel de billones de vectores a favor de simplicidad inigualable para comenzar.'],
      idealFor: ['Desarrollo de prototipos de IA', 'Aplicaciones de escritorio locales con LLMs', 'Proyectos pequenos y medianos de RAG'],
      avoidIf: ['Sistemas de busqueda de nivel enterprise con cientos de nodos de computo en produccion'],
    },
  }),
  defineTech({
    id: 'milvus',
    name: 'Milvus',
    category: 'ai',
    tagline: 'Base de datos vectorial cloud-native creada para escalabilidad masiva a nivel empresarial.',
    description: 'Proyecto de la fundacion LF AI & Data capaz de indexar y buscar entre miles de millones de vectores mediante una arquitectura distribuida con separacion de computo y almacenamiento.',
    website: 'https://milvus.io/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Massive Scale',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% software libre y de codigo abierto (u opcion Zilliz Cloud gestionada).' },
    tradeoffs: {
      pros: ['Capacidad demostrada para escalar a miles de millones de vectores sin perder rendimiento', 'Soporte para multiples algoritmos de indexacion (HNSW, IVF_FLAT, SCaNN, Annoy)', 'Gran respaldo de la fundacion Linux y arquitectura de microservicios distribuida'],
      cons: ['Despliegue y mantenimiento de la version distribuida en Kubernetes requiere conocimientos avanzados', 'Consumo significativo de recursos de infraestructura base'],
      sacrifices: ['Sacrificas sencillez de despliegue a favor de la capacidad de absorcion de datos masiva.'],
      idealFor: ['Grandes corporaciones tecnologicas', 'Comercio electronico con catalogos de cientos de millones de productos', 'Vision por computador'],
      avoidIf: ['Proyectos individuales o aplicaciones que buscan sencillez en una sola maquina virtual'],
    },
  }),
  defineTech({
    id: 'weaviate',
    name: 'Weaviate',
    category: 'ai',
    tagline: 'Motor de busqueda vectorial de codigo abierto y base de datos multimodal.',
    description: 'Permite almacenar objetos de datos y sus vectores juntos, con busqueda hibrida (vectorial + busqueda de palabras clave BM25) y soporte nativo para modelos de lenguaje integrados.',
    website: 'https://weaviate.io/',
    license: 'BSD-3-Clause',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Hybrid Search',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Sandbox de 14 dias en Weaviate Cloud o auto-alojamiento 100% libre sin restricciones.' },
    tradeoffs: {
      pros: ['Busqueda hibrida nativa que combina precision lexica (BM25) con comprension semantica vectorial', 'Modulos integrados para conectar directamente con OpenAI, Cohere o Hugging Face', 'Soporta vectores de texto, imagenes y audio en un mismo esquema'],
      cons: ['Sintaxis de esquema basada en GraphQL y REST que requiere cierta adaptacion', 'Sincronizacion de indices distribuidos compleja en clusters de alta disponibilidad'],
      sacrifices: ['Sacrificas estandares clasicos SQL a cambio de un grafo de conocimiento semantico enriquecido.'],
      idealFor: ['Sistemas de documentacion y atencion al cliente', 'Busqueda de e-commerce multimodal', 'Sistemas RAG avanzados'],
      avoidIf: ['Aplicaciones puramente transaccionales que requieren integridad referencial relacional'],
    },
  }),
  defineTech({
    id: 'langchain',
    name: 'LangChain',
    category: 'ai',
    tagline: 'El framework lider para construir aplicaciones impulsadas por modelos de lenguaje (LLMs).',
    description: 'Ecosistema integral para encadenar llamadas a LLMs, conectar bases de datos vectoriales, gestionar memoria de conversacion y crear agentes autonomos con herramientas (LangGraph).',
    website: 'https://www.langchain.com/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'LLM Orchestration',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Framework 100% de codigo abierto en Python y TypeScript (LangChain.js).' },
    tradeoffs: {
      pros: ['El catalogo de integraciones mas exhaustivo del mundo (mas de 700 conectores a modelos y bases de datos)', 'Abstracciones listas para usar para cadenas de razonamiento, agentes y memoria', 'LangGraph ofrece control determinista de grafos de estados para flujos complejos'],
      cons: ['Historico de abstracciones excesivas que pueden dificultar la depuracion de errores en codigo interno', 'Rapida evolucion con cambios frecuentes entre versiones mayores'],
      sacrifices: ['Sacrificas llamadas transparentes y sencillas a cambio de una amplia biblioteca de integraciones prefabricadas.'],
      idealFor: ['Agentes inteligentes con acceso a herramientas externas', 'Flujos de trabajo complejos de RAG', 'Prototipos multidisciplinarios'],
      avoidIf: ['Llamadas simples y directas a un solo modelo donde un SDK nativo es mucho mas limpio'],
    },
  }),
  defineTech({
    id: 'llamaindex',
    name: 'LlamaIndex',
    category: 'ai',
    tagline: 'Framework especializado en conectar datos privados con modelos de lenguaje (RAG).',
    description: 'Centrado en la ingestion, indexacion y recuperacion optima de documentos no estructurados (PDFs, Notion, SQL, Slack) para alimentar LLMs con contexto relevante y preciso.',
    website: 'https://www.llamaindex.ai/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'RAG Specialist',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Framework de codigo abierto en Python y TypeScript.' },
    tradeoffs: {
      pros: ['Especializacion profunda en analisis, segmentacion (chunking) y parsing de documentos complejos', 'Algoritmos avanzados de re-ranking y evaluacion de fidelidad de respuestas generadas', 'Excelente soporte de busqueda jerarquica y grafos de conocimiento'],
      cons: ['Menos enfocado en la creacion de agentes genericos que LangChain/LangGraph', 'La documentacion en TypeScript esta ligeramente rezagada frente a la de Python'],
      sacrifices: ['Sacrificas versatilidad en herramientas de agentes por la maxima excelencia en pipelines de recuperacion documental.'],
      idealFor: ['Sistemas de consulta sobre documentacion tecnica, manuales y contratos legales', 'Pipelines RAG de alta fidelidad'],
      avoidIf: ['Aplicaciones conversacionales simples sin ingestion de documentos externos'],
    },
  }),
  defineTech({
    id: 'openai-api',
    name: 'OpenAI API',
    category: 'ai',
    tagline: 'Modelos de lenguaje de frontera y razonamiento lideres de la industria (GPT-4o, o1).',
    description: 'La suite de modelos de inteligencia artificial mas extendida del planeta, ofreciendo modelos multimodales de vanguardia, capacidades avanzadas de Structured Outputs y llamada a funciones.',
    website: 'https://openai.com/api/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Industry Standard',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: false, limitsDescription: 'Facturacion de pago por uso segun millones de tokens de entrada y salida consumidos.' },
    tradeoffs: {
      pros: ['Calidad de razonamiento, seguimiento de instrucciones y coherencia linguisticas punteras', 'Soporte nativo para Structured Outputs con esquemas JSON garantizados al 100%', 'Ecosistema masivo de herramientas y bibliotecas optimizadas para su API'],
      cons: ['Costos variables que pueden acumularse con alto volumen de tokens de razonamiento (familia o1)', 'Posibles latencias variables en momentos de picos mundiales'],
      sacrifices: ['Sacrificas soberania de codigo y costes fijos a cambio de la mayor inteligencia disponible comercialmente.'],
      idealFor: ['Cualquier producto digital que requiera maxima inteligencia y razonamiento', 'Generacion de codigo y analisis'],
      avoidIf: ['Empresas con prohibicion estricta de envio de datos a servidores en territorio estadounidense'],
    },
  }),
  defineTech({
    id: 'anthropic-api',
    name: 'Anthropic Claude API',
    category: 'ai',
    tagline: 'Modelos Claude 3.5 (Sonnet, Haiku) lideres en programacion, vision y generacion humana.',
    description: 'Familia de modelos de IA disenados con enfoque en seguridad e interpretabilidad, aclamados por la comunidad de ingenieria como los mejores del mundo en generacion y depuracion de codigo.',
    website: 'https://www.anthropic.com/api',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Coding Leader',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: false, limitsDescription: 'Pago por millon de tokens con soporte de Prompt Caching que reduce costes hasta un 90%.' },
    tradeoffs: {
      pros: ['Capacidad insuperable en generacion de codigo limpio, refactorizaciones y razonamiento logico', 'Tecnologia de Prompt Caching extremadamente eficiente para chats largos o bases de codigo', 'Ventana de contexto inmensa de 200,000 tokens'],
      cons: ['Disponibilidad de metodos de ajuste fino (fine-tuning) mas restringida que OpenAI', 'Menos funcionalidades de generacion de audio nativo en tiempo real'],
      sacrifices: ['Sacrificas variedad de modalidades de audio por la mejor precision sintactica y analitica del mercado.'],
      idealFor: ['Herramientas de asistencia de codigo y desarrollo', 'Escritura compleja y analisis de extensos documentos tecnicos'],
      avoidIf: ['Casos que requieren modelos de bajo coste microscopico en dispositivos locales'],
    },
  }),
  defineTech({
    id: 'groq',
    name: 'Groq',
    category: 'ai',
    tagline: 'Motor de inferencia ultrarrapido impulsado por procesadores LPU (Language Processing Unit).',
    description: 'Procesador de hardware especifico capaz de ejecutar modelos de pesos abiertos (Llama 3, Mistral, Gemma) a velocidades sorprendentes de mas de 500 tokens por segundo.',
    website: 'https://groq.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: '500+ Tokens/sec',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Capa gratuita generosa en cuota diaria de tokens para pruebas y desarrollo.' },
    tradeoffs: {
      pros: ['Velocidad de generacion en tiempo real sin equivalente en el mercado, ideal para experiencias conversacionales orales', 'API compatible al 100% con el SDK estandar de OpenAI', 'Costes por token sumamente competitivos'],
      cons: ['Limitado a modelos de pesos abiertos soportados en su arquitectura de LPUs', 'Menos memoria de contexto disponible en comparacion con grandes clusters de GPUs'],
      sacrifices: ['Sacrificas ventanas de contexto kilometricas a cambio de una velocidad de respuesta instantanea.'],
      idealFor: ['Asistentes de voz interactivos', 'Clasificaciones y extracciones de datos en tiempo real ultrarrapidas'],
      avoidIf: ['Necesidad estricta de utilizar modelos propietarios cerrados de OpenAI o Anthropic'],
    },
  }),
  defineTech({
    id: 'mistral',
    name: 'Mistral AI',
    category: 'ai',
    tagline: 'Modelos de frontera de alta eficiencia y soberania de datos europea (Mistral, Codestral).',
    description: 'Empresa francesa lider en inteligencia artificial europea, que ofrece modelos abiertos de pesos optimizados y modelos comerciales de frontera de gran rendimiento y bajo consumo de memoria.',
    website: 'https://mistral.ai/',
    license: 'Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'European Frontier',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Nivel gratuito en su plataforma La Plateforme para pruebas de desarrollo.' },
    tradeoffs: {
      pros: ['Garantia de soberania y cumplimiento legal riguroso dentro del territorio de la Union Europea', 'Modelos abiertos que pueden desplegarse en servidores propios sin ataduras comerciales', 'Codestral y Mistral Large ofrecen excelente rendimiento a precios ajustados'],
      cons: ['Ecosistema de plugins complementarios aun mas joven que el de OpenAI', 'Comunidad en ingles mas concentrada, aunque con gran apoyo europeo'],
      sacrifices: ['Sacrificas el tamano absoluto de comunidad a favor de soberania legal y eficiencia computacional.'],
      idealFor: ['Empresas europeas con requisitos normativos de IA', 'Autohospedaje de modelos potentes en servidores locales'],
      avoidIf: ['Proyectos que requieren modelos de razonamiento ultra complejos multi-paso como OpenAI o1'],
    },
  }),
  defineTech({
    id: 'cerebras',
    name: 'Cerebras Inference',
    category: 'ai',
    tagline: 'Inferencia de IA a velocidad record mundial impulsada por el chip Wafer-Scale Engine.',
    description: 'Plataforma de inferencia que utiliza el procesador de silicio mas grande jamas fabricado (a nivel de oblea completa), ofreciendo miles de tokens por segundo para modelos Llama 3.',
    website: 'https://cerebras.ai/inference',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Wafer Scale',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '1 millon de tokens gratuitos al dia durante la fase de lanzamiento.' },
    tradeoffs: {
      pros: ['Velocidad de generacion de texto mas rapida documentada en la historia de la computacion', 'Permite flujos de razonamiento y validacion iterativa en fracciones de segundo', 'API compatible con OpenAI'],
      cons: ['Hardware propietario muy especializado exclusivo de Cerebras', 'Seleccion de modelos disponible mas acotada que en nubes tradicionales de GPUs'],
      sacrifices: ['Sacrificas variedad de catalogo de modelos a cambio de la maxima velocidad de computo fisica del mercado.'],
      idealFor: ['Sistemas de busqueda iterativa (deep research)', 'Agentes autonomos que requieren multiples reflexiones consecutivas'],
      avoidIf: ['Aplicaciones que dependen de modelos propietarios de terceros'],
    },
  }),
  defineTech({
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'ai',
    tagline: 'La plataforma comunitaria global donde se construye el futuro de los modelos abiertos.',
    description: 'El GitHub del aprendizaje automatico: alberga mas de 500,000 modelos, datasets y aplicaciones interactivas (Spaces), con bibliotecas esenciales como Transformers y Diffusers.',
    website: 'https://huggingface.co/',
    license: 'Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Open ML Hub',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Alojamiento gratuito de repositorios de modelos y demos en CPU; endpoints de inferencia por hora.' },
    tradeoffs: {
      pros: ['El repositorio universal indispensable de cualquier modelo abierto de audio, vision, texto o video', 'Facilidad para desplegar demos interactivas con Gradio o Streamlit en Spaces', 'Endpoints de inferencia dedicados y serverless en GPUs de última generación'],
      cons: ['Variedad tan descomunal que requiere criterio tecnico para filtrar modelos optimizados para produccion', 'La configuracion de infraestructura en GPU dedicada exige control de costes por hora'],
      sacrifices: ['Sacrificas interfaces corporativas pulidas a favor de libertad absoluta de exploracion de investigacion.'],
      idealFor: ['Investigadores, cientificos de datos e ingenieros de machine learning', 'Despliegue de modelos especializados abiertos'],
      avoidIf: ['Equipos que unicamente buscan consumir un endpoint REST sin saber nada de inteligencia artificial'],
    },
  }),
  defineTech({
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'ai',
    tagline: 'Pasarela unificada y enrutamiento inteligente entre mas de 100 modelos de lenguaje.',
    description: 'API unica que permite acceder a modelos de OpenAI, Anthropic, Google, Meta, Mistral y docenas mas con una sola clave, balanceo de carga automatico y comparacion de precios en tiempo real.',
    website: 'https://openrouter.ai/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Unified Gateway',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Acceso a multiples modelos de codigo abierto 100% gratuitos y facturacion directa por token.' },
    tradeoffs: {
      pros: ['Elimina el bloqueo con un solo proveedor: cambia de modelo o proveedor de inferencia modificando una sola palabra', 'Precios de reventa competitivos sin recargos abusivos', 'Permite enrutar a modelos gratuitos de prueba para entornos de desarrollo'],
      cons: ['Dependencia de un intermediario adicional en la cadena de transmision de peticiones', 'Algunas caracteristicas muy especificas de proveedores punteros (como ciertas herramientas nativas) tardan unos dias en llegar'],
      sacrifices: ['Sacrificas relacion comercial directa con el laboratorio original a cambio de redundancia e independencia total.'],
      idealFor: ['Cualquier desarrollador o startup que no quiera atarse a un unico laboratorio de IA', 'Pruebas de modelos comparativas'],
      avoidIf: ['Contratos empresariales que requieren facturacion directa y acuerdos de confidencialidad BAA con un solo gigante cloud'],
    },
  }),
  defineTech({
    id: 'langfuse',
    name: 'Langfuse',
    category: 'ai',
    tagline: 'Plataforma de ingenieria para aplicaciones LLM: observabilidad, evaluaciones y gestion de prompts.',
    description: 'Herramienta de codigo abierto para monitorizar llamadas a LLMs, costes por usuario, latencias de ejecucion, gestion centralizada de prompts y evaluacion automatica de respuestas.',
    website: 'https://langfuse.com/',
    license: 'MIT',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'LLM Observability',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '50,000 observaciones al mes gratuitas en cloud o 100% libre para self-hosting.' },
    tradeoffs: {
      pros: ['Trazabilidad visual clara de cadenas completas de llamadas a modelos y bases vectoriales', 'Gestion versionada de prompts desde la interfaz sin redeployar la aplicacion', 'Codigo abierto disponible para correr localmente junto con tu base de datos'],
      cons: ['Requiere anadir llamadas de instrumentacion o SDK en el codigo de backend', 'Capacidades de testing continuo que requieren configurar conjuntos de datos de referencia (golden datasets)'],
      sacrifices: ['Sacrificas unos minutos de configuracion a cambio de visibilidad completa del gasto y rendimiento de tus modelos.'],
      idealFor: ['Cualquier aplicacion en produccion que consuma APIs de IA', 'Equipos que optimizan costes por prompt y tokens'],
      avoidIf: ['Scripts desechables de un solo uso'],
    },
  }),
  defineTech({
    id: 'portkey',
    name: 'Portkey',
    category: 'ai',
    tagline: 'Gateway y plano de control para gestionar el trafico de LLMs en produccion.',
    description: 'Ofrece enrutamiento con conmutacion por error automatica (failover), reintentos exponenciales, balanceo de carga, cache semantica de respuestas y defensas de seguridad (guardrails).',
    website: 'https://portkey.ai/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'AI Gateway',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '10,000 solicitudes al mes gratuitas en el plan Developer.' },
    tradeoffs: {
      pros: ['Conmutacion por error automatica si OpenAI sufre una caida, redirigiendo la llamada a Anthropic o Azure de forma invisible', 'Cache semantica que ahorra costes y responde en milisegundos a preguntas repetidas', 'Reglas de limitacion de gasto por clave y proteccion contra inyeccion de prompts'],
      cons: ['Punto unico de entrada de trafico a tus modelos que debe ser altamente confiable', 'Menos especializado en gestion documental profunda que plataformas RAG dedicadas'],
      sacrifices: ['Sacrificas arquitectura sin intermediarios a favor de una resiliencia de nivel de 99.99% de uptime.'],
      idealFor: ['Aplicaciones comerciales criticas que no pueden tolerar una caida de la API de un proveedor', 'SaaS multi-tenant'],
      avoidIf: ['Experimentos basicos sin usuarios reales'],
    },
  }),
  defineTech({
    id: 'braintrust',
    name: 'Braintrust',
    category: 'ai',
    tagline: 'Plataforma de evaluacion rigurosa, observabilidad y mejora continua de software con IA.',
    description: 'Entorno para crear conjuntos de evaluacion continua (evals), comparar la calidad de diferentes versiones de prompts y modelos en CI/CD y registrar trazas de produccion.',
    website: 'https://www.braintrust.dev/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'AI Evaluation',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Plan gratuito para proyectos individuales y evaluacion en equipos pequenos.' },
    tradeoffs: {
      pros: ['Enfoque estricto en pruebas automatizadas y puntuaciones de calidad objetivas para modelos de lenguaje', 'Integracion fluida en pipelines de integracion continua (CI) para evitar regresiones de prompts', 'Dashboard de evaluacion rapido y muy colaborativo'],
      cons: ['Herramienta comercial de pago para volumenes medianos y grandes de evaluacion', 'Exige definir metricas de scoring precisas para aprovechar su potencial'],
      sacrifices: ['Sacrificas rapidez informal a cambio de ingenieria rigurosa y verificable en IA.'],
      idealFor: ['Equipos de ingenieria maduros que reemplazan la intuicion por metricas cientificas de rendimiento de LLM'],
      avoidIf: ['Desarrolladores que solo quieren un chat conversacional sin necesidad de evaluar exactitud factual'],
    },
  }),
  defineTech({
    id: 'ollama',
    name: 'Ollama',
    category: 'ai',
    tagline: 'Ejecuta modelos de lenguaje abiertos (Llama 3, DeepSeek, Qwen) en tu ordenador o servidor local.',
    description: 'La forma mas sencilla y eficiente de ejecutar, personalizar y crear modelos de pesos abiertos de forma local en macOS, Linux y Windows, con aceleracion por GPU y una API REST estilo OpenAI.',
    website: 'https://ollama.com/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Local LLM Standard',
    metrics: { dx: 5, learningCurve: 1, scalability: 3, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito sin ningun coste de licencias.' },
    tradeoffs: {
      pros: ['Privacidad total: tus datos nunca salen de tu ordenador o servidor privado', 'Cero costes de consumo por tokens: ejecuta millones de peticiones gratis en tu propio hardware', 'Descarga y arranque de modelos populares con un solo comando (ollama run llama3)'],
      cons: ['La velocidad y el tamano del modelo estan limitados por la memoria RAM y VRAM de tu propia maquina', 'No compite con modelos masivos de frontera como Claude 3.5 Sonnet en tareas hipercomplejas'],
      sacrifices: ['Sacrificas la inteligencia de modelos de frontera de cientos de miles de millones de parametros a favor de privacidad y coste cero.'],
      idealFor: ['Desarrollo local sin conexion a internet', 'Procesamiento de datos altamente confidenciales o medicos', 'Herramientas CLI'],
      avoidIf: ['Aplicaciones en produccion que atienden concurrentemente a miles de usuarios simultaneos sin una granja de GPUs propia'],
    },
  }),
];
