import type { Technology } from '../types';
import { defineTech } from './builder';

export const AUTH_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'clerk',
    name: 'Clerk Auth',
    category: 'auth',
    tagline: 'La mejor experiencia de usuario y componentes pre-diseñados para autenticación en Next.js y React.',
    description: 'Solución completa de autenticación y gestión de usuarios con componentes UI drop-in impecables, soporte multi-tenant y passkeys.',
    website: 'https://clerk.com',
    badgeText: 'Top-tier DX Auth',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'high', hasFreeTier: true, limitsDescription: '10.000 usuarios activos mensuales (MAU) gratuitos. $0.02 por MAU adicional al escalar.' },
    tradeoffs: {
      pros: ['Implementación en menos de 10 minutos con componentes UI listos.', 'Soporte excelente de organizaciones B2B y multi-session.', 'SDKs optimizados para React y Next.js App Router.'],
      cons: ['Vendor lock-in alto con la plataforma de Clerk.', 'Coste elevado si la base de usuarios escala a 50k+ MAU ($850/mes).'],
      sacrifices: ['Sacrificas previsibilidad de costes en productos B2C masivos con bajo ingreso por usuario.'],
      idealFor: ['SaaS B2B con pricing por asiento', 'Proyectos que priorizan lanzar auth en 1 hora'],
      avoidIf: ['Aplicaciones B2C virales con millones de usuarios gratuitos no monetizados'],
    },
  }),
  defineTech({
    id: 'supabase-auth',
    name: 'Supabase Auth',
    category: 'auth',
    tagline: 'Autenticación nativa integrada con Row Level Security en PostgreSQL.',
    description: 'Sistema de autenticación basado en GoTrue con soporte de proveedores OAuth, magic links, SMS y tokens JWT integrados en Postgres.',
    website: 'https://supabase.com/auth',
    badgeText: 'Native Postgres Auth',
    license: 'Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '50.000 MAU gratuitos incluidos en el free tier de Supabase.' },
    tradeoffs: {
      pros: ['Los usuarios residen en la tabla auth.users de tu propia base de datos SQL.', 'Permite políticas RLS seguras sin backend intermediario.', 'Tier gratuito masivo (50k MAU).'],
      cons: ['Componentes de interfaz gráfica más básicos que Clerk (debes diseñar los formularios).'],
      sacrifices: ['Sacrificas componentes preconstruidos estilo copiar y pegar de Clerk.'],
      idealFor: ['Cualquier proyecto que utilice Supabase como base de datos', 'SaaS con presupuestos controlados'],
      avoidIf: ['Sistemas sin PostgreSQL'],
    },
  }),
  defineTech({
    id: 'auth0',
    name: 'Auth0 by Okta',
    category: 'auth',
    tagline: 'El estándar corporativo para federación de identidades y Single Sign-On (SSO).',
    description: 'Plataforma de identidad empresarial con soporte de SAML, LDAP, MFA avanzado y cumplimiento normativo estricto.',
    website: 'https://auth0.com',
    badgeText: 'Enterprise Standard',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 3, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'high', scalingRisk: 'high', hasFreeTier: true, limitsDescription: '7.500 usuarios activos mensuales gratuitos.' },
    tradeoffs: {
      pros: ['Aceptado de inmediato por los departamentos de seguridad de grandes corporaciones.', 'Soporte SAML / Enterprise Connection probado.'],
      cons: ['Precios corporativos muy elevados al activar add-ons enterprise.', 'Panel de control denso y configuración compleja.'],
      sacrifices: ['Sacrificas DX moderna y agilidad para desarrolladores individuales.'],
      idealFor: ['Ventas a corporaciones que exigen conexión con Active Directory o Okta'],
      avoidIf: ['Startups en fase pre-semilla con presupuesto limitado'],
    },
  }),
  defineTech({
    id: 'better-auth',
    name: 'Better Auth',
    category: 'auth',
    tagline: 'El framework de autenticación moderno más completo, tipado y auto-hospedable para TypeScript.',
    description: 'Librería de autenticación agnóstica de framework que corre en tu propio servidor o edge con soporte de plugins (2FA, passkeys, multi-tenant).',
    website: 'https://better-auth.com',
    badgeText: 'Self-Hosted TypeScript',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 3, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% open source y gratuito; corre dentro de tu propia infraestructura.' },
    tradeoffs: {
      pros: ['Zero vendor lock-in y cero costes por usuario activo al escalar.', 'Tipado perfecto e inferencia en el cliente.', 'Arquitectura extensible basada en plugins.'],
      cons: ['Proyecto más joven que Auth.js o Passport.'],
      sacrifices: ['Sacrificas soporte gestionado 24/7 de un proveedor en la nube.'],
      idealFor: ['Desarrolladores que quieren control total de sus usuarios en TypeScript sin costes cloud'],
      avoidIf: ['Equipos que no deseen responsabilizarse de la seguridad de sesiones en su servidor'],
    },
  }),
  defineTech({
    id: 'authjs',
    name: 'Auth.js (NextAuth)',
    category: 'auth',
    tagline: 'Autenticación open-source de referencia para el ecosistema React y Next.js.',
    description: 'Solución open-source agnóstica de base de datos con decenas de proveedores OAuth listos y manejo de sesiones JWT en el servidor.',
    website: 'https://authjs.dev',
    badgeText: 'Open Source Community',
    license: 'ISC',
    isManaged: false,
    isOpenSource: true,
    metrics: { dx: 3, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Código abierto y sin costes de uso.' },
    tradeoffs: {
      pros: ['Totalmente gratuito sin límite de usuarios.', 'Integración profunda con Next.js App Router.', 'Gran cantidad de adaptadores de bases de datos.'],
      cons: ['La transición de NextAuth v4 a Auth.js v5 generó fricciones en la documentación.'],
      sacrifices: ['Sacrificas la facilidad plug-and-play de componentes visuales de Clerk.'],
      idealFor: ['Proyectos Next.js con autenticación simple basada en OAuth (GitHub, Google)'],
      avoidIf: ['Proyectos estáticos puros o que requieran gestión avanzada de roles y organizaciones complejas'],
    },
  }),
  defineTech({
    id: 'kinde',
    name: 'Kinde Auth',
    category: 'auth',
    tagline: 'Autenticación simple, segura y con soporte nativo de multi-tenancy para SaaS B2B.',
    description: 'Plataforma de autenticación para desarrolladores con gestión de organizaciones, SSO empresarial y feature flags integradas.',
    website: 'https://kinde.com',
    badgeText: 'B2B SaaS Auth',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Free tier con hasta 7.500 MAU gratuitos y organizaciones ilimitadas.' },
    tradeoffs: {
      pros: ['Soporte multi-inquilino de fábrica sin coste adicional.', 'Componentes limpios y SDKs para múltiples lenguajes.'],
      cons: ['Menos conocido que Clerk o Auth0 en el mercado de Estados Unidos.'],
      sacrifices: ['Sacrificas la abundancia de tutoriales comunitarios de terceros.'],
      idealFor: ['SaaS B2B que necesitan multi-tenant rápido con organizaciones por cliente'],
      avoidIf: ['Aplicaciones offline o que requieran base de datos on-premise'],
    },
  }),
  defineTech({
    id: 'logto',
    name: 'Logto',
    category: 'auth',
    tagline: 'La alternativa open-source moderna y hermosa a Auth0.',
    description: 'Plataforma de gestión de identidades y accesos (IAM) con protocolo OIDC, soporte multi-tenant y panel de control web pulido.',
    website: 'https://logto.io',
    badgeText: 'Open Source IAM',
    license: 'MPL-2.0',
    isManaged: true,
    isOpenSource: true,
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Cloud ofrece plan gratuito de hasta 50.000 MAU; versión auto-hospedable libre.' },
    tradeoffs: {
      pros: ['Auto-hospedable en Docker con control total de datos.', 'Soporte OIDC nativo compatible con cualquier framework.', 'Panel administrativo moderno.'],
      cons: ['Ecosistema de extensiones más joven que Keycloak.'],
      sacrifices: ['Sacrificas plugins de integración con directorios legacy antiquísimos.'],
      idealFor: ['Startups y empresas que buscan una experiencia tipo Auth0 sin sus precios desorbitados'],
      avoidIf: ['Sistemas monolíticos que no soporten protocolos OAuth2/OIDC estándar'],
    },
  }),
  defineTech({
    id: 'stytch',
    name: 'Stytch',
    category: 'auth',
    tagline: 'Infraestructura de autenticación especializada en passwordless, passkeys y APIs B2B.',
    description: 'Plataforma enfocada en experiencias sin contraseñas: biometría WebAuthn, magic links, OTP y protección contra fraude.',
    website: 'https://stytch.com',
    badgeText: 'Passwordless & Passkeys',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 3, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '10.000 usuarios activos mensuales gratuitos en plan Developer.' },
    tradeoffs: {
      pros: ['Soporte de passkeys y WebAuthn más refinado de la industria.', 'Detección de bots y prevención de ataques de fuerza bruta.'],
      cons: ['Modelo API-first requiere diseñar los flujos de UI manualmente.'],
      sacrifices: ['Sacrificas componentes prefabricados que se pegan en 1 línea de código.'],
      idealFor: ['Apps móviles modernas', 'SaaS con estándares de seguridad elevados sin contraseñas'],
      avoidIf: ['Proyectos que busquen componentes prehechos tipo Clerk'],
    },
  }),
  defineTech({
    id: 'descope',
    name: 'Descope',
    category: 'auth',
    tagline: 'Plataforma de flujos de autenticación visual drag-and-drop sin código.',
    description: 'Servicio de identidad para diseñar journeys de usuario, autenticación adaptativa y SSO mediante un lienzo visual interactivo.',
    website: 'https://descope.com',
    badgeText: 'Visual Flows IAM',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Free tier generoso con hasta 7.500 MAU.' },
    tradeoffs: {
      pros: ['Permite a equipos de producto modificar los flujos de login sin tocar código.', 'Autenticación basada en riesgo adaptativa.'],
      cons: ['Menor control a bajo nivel del código fuente del flujo de login.'],
      sacrifices: ['Sacrificas control imperativo tradicional en código.'],
      idealFor: ['Equipos con product managers activos iterando en conversión de onboarding'],
      avoidIf: ['Desarrolladores puristas que desean 100% de la lógica en archivos de código fuente'],
    },
  }),
  defineTech({
    id: 'workos',
    name: 'WorkOS',
    category: 'auth',
    tagline: 'El puente para hacer tu software Enterprise-Ready con SSO SAML y SCIM en días.',
    description: 'Conjunto de APIs modulares para agregar Single Sign-On empresarial, sincronización de directorios SCIM y logs de auditoría.',
    website: 'https://workos.com',
    badgeText: 'Enterprise Ready Auth',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Autenticación básica AuthKit gratuita hasta 1M de usuarios; SSO empresarial con coste por conexión.' },
    tradeoffs: {
      pros: ['AuthKit ofrece un diseño visual del nivel de Vercel/Linear.', 'Integración trivial con Okta, Azure AD y Google Workspace.'],
      cons: ['Las conexiones de SSO empresarial de clientes tienen coste mensual por conexión.'],
      sacrifices: ['Sacrificas soluciones caseras de SAML gratuitas pero difíciles de mantener.'],
      idealFor: ['Startups B2B que necesitan cerrar contratos con clientes enterprise que exigen SAML/SCIM'],
      avoidIf: ['Aplicaciones B2C orientadas al consumidor final'],
    },
  }),
  defineTech({
    id: 'firebase-auth',
    name: 'Firebase Authentication',
    category: 'auth',
    tagline: 'El servicio de autenticación gestionado de Google para web y móvil.',
    description: 'Servicio de identidad escalable respaldado por Google Cloud con soporte de email, SMS, redes sociales y multi-tenancy.',
    website: 'https://firebase.google.com/products/auth',
    badgeText: 'Google Cloud Auth',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '50.000 usuarios activos mensuales gratuitos para la mayoría de proveedores.' },
    tradeoffs: {
      pros: ['Escala automáticamente a millones de usuarios sin configuración.', 'Excelente soporte nativo en iOS, Android y Flutter.'],
      cons: ['Atado a la consola de Google Cloud/Firebase.', 'El coste de verificación por SMS es elevado.'],
      sacrifices: ['Sacrificas portabilidad a proveedores fuera de la nube de Google.'],
      idealFor: ['Apps móviles multiplataforma en Flutter o React Native', 'Proyectos del ecosistema Google Cloud'],
      avoidIf: ['Desarrolladores que prefieran stacks de código abierto independientes'],
    },
  }),
  defineTech({
    id: 'keycloak',
    name: 'Keycloak IAM',
    category: 'auth',
    tagline: 'El servidor de identidad y gestión de accesos open-source estándar de Red Hat.',
    description: 'Servidor completo de autenticación corporativa con soporte integral de OpenID Connect, OAuth 2.0, SAML 2.0 y federación LDAP.',
    website: 'https://keycloak.org',
    badgeText: 'Enterprise Open Source',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Completamente open source y gratuito; requiere servidor propio (JVM).' },
    tradeoffs: {
      pros: ['Capacidades enterprise sin pagar licencias millonarias.', 'Soporta cualquier topología de seguridad corporativa.'],
      cons: ['Requiere recursos significativos de memoria (JVM en Java).', 'Curva de administración y configuración compleja.'],
      sacrifices: ['Sacrificas la agilidad y ligereza de soluciones cloud modernas como Clerk.'],
      idealFor: ['Entornos de gobierno, banca e instituciones con requisitos estrictos de soberanía de datos'],
      avoidIf: ['Startups pequeñas que busquen configurar auth en 15 minutos'],
    },
  }),
];
