import type { Technology } from '../types';
import { defineTech } from './builder';

export const BACKEND_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'fastapi',
    name: 'FastAPI',
    category: 'backend',
    tagline: 'Framework Python asíncrono de alto rendimiento con validación tipada OpenAPI.',
    description: 'Framework web moderno basado en Python 3.10+, Pydantic y Starlette para crear APIs REST con documentación Swagger automática.',
    website: 'https://fastapi.tiangolo.com',
    badgeText: 'Python Async & AI',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Ejecutable en VPS de $4/mes (Hetzner) o serverless container (Fly.io/Cloud Run).' },
    tradeoffs: {
      pros: ['Documentación interactiva Swagger/ReDoc de fábrica.', 'Ecosistema de Machine Learning e IA líder (LangChain, PyTorch).', 'Tipado estricto con Pydantic.'],
      cons: ['Bloqueo de CPU en tareas síncronas si no se configuran workers asíncronos.', 'Rendimiento menor que Go o Rust en micro-benchmarks puros.'],
      sacrifices: ['Sacrificas velocidad máxima de ejecución a cambio de DX y ecosistema de IA.'],
      idealFor: ['Servicios de Inteligencia Artificial', 'APIs modernas REST', 'Data pipelines'],
      avoidIf: ['Sistemas de ultra-baja latencia sub-milisegundo donde Go/Rust dominan'],
    },
  }),
  defineTech({
    id: 'express',
    name: 'Node.js Express',
    category: 'backend',
    tagline: 'El servidor HTTP minimalista y universal del ecosistema JavaScript.',
    description: 'Framework minimalista y flexible para Node.js con el ecosistema de middleware más extenso del mundo.',
    website: 'https://expressjs.com',
    badgeText: 'Classic Node.js',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 1, scalability: 3, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Corre en cualquier servidor Linux, contenedor Docker o PaaS.' },
    tradeoffs: {
      pros: ['La mayor cantidad de tutoriales y middlewares existentes.', 'Curva de entrada mínima.', 'Fácil de desplegar.'],
      cons: ['Rendimiento superado por frameworks modernos (Fastify, Hono).', 'Falta de estructura de arquitectura de fábrica.'],
      sacrifices: ['Sacrificas optimizaciones de rendimiento modernas y tipado TypeScript nativo.'],
      idealFor: ['APIs sencillas', 'Prototipos rápidos', 'Servicios heredados estables'],
      avoidIf: ['Nuevos proyectos TypeScript donde NestJS, Hono o Fastify ofrecen mejor tipado'],
    },
  }),
  defineTech({
    id: 'nestjs',
    name: 'NestJS',
    category: 'backend',
    tagline: 'Arquitectura empresarial escalable y modular con TypeScript e inyección de dependencias.',
    description: 'Framework progresivo de Node.js con arquitectura modular inspirada en Angular para aplicaciones robustas de nivel corporativo.',
    website: 'https://nestjs.com',
    badgeText: 'Enterprise TypeScript',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 4, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Código abierto y sin costes de licencia corporativa.' },
    tradeoffs: {
      pros: ['Estructura estandarizada con módulos, controladores y servicios.', 'Excelente soporte de microservicios, WebSockets y gRPC.', 'Inyección de dependencias nativa.'],
      cons: ['Verbosidad y curva de aprendizaje más elevada que Express.', 'Arranque en frío perceptible en serverless efímero.'],
      sacrifices: ['Sacrificas agilidad de prototipado rápido en un solo archivo.'],
      idealFor: ['Equipos grandes de ingeniería', 'SaaS enterprise modular', 'APIs financieras'],
      avoidIf: ['Funciones serverless efímeras donde el cold start penaliza'],
    },
  }),
  defineTech({
    id: 'go-fiber',
    name: 'Go Fiber',
    category: 'backend',
    tagline: 'Rendimiento extremo en Go con la ergonomía sintáctica de Express.',
    description: 'Framework web construido sobre Fasthttp para Go, diseñado para ofrecer asignación de memoria zero y latencia mínima.',
    website: 'https://gofiber.io',
    badgeText: 'Zero Memory Allocation',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Consume menos de 20MB de RAM; corre en el tier más barato de cualquier nube.' },
    tradeoffs: {
      pros: ['Rendimiento de cientos de miles de peticiones por segundo.', 'Consumo de RAM mínimo.', 'Binario único compilado estático sin runtime externo.'],
      cons: ['No compatible con el paquete net/http nativo estándar de Go.', 'Menor ecosistema de ORMs comparado con TypeScript/Python.'],
      sacrifices: ['Sacrificas dinamismo de lenguajes interpretados para mutar esquemas sobre la marcha.'],
      idealFor: ['Microservicios de alta concurrencia', 'Gateways de red', 'APIs de telemetría'],
      avoidIf: ['Aplicaciones con lógica de negocio que cambie cada hora donde Python/Node son más rápidos de escribir'],
    },
  }),
  defineTech({
    id: 'go-gin',
    name: 'Go Gin',
    category: 'backend',
    tagline: 'El framework HTTP estándar y battle-tested del ecosistema Go.',
    description: 'Framework web HTTP para Go con enrutador basado en Radix Tree, middleware eficiente y compatibilidad net/http.',
    website: 'https://gin-gonic.com',
    badgeText: 'Go Standard',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Binario estático compilado desplegable en cualquier infraestructura.' },
    tradeoffs: {
      pros: ['Madurez absoluta en producción corporativa.', 'Excelente rendimiento y concurrencia con goroutines.', 'Gran cantidad de librerías de terceros.'],
      cons: ['Manejo de errores explícito en Go puede sentirse repetitivo.'],
      sacrifices: ['Sacrificas velocidad de prototipado inicial frente a frameworks fullstack como Rails.'],
      idealFor: ['Sistemas de backend distribuidos', 'Servicios core de alta disponibilidad', 'APIs de producción'],
      avoidIf: ['Desarrolladores sin experiencia en Go que busquen lanzar en 24 horas'],
    },
  }),
  defineTech({
    id: 'hono',
    name: 'Hono',
    category: 'backend',
    tagline: 'Framework ultrafino y universal para Cloudflare Workers, Bun, Deno y Node.js.',
    description: 'Framework ultraligero (<15 kB) optimizado para plataformas Edge con tipado TypeScript de extremo a extremo y enrutamiento ultra-rápido.',
    website: 'https://hono.dev',
    badgeText: 'Multi-Runtime Edge',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100k invocaciones/día gratuitas en Cloudflare Workers.' },
    tradeoffs: {
      pros: ['Arranque en frío casi nulo (<5ms en Edge).', 'Tipado RPC de cliente a servidor out-of-the-box.', 'Corre en cualquier runtime moderno (Node, Deno, Bun, Cloudflare, Fastly).'],
      cons: ['Menor cantidad de plugins empaquetados frente a NestJS.'],
      sacrifices: ['Sacrificas estructuras complejas de inyección de dependencias empresariales.'],
      idealFor: ['APIs en el Edge', 'Microservicios serverless', 'Local-first backends con Turso'],
      avoidIf: ['Monolitos legacy pesados dependientes de librerías exclusivas de Node.js antiguas'],
    },
  }),
  defineTech({
    id: 'elysia',
    name: 'Elysia.js',
    category: 'backend',
    tagline: 'Framework ergonómico de máxima velocidad diseñado nativamente para Bun.',
    description: 'Framework optimizado para Bun con tipado estricto mediante TypeBox, OpenAPI automático y rendimiento superior a Express.',
    website: 'https://elysiajs.com',
    badgeText: 'Bun Native',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Código abierto y ligero en consumo de memoria.' },
    tradeoffs: {
      pros: ['Velocidad de ejecución y I/O líder en benchmarks de JavaScript.', 'Inferencia de tipos automática en rutas y clientes.', 'Integración nativa con Bun.'],
      cons: ['Dependencia del runtime Bun en producción.'],
      sacrifices: ['Sacrificas estabilidad conservadora de Node.js LTS en entornos bancarios.'],
      idealFor: ['APIs de alto tráfico en Bun', 'Startups tecnológicas que buscan máxima velocidad en TypeScript'],
      avoidIf: ['Infraestructuras rígidas restringidas a Node.js oficial'],
    },
  }),
  defineTech({
    id: 'fastify',
    name: 'Fastify',
    category: 'backend',
    tagline: 'El framework de Node.js centrado en máximo rendimiento y bajo overhead.',
    description: 'Framework rápido y de bajo overhead para Node.js con sistema de plugins asíncronos y serialización JSON ultrarrápida.',
    website: 'https://fastify.dev',
    badgeText: 'Low Overhead Node',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source bajo licencia MIT.' },
    tradeoffs: {
      pros: ['Hasta 2x más rápido que Express en serialización.', 'Sistema de plugins con encapsulación limpia.', 'Soporte TypeScript maduro.'],
      cons: ['Paradigma de ciclo de vida de plugins requiere comprensión previa.'],
      sacrifices: ['Sacrificas la simplicidad casi ingenua de Express a cambio de velocidad y arquitectura.'],
      idealFor: ['APIs de producción en Node.js', 'Microservicios con alto volumen de JSON'],
      avoidIf: ['Scripts desechables de menos de 50 líneas'],
    },
  }),
  defineTech({
    id: 'django',
    name: 'Django',
    category: 'backend',
    tagline: 'El framework web con baterías incluidas para perfectionists with deadlines.',
    description: 'Framework Python de alto nivel con ORM completo, panel de administración generado automáticamente, autenticación y migraciones de datos robustas.',
    website: 'https://djangoproject.com',
    badgeText: 'Batteries Included',
    license: 'BSD-3-Clause',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Desplegable en cualquier servidor Linux sin licencias.' },
    tradeoffs: {
      pros: ['Panel de administración automático más potente de la industria.', 'ORM seguro que previene inyecciones SQL.', 'Módulos de seguridad y auth integrados de fábrica.'],
      cons: ['Estructura monolítica más rígida.', 'Soporte asíncrono secundario comparado con FastAPI.'],
      sacrifices: ['Sacrificas ligereza y flexibilidad para montar microservicios desacoplados.'],
      idealFor: ['SaaS con modelos de datos complejos', 'Plataformas de contenido', 'Startups que necesitan admin panel el primer día'],
      avoidIf: ['Microservicios diminutos de una sola ruta HTTP'],
    },
  }),
  defineTech({
    id: 'flask',
    name: 'Flask',
    category: 'backend',
    tagline: 'Microframework Python flexible y minimalista sin decisiones impuestas.',
    description: 'Framework ligero basado en Werkzeug y Jinja para construir desde micro-APIs hasta servicios complejos mediante extensiones modulares.',
    website: 'https://flask.palletsprojects.com',
    badgeText: 'Python Microframework',
    license: 'BSD-3-Clause',
    metrics: { dx: 4, learningCurve: 2, scalability: 3, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Gratuito y compatible con cualquier host Python.' },
    tradeoffs: {
      pros: ['Libertad total para elegir ORM, base de datos y estructura.', 'Curva de aprendizaje muy accesible.'],
      cons: ['Requiere configurar manualmente auth, validación y serialización.'],
      sacrifices: ['Sacrificas la validación automática OpenAPI nativa de FastAPI.'],
      idealFor: ['Modelos de Machine Learning servidos como API simple', 'Scripts internos'],
      avoidIf: ['APIs REST modernas con especificación OpenAPI estricta donde FastAPI es superior'],
    },
  }),
  defineTech({
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'backend',
    tagline: 'El estándar enterprise indiscutido para el ecosistema Java y Kotlin.',
    description: 'Framework corporativo integral con configuración automática, inyección de dependencias madura y ecosistema Spring Cloud completo.',
    website: 'https://spring.io/projects/spring-boot',
    badgeText: 'Enterprise Java',
    license: 'Apache-2.0',
    metrics: { dx: 3, learningCurve: 5, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source bajo Apache 2.0; consume más memoria RAM que Go.' },
    tradeoffs: {
      pros: ['Respaldo corporativo masivo en bancos y aseguradoras.', 'Bibliotecas probadas para cada protocolo existente.', 'Seguridad enterprise.'],
      cons: ['Consumo de memoria RAM elevado (mínimo 512MB-1GB para arrancar).', 'Tiempos de arranque lentos sin GraalVM native image.'],
      sacrifices: ['Sacrificas agilidad de lanzamiento para startups tempranas.'],
      idealFor: ['Sistemas financieros', 'Core banking', 'Empresas Fortune 500 con equipos de 50+ ingenieros'],
      avoidIf: ['Startups MVP de 1 o 2 desarrolladores buscando iterar cada tarde'],
    },
  }),
  defineTech({
    id: 'rails',
    name: 'Ruby on Rails',
    category: 'backend',
    tagline: 'La doctrina de la felicidad del programador y el lanzamiento rápido de startups.',
    description: 'Framework web full-stack por convención que impulsó a GitHub, Shopify, Stripe y Airbnb con productividad legendaria.',
    website: 'https://rubyonrails.org',
    badgeText: 'Productivity Legend',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Desplegable fácilmente en servidores Hetzner con Kamal o en Fly.io.' },
    tradeoffs: {
      pros: ['Velocidad de construcción de producto inigualable para desarrolladores senior.', 'ActiveRecord es uno de los ORMs más ergonómicos jamás diseñados.', 'Comunidad unida y soporte sólido.'],
      cons: ['Rendimiento por núcleo menor que Go o Rust.', 'Uso de memoria mayor que runtimes compilados.'],
      sacrifices: ['Sacrificas tipado estático nativo de fábrica.'],
      idealFor: ['Startups bootstrap', 'Fundadores técnicos en solitario', 'SaaS transaccionales'],
      avoidIf: ['Sistemas de cálculo matemático intensivo o procesamiento masivo de vídeo en tiempo real'],
    },
  }),
  defineTech({
    id: 'phoenix',
    name: 'Elixir Phoenix',
    category: 'backend',
    tagline: 'Concurrencia masiva tolerante a fallos impulsada por la máquina virtual de Erlang.',
    description: 'Framework web moderno sobre la BEAM con Phoenix LiveView para interfaces en tiempo real sin escribir JavaScript de frontend.',
    website: 'https://phoenixframework.org',
    badgeText: 'BEAM Realtime',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Capaz de mantener millones de conexiones WebSockets en un solo servidor de $20.' },
    tradeoffs: {
      pros: ['Concurrencia y tolerancia a fallos legendaria de Erlang.', 'Phoenix LiveView elimina la necesidad de SPAs para interactividad en tiempo real.', 'Latencia predecible.'],
      cons: ['Curva de programación funcional en Elixir.', 'Menor volumen de talento en el mercado frente a Node/Python.'],
      sacrifices: ['Sacrificas la facilidad de contratar programadores júnior de React/Node.'],
      idealFor: ['Sistemas de mensajería y chat', 'Colaboración en tiempo real tipo Figma', 'Juegos multijugador'],
      avoidIf: ['Equipos sin interés en aprender paradigmas funcionales'],
    },
  }),
  defineTech({
    id: 'rust-axum',
    name: 'Rust Axum',
    category: 'backend',
    tagline: 'Seguridad de memoria, cero sobrecoste y máxima velocidad sobre el ecosistema Tokio.',
    description: 'Framework web modular mantenido por el equipo oficial de Tokio para crear servicios web con seguridad de tipos estricta y velocidad de CPU récord.',
    website: 'https://github.com/tokio-rs/axum',
    badgeText: 'Zero-Cost Rust',
    license: 'MIT',
    metrics: { dx: 3, learningCurve: 5, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Consume entre 10MB y 30MB de RAM en servidores de $3/mes.' },
    tradeoffs: {
      pros: ['Consumo de recursos minúsculo y latencia sub-milisegundo.', 'Seguridad de concurrencia garantizada por el compilador de Rust (cero data races).', 'Ecosistema Tokio.'],
      cons: ['Tiempos de compilación prolongados.', 'Curva de aprendizaje del borrow checker y lifetimes.'],
      sacrifices: ['Sacrificas velocidad de iteración en features que cambian a diario.'],
      idealFor: ['Infraestructura crítica', 'Sistemas fintech de alta frecuencia', 'Gateways de red'],
      avoidIf: ['Prototipos desechables para validar ideas en 48 horas'],
    },
  }),
  defineTech({
    id: 'rust-actix',
    name: 'Rust Actix-web',
    category: 'backend',
    tagline: 'El framework web con los puntajes más altos del mundo en TechEmpower benchmarks.',
    description: 'Framework web extremadamente rápido para Rust con modelo de actores y soporte HTTP/1.x y HTTP/2 nativo.',
    website: 'https://actix.rs',
    badgeText: 'Benchmark Champion',
    license: 'MIT',
    metrics: { dx: 3, learningCurve: 5, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Throughput de más de 1 millón de req/s en hardware estándar.' },
    tradeoffs: {
      pros: ['Velocidad absoluta de procesamiento.', 'Madurez en producción durante años.', 'Manejo estricto de tipos.'],
      cons: ['Complejidad sintáctica en tipado de extractores y middlewares.'],
      sacrifices: ['Sacrificas la ergonomía modular que ofrece Axum con Tokio directo.'],
      idealFor: ['Microservicios de computación masiva', 'APIs de telemetría de IoT'],
      avoidIf: ['CRUDs convencionales donde el cuello de botella es la base de datos'],
    },
  }),
  defineTech({
    id: 'aspnet-core',
    name: 'ASP.NET Core',
    category: 'backend',
    tagline: 'Rendimiento de primer nivel con tipado estricto en C# y soporte LTS de Microsoft.',
    description: 'Framework multiplataforma open source para C# con rendimiento extraordinario en Linux y Windows, Minimal APIs y gRPC.',
    website: 'https://dotnet.microsoft.com/apps/aspnet',
    badgeText: 'Modern .NET Core',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Corre nativamente en contenedores Linux sin coste de Windows Server.' },
    tradeoffs: {
      pros: ['Rendimiento en el top 10 mundial de TechEmpower.', 'Sintaxis de C# moderna y expresiva.', 'Herramientas de depuración y profiling líderes.'],
      cons: ['Percepción histórica errónea de dependencia de Windows.'],
      sacrifices: ['Sacrificas la ligereza de lenguajes de scripting interpretados.'],
      idealFor: ['SaaS B2B de alto volumen', 'Servicios empresariales', 'Sistemas con procesamiento intensivo'],
      avoidIf: ['Equipos alérgicos al ecosistema .NET'],
    },
  }),
  defineTech({
    id: 'laravel',
    name: 'Laravel',
    category: 'backend',
    tagline: 'El framework PHP elegante para artesanos de la web con el ecosistema más completo.',
    description: 'Framework full-stack con ORM Eloquent, sistema de colas integrado, autenticación y despliegue automatizado con Laravel Forge/Vapor.',
    website: 'https://laravel.com',
    badgeText: 'PHP Modern Ecosystem',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Desplegable en cualquier hosting compartido o VPS por $5/mes.' },
    tradeoffs: {
      pros: ['Documentación ejemplar.', 'Eloquent ORM extraordinariamente intuitivo.', 'Herramientas satélite oficiales (Pulse, Horizon, Telescope, Nova).'],
      cons: ['Rendimiento por petición menor que Go o Node sin Octane/Swoole.'],
      sacrifices: ['Sacrificas concurrencia asíncrona nativa por proceso.'],
      idealFor: ['SaaS con facturación y suscripciones', 'Marketplaces', 'Agencias de desarrollo'],
      avoidIf: ['Sistemas de streaming o WebSockets con cientos de miles de conexiones persistentes sin Redis'],
    },
  }),
  defineTech({
    id: 'adonisjs',
    name: 'AdonisJS',
    category: 'backend',
    tagline: 'El framework MVC con baterías incluidas para Node.js y TypeScript.',
    description: 'Framework fullstack para Node.js que aporta la claridad arquitectónica de Laravel y Rails al ecosistema nativo de TypeScript.',
    website: 'https://adonisjs.com',
    badgeText: 'TypeScript MVC',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 3, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source bajo licencia MIT.' },
    tradeoffs: {
      pros: ['Lucid ORM potente y tipado.', 'Autenticación, migraciones y validadores de fábrica.', 'Arquitectura coherente sin reinventar la rueda.'],
      cons: ['Comunidad más pequeña que Express o NestJS.'],
      sacrifices: ['Sacrificas la inercia masiva de NestJS en ofertas de empleo enterprise.'],
      idealFor: ['Desarrolladores que añoran Laravel en TypeScript', 'Startups enfocadas en lanzar rápido'],
      avoidIf: ['Equipos que prefieren micro-librerías desacopladas en vez de un framework MVC'],
    },
  }),
];
