import type { Technology } from '../types';
import { defineTech } from './builder';

export const CICD_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'github-actions',
    name: 'GitHub Actions',
    category: 'cicd',
    tagline: 'Automatizacion nativa de integracion y despliegue continuo integrada en GitHub.',
    description: 'Permite automatizar pruebas, empaquetado y despliegues directamente desde cualquier evento en tu repositorio de GitHub, con un marketplace gigantesco de acciones reutilizables.',
    website: 'https://github.com/features/actions',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Industry Standard',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '2,000 minutos de ejecucion al mes gratuitos en repositorios privados; ilimitado para open source.' },
    tradeoffs: {
      pros: ['Integracion inmediata con Pull Requests, checks y secrets de GitHub sin herramientas externas', 'Marketplace con decenas de miles de ' + 'actions' + ' prediseñadas por la comunidad', 'Soporte para self-hosted runners en tu propia infraestructura para acelerar tiempos de build'],
      cons: ['Sintaxis de YAML propensa a errores en workflows extremadamente complejos', 'Tiempos de arranque de maquinas virtuales compartidas ligeramente variables'],
      sacrifices: ['Sacrificas portabilidad directa a otras plataformas de Git sin reescribir workflows.'],
      idealFor: ['Cualquier proyecto alojado en GitHub', 'Pipelines de testeo, linting y publicacion automatica a NPM/Docker'],
      avoidIf: ['Equipos cuya infraestructura y codigo residen estrictamente en GitLab o servidores internos aislados'],
    },
  }),
  defineTech({
    id: 'gitlab-ci',
    name: 'GitLab CI/CD',
    category: 'cicd',
    tagline: 'Suite completa de ciclo de vida DevOps y ejecucion de pipelines integrada.',
    description: 'Solucion DevOps de codigo abierto unificada que cubre desde la gestion de incidencias y repositorios Git hasta compilaciones en contenedores, seguridad estatica (SAST) y despliegues.',
    website: 'https://about.gitlab.com/stages-devops-lifecycle/continuous-integration/',
    license: 'MIT',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'DevOps Lifecycle',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '400 minutos mensuales gratuitos en GitLab SaaS o 100% ilimitado en self-hosted.' },
    tradeoffs: {
      pros: ['Sintaxis de pipelines .gitlab-ci.yml madura, modular y con excelente herencia', 'Escaneo de seguridad de dependencias y vulnerabilidades integrado de serie', 'Capacidad total de auto-alojar en servidores propios para soberania total'],
      cons: ['El limite de minutos de computo en su plan SaaS gratuito es mas restringido que el de GitHub', 'La interfaz de GitLab puede resultar sobrecargada si solo se busca un repositorio simple'],
      sacrifices: ['Sacrificas sencillez minima a cambio de una suite DevOps corporativa unificada.'],
      idealFor: ['Empresas que necesitan self-hosting de su plataforma de codigo', 'Pipelines de seguridad y cumplimiento normativo estricto'],
      avoidIf: ['Proyectos personales pequenos alojados en GitHub'],
    },
  }),
  defineTech({
    id: 'vercel-ci',
    name: 'Vercel Deployment Pipeline',
    category: 'cicd',
    tagline: 'Despliegues continuos sin configuracion con entornos de previsualizacion efimeros.',
    description: 'Canalizacion de CI/CD automatica que detecta cada push a GitHub o GitLab, compila la aplicacion frontend, optimiza imagenes y genera una URL de previsualizacion en segundos.',
    website: 'https://vercel.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Zero-Config CI',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Compilaciones y previsualizaciones gratuitas incluidas en el plan Hobby.' },
    tradeoffs: {
      pros: ['Cero lineas de configuracion YAML para arrancar', 'Entornos de previsualizacion aislados con comentarios en pantalla para colaboracion visual', 'Optimizacion y balanceo automatico de artefactos estaticos'],
      cons: ['No apto para pipelines de pruebas de backend pesadas o despliegues en servidores externos', 'Tiempo maximo de duracion de compilacion limitado'],
      sacrifices: ['Sacrificas control de pasos de infraestructura compleja a cambio de velocidad frontend pura.'],
      idealFor: ['Aplicaciones web con Next.js, SvelteKit, Nuxt o Remix', 'Equipos agiles con revisiones visuales continuas'],
      avoidIf: ['Compilaciones de kernels, microservicios en Go o bases de datos complejas'],
    },
  }),
  defineTech({
    id: 'circleci',
    name: 'CircleCI',
    category: 'cicd',
    tagline: 'Plataforma CI/CD de alta velocidad y paralelismo para equipos de ingenieria exigentes.',
    description: 'Especializada en ejecucion concurrente, almacenamiento en cache inteligente de dependencias y tiempos de compilacion ultra rapidos para suites de pruebas masivas.',
    website: 'https://circleci.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'High Concurrency',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '6,000 creditos de compilacion gratuitos al mes (hasta 30,000 minutos segun maquina).' },
    tradeoffs: {
      pros: ['Paralelizacion avanzada automatica de pruebas para reducir suites de 40 min a 3 min', 'Soporte excelente de entornos Docker, maquinas virtuales Linux, macOS y Windows', 'Sistema de orbs reutilizables y depuracion interactiva por SSH en contenedores fallidos'],
      cons: ['Modelo de facturacion por creditos que requiere atencion a la configuracion de recursos', 'Herramienta externa que requiere autorizar accesos a tu proveedor de Git'],
      sacrifices: ['Sacrificas la integracion nativa en la UI de GitHub por potencia de ejecucion bruta.'],
      idealFor: ['Proyectos con cientos de tests de integracion lentos', 'Equipos con requerimientos de compilacion en macOS para iOS'],
      avoidIf: ['Proyectos sencillos donde un simple workflow de GitHub Actions es suficiente'],
    },
  }),
  defineTech({
    id: 'buildkite',
    name: 'Buildkite',
    category: 'cicd',
    tagline: 'CI/CD hibrido que combina agentes autogestionados veloces con una interfaz cloud segura.',
    description: 'Arquitectura unica donde la interfaz web y orquestacion se gestionan en la nube, pero las pruebas y el codigo se compilan en tus propios servidores (AWS, bare-metal, Mac Stadium) garantizando maxima seguridad y velocidad.',
    website: 'https://buildkite.com/',
    license: 'Proprietary',
    isManaged: false,
    isOpenSource: false,
    badgeText: 'Hybrid CI',
    metrics: { dx: 5, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Plan gratuito para desarrolladores individuales y pequenos equipos.' },
    tradeoffs: {
      pros: ['El codigo fuente y los secretos de produccion nunca salen de tus propios servidores', 'Velocidad de ejecucion insuperable al correr en hardware dedicado de alto rendimiento', 'Escala sin limites artificiales de minutos de compilacion'],
      cons: ['Requiere aprovisionar y mantener los servidores donde corren los agentes de compilacion', 'No es una solucion 100% delegada para quien no quiere gestionar ninguna maquina'],
      sacrifices: ['Sacrificas cero mantenimiento de maquinas a cambio de velocidad extrema y confidencialidad.'],
      idealFor: ['Empresas de tecnologia punteras (Shopify, Uber, Canva)', 'Empresas con estricta propiedad intelectual'],
      avoidIf: ['Equipos que buscan una solucion totalmente gestionada sin tocar servidores de compilacion'],
    },
  }),
  defineTech({
    id: 'docker-hub',
    name: 'Docker Hub',
    category: 'cicd',
    tagline: 'El registro publico y privado de imagenes de contenedores mas grande del mundo.',
    description: 'Servicio central para buscar, compartir y almacenar imagenes de contenedores Docker, con soporte para compilaciones automatizadas vinculadas a repositorios de GitHub y Bitbucket.',
    website: 'https://hub.docker.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Container Hub',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Repositorios publicos ilimitados y 1 repositorio privado gratuito.' },
    tradeoffs: {
      pros: ['Destino por defecto al ejecutar ' + 'docker pull' + ' en cualquier maquina del planeta', 'Escaneo automatizado de vulnerabilidades en imagenes con Docker Scout', 'Integracion universal con cualquier orquestador'],
      cons: ['Limites de tasa de descargas (rate limits) para usuarios anonimos no autenticados', 'Solo 1 repositorio privado gratuito para proyectos comerciales'],
      sacrifices: ['Sacrificas repositorios privados ilimitados frente a alternativas como GitHub Container Registry.'],
      idealFor: ['Distribucion de imagenes de contenedores publicas', 'Estandarizacion de entornos de desarrollo en equipos'],
      avoidIf: ['Proyectos con decenas de microservicios privados que no desean pagar suscripciones adicionales'],
    },
  }),
  defineTech({
    id: 'argocd',
    name: 'Argo CD',
    category: 'cicd',
    tagline: 'Herramienta de entrega continua declarativa basada en GitOps para Kubernetes.',
    description: 'Sincroniza automaticamente el estado deseado definido en repositorios Git con el estado en vivo de los clusters Kubernetes, detectando desalineaciones y revirtiendo cambios no autorizados.',
    website: 'https://argo-cd.readthedocs.io/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'GitOps Standard',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito para desplegar en cualquier cluster Kubernetes.' },
    tradeoffs: {
      pros: ['Estandar de oro para implementar GitOps en entornos nativos de la nube', 'Interfaz web clara para visualizar el estado y la salud de todos los pods y servicios', 'Despliegues seguros ' + 'pull-based' + ' sin exponer credenciales del cluster fuera del firewall'],
      cons: ['Requiere un cluster Kubernetes operativo para funcionar', 'Curva de aprendizaje exigente para desarrolladores no familiarizados con manifiestos de K8s'],
      sacrifices: ['Sacrificas sencillez para proyectos simples a favor de automatizacion enterprise inquebrantable.'],
      idealFor: ['Equipos con infraestructura moderna basada en Kubernetes', 'Grandes empresas con estricto control de auditoria'],
      avoidIf: ['Aplicaciones alojadas en simples VPS o arquitecturas serverless puras'],
    },
  }),
  defineTech({
    id: 'bitbucket-pipelines',
    name: 'Bitbucket Pipelines',
    category: 'cicd',
    tagline: 'Canalizaciones integradas dentro de la suite Atlassian (Jira, Confluence).',
    description: 'Servicio de CI/CD integrado en Bitbucket Cloud que permite compilar, probar y desplegar codigo a partir de un archivo bitbucket-pipelines.yml con conexion transparente con incidencias de Jira.',
    website: 'https://bitbucket.org/product/features/pipelines',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Atlassian Ecosystem',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '50 minutos de compilacion mensuales gratuitos en el plan Free.' },
    tradeoffs: {
      pros: ['Trazabilidad total entre tickets de Jira, ramas de Git y estados de despliegue', 'Configuracion sencilla basada en contenedores Docker estándar', 'Permisos corporativos integrados con Atlassian Access'],
      cons: ['Cuota gratuita de minutos muy escasa comparada con GitHub', 'Comunidad y marketplace de pasos prefabricados mas pequeno'],
      sacrifices: ['Sacrificas la vitalidad de la comunidad open source de GitHub por integracion corporativa Atlassian.'],
      idealFor: ['Empresas cuya gestion de proyectos y requerimientos reside enteramente en Jira'],
      avoidIf: ['Comunidades de software libre o startups modernas enfocadas en GitHub'],
    },
  }),
  defineTech({
    id: 'woodpecker-ci',
    name: 'Woodpecker CI',
    category: 'cicd',
    tagline: 'Fork comunitario y libre de Drone CI para pipelines ligeros en contenedores.',
    description: 'Motor de integracion continua de codigo abierto, impulsado por la comunidad, que ejecuta cada paso del pipeline de forma aislada dentro de contenedores Docker efimeros.',
    website: 'https://woodpecker-ci.org/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Community CI',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 3, community: 4, maturity: 4, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% software libre y sin limites comerciales artificiales.' },
    tradeoffs: {
      pros: ['Extremadamente ligero y rapido de desplegar con Docker Compose', 'Compatible con GitHub, GitLab, Gitea y Forgejo', 'Sintaxis YAML clara y predecible'],
      cons: ['Marketplace de plugins mas reducido que GitHub Actions', 'Requiere que el usuario gestione su propio servidor de pipelines'],
      sacrifices: ['Sacrificas servicios de soporte corporativo comercial por software comunitario autentico.'],
      idealFor: ['Instalaciones auto-alojadas con Gitea o Forgejo', 'Desarrolladores comprometidos con la independencia de la nube'],
      avoidIf: ['Equipos que buscan cero administracion de servidores de testing'],
    },
  }),
  defineTech({
    id: 'drone-ci',
    name: 'Drone CI (Harness)',
    category: 'cicd',
    tagline: 'Plataforma de entrega continua nativa en contenedores pionera en el mercado.',
    description: 'Sistema que revoluciono el mundo de CI/CD al convertir cada tarea de compilacion en un contenedor Docker aislado, garantizando reproducibilidad identica entre local y produccion.',
    website: 'https://www.drone.io/',
    license: 'Polyform-Small-Business',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Container Native',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Gratuito para uso personal y pequenas organizaciones.' },
    tradeoffs: {
      pros: ['Arranque de compilaciones instantaneo y minimo consumo de memoria RAM del sistema', 'Excelente aislamiento gracias a la ejecucion nativa dentro de Docker', 'Instalacion sencilla en servidores locales'],
      cons: ['Cambio de licencia y modelo tras su adquisicion por parte de Harness', 'Menor traccion reciente frente a forks comunitarios y GitHub Actions'],
      sacrifices: ['Sacrificas dinamismo comunitario por un diseno solido y probado historicamente.'],
      idealFor: ['Empresas que ya cuentan con Drone configurado en sus servidores', 'Infraestructuras basadas en contenedores puros'],
      avoidIf: ['Nuevos proyectos que prefieren soluciones nativas en la nube sin mantenimiento de infraestructura'],
    },
  }),
];
