import type { Technology } from '../types';
import { defineTech } from './builder';

export const DATABASE_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'postgres',
    name: 'PostgreSQL Dedicated',
    category: 'database',
    tagline: 'El estándar de oro indiscutido de las bases de datos relacionales ACID.',
    description: 'Sistema de gestión de bases de datos relacional de código abierto con extensibilidad líder (JSONB, pgvector, PostGIS, Timescale).',
    website: 'https://postgresql.org',
    badgeText: 'Relational Gold Standard',
    license: 'PostgreSQL',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Instalable en cualquier VPS de $4/mes con Docker o bare-metal.' },
    tradeoffs: {
      pros: ['Soporte para tipos JSONB que combina lo mejor de SQL y NoSQL.', 'Extensión pgvector para embeddings vectoriales.', 'Portabilidad 100% libre.'],
      cons: ['Requiere configurar pooling de conexiones (PgBouncer) en arquitecturas serverless.', 'Mantenimiento manual de backups y réplicas en VPS.'],
      sacrifices: ['Sacrificas auto-escalado transparente a cero.'],
      idealFor: ['SaaS de cualquier tamaño', 'Sistemas transaccionales ACID', 'Aplicaciones de IA con pgvector'],
      avoidIf: ['Desarrolladores sin experiencia en infraestructura que no quieran gestionar servidores'],
    },
  }),
  defineTech({
    id: 'supabase-db',
    name: 'Supabase Postgres',
    category: 'database',
    tagline: 'Postgres completo gestionado con Row Level Security y APIs automáticas.',
    description: 'Plataforma open source basada en PostgreSQL con extensión PostgREST, WebSockets en tiempo real y autenticación nativa.',
    website: 'https://supabase.com',
    badgeText: 'Managed Postgres & RLS',
    license: 'Apache-2.0',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Free tier con 500MB de datos, 50k usuarios activos y 2 proyectos activos.' },
    tradeoffs: {
      pros: ['Row Level Security (RLS) permite consultar la DB directamente desde el cliente con seguridad.', 'Panel de control visual web impecable.', 'Migraciones y branching de esquemas.'],
      cons: ['Pausa automática de proyectos inactivos en el tier gratuito después de 7 días.', 'Coste mensual fijo de $25 al pasar a Pro.'],
      sacrifices: ['Sacrificas disponibilidad continua en tier gratuito si el proyecto deja de recibir visitas.'],
      idealFor: ['SaaS MVP', 'Apps móviles con React Native/Flutter', 'Desarrollo en solitario'],
      avoidIf: ['Grandes bases de datos con cientos de gigabytes donde el coste de almacenamiento cloud se dispara'],
    },
  }),
  defineTech({
    id: 'neon',
    name: 'Neon Serverless Postgres',
    category: 'database',
    tagline: 'Postgres serverless con branching instantáneo y escala a cero automática.',
    description: 'PostgreSQL desacoplado en almacenamiento y cómputo con ramificación git-like para previews de bases de datos por cada Pull Request.',
    website: 'https://neon.tech',
    badgeText: 'Serverless Branching',
    license: 'Apache-2.0',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '0.5 GiB de almacenamiento gratuito y branching ilimitado.' },
    tradeoffs: {
      pros: ['Branching de base de datos en segundos para staging y tests aislados.', 'Escala a 0 cómputo cuando no hay tráfico para ahorrar 100% de costes.', 'Pooling de conexiones HTTP y WebSockets nativo.'],
      cons: ['Cold start de cómputo perceptible (500ms - 1.5s) al despertar la base de datos tras inactividad.'],
      sacrifices: ['Sacrificas respuesta instantánea en la primera petición tras horas de inactividad.'],
      idealFor: ['Equipos con entornos de staging efímeros en CI/CD', 'Aplicaciones serverless en Vercel'],
      avoidIf: ['Sistemas de backend persistentes con tráfico 24/7 donde el modelo serverless no aporta ahorro'],
    },
  }),
  defineTech({
    id: 'turso',
    name: 'Turso (libSQL)',
    category: 'database',
    tagline: 'SQLite distribuido en el Edge con microsegundos de latencia de lectura.',
    description: 'Base de datos libSQL (fork open-source de SQLite) con replicación global en más de 30 regiones y coste cero de mantenimiento.',
    website: 'https://turso.tech',
    badgeText: 'Distributed SQLite',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Free tier generoso con hasta 500 bases de datos y 9 GB de almacenamiento.' },
    tradeoffs: {
      pros: ['Latencias de lectura de 1 a 5 ms cerca de cualquier usuario.', 'Sintaxis SQL estándar de SQLite simple.', 'Soporta miles de bases de datos multi-tenant aisladas.'],
      cons: ['Las escrituras deben enrutarse a la región primaria.', 'Capacidad analítica menor comparada con PostgreSQL en joins masivos.'],
      sacrifices: ['Sacrificas extensiones avanzadas de PostgreSQL como PostGIS o Timescale.'],
      idealFor: ['Arquitecturas Local-First con réplica local', 'SaaS multi-tenant con 1 base de datos por cliente', 'Edge APIs con Hono'],
      avoidIf: ['Almacenes de datos OLAP para analítica compleja con millones de registros agrupados'],
    },
  }),
  defineTech({
    id: 'mongodb',
    name: 'MongoDB Atlas',
    category: 'database',
    tagline: 'Base de datos documental NoSQL flexible con esquemas JSONB dinámicos.',
    description: 'Base de datos NoSQL líder orientada a documentos BSON con replicación multi-cloud, búsqueda de texto y sharding automático.',
    website: 'https://mongodb.com',
    badgeText: 'Document NoSQL',
    license: 'SSPL',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'high', hasFreeTier: true, limitsDescription: 'Cluster M0 Sandbox con 512MB de almacenamiento gratuito.' },
    tradeoffs: {
      pros: ['Esquemas altamente mutables sin migraciones DDL rígidas.', 'Excelente para catálogos heterogéneos y contenidos dinámicos.'],
      cons: ['Riesgo de inconsistencia de datos sin un modelado riguroso.', 'La licencia SSPL no es OSI open source.', 'Los costes de Atlas escalan rápidamente en producción.'],
      sacrifices: ['Sacrificas la integridad relacional estricta de claves foráneas SQL.'],
      idealFor: ['Catálogos de productos con atributos variables', 'Gestión de contenidos flexibles'],
      avoidIf: ['Aplicaciones financieras con transacciones contables complejas entre múltiples tablas'],
    },
  }),
  defineTech({
    id: 'redis',
    name: 'Upstash Redis',
    category: 'database',
    tagline: 'Almacén en memoria de clave-valor serverless por petición con API REST.',
    description: 'Redis serverless optimizado para arquitecturas serverless con conexión HTTP/REST que evita el agotamiento de sockets de red.',
    website: 'https://upstash.com',
    badgeText: 'Serverless Redis',
    license: 'Proprietary',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '10.000 comandos diarios gratuitos.' },
    tradeoffs: {
      pros: ['Acceso directo desde Edge Functions mediante HTTP fetch sin pools de sockets.', 'Latencia sub-10ms para caché, contadores y rate limiting.', 'Cero costes fijos de servidor.'],
      cons: ['Latencia ligeramente mayor por HTTP que sobre socket TCP directo persistente.'],
      sacrifices: ['Sacrificas persistencia a largo plazo de gigabytes de datos primarios.'],
      idealFor: ['Caché de APIs', 'Rate limiting y throttling', 'Gestión de sesiones efímeras'],
      avoidIf: ['Almacén primario de registros transaccionales'],
    },
  }),
  defineTech({
    id: 'convex',
    name: 'Convex BaaS',
    category: 'database',
    tagline: 'Backend reactivo con sincronización de estado end-to-end 100% en TypeScript.',
    description: 'Base de datos relacional documental con reactividad automática: la interfaz de usuario se actualiza en tiempo real al mutar datos en el servidor.',
    website: 'https://convex.dev',
    badgeText: 'Reactive TypeScript BaaS',
    license: 'Proprietary',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 1, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Free tier generoso con hasta 1M de operaciones mensuales.' },
    tradeoffs: {
      pros: ['Elimina react-query, WebSockets y capas de caché manual.', 'Esquema tipado con TypeScript puro.', 'Transacciones ACID reales garantizadas.'],
      cons: ['Fuerte acoplamiento con la plataforma Convex.', 'Código de queries debe ejecutarse en el entorno de Convex.'],
      sacrifices: ['Sacrificas portabilidad a otras bases de datos SQL tradicionales.'],
      idealFor: ['Apps colaborativas tipo Figma/Linear', 'SaaS rápidos donde la reactividad en tiempo real es vital'],
      avoidIf: ['Sistemas enterprise con requisitos de base de datos on-premise estricta'],
    },
  }),
  defineTech({
    id: 'cockroachdb',
    name: 'CockroachDB Serverless',
    category: 'database',
    tagline: 'PostgreSQL distribuido resiliente a caídas de regiones enteras con escala elástica.',
    description: 'Base de datos SQL global con consistencia serializable ACID distribuida, compatible con el protocolo wire de PostgreSQL.',
    website: 'https://cockroachlabs.com',
    badgeText: 'Distributed SQL Resilient',
    license: 'BSL',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Tier serverless gratuito con 50M de Request Units y 10GB de storage al mes.' },
    tradeoffs: {
      pros: ['Sobrevive a la desconexión de zonas de disponibilidad o regiones enteras sin caída.', 'Consistencia serializable absoluta.', 'Sintaxis PostgreSQL compatible.'],
      cons: ['Latencia de escritura ligeramente superior en transacciones que cruzan continentes debido al consenso Raft.'],
      sacrifices: ['Sacrificas la latencia sub-milisegundo de escrituras locales de un Postgres de nodo único.'],
      idealFor: ['Sistemas de pagos y bancos globales', 'Plataformas multi-región con tolerancia cero al downtime'],
      avoidIf: ['Proyectos locales donde un PostgreSQL simple en Hetzner o Supabase es 10x más barato'],
    },
  }),
  defineTech({
    id: 'planetscale',
    name: 'PlanetScale',
    category: 'database',
    tagline: 'Base de datos MySQL serverless construida sobre Vitess con branching sin bloqueos.',
    description: 'Plataforma de datos basada en Vitess (la tecnología que escala YouTube) con cambios de esquema sin bloqueo de tablas.',
    website: 'https://planetscale.com',
    badgeText: 'Vitess Horizontal Scale',
    license: 'Proprietary',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'low', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: false, limitsDescription: 'Planes a partir de $39/mes tras la retirada de su plan gratuito histórico.' },
    tradeoffs: {
      pros: ['Migraciones de esquema en producción con cero tiempo de inactividad.', 'Escalabilidad horizontal masiva sin preocuparse por particiones.'],
      cons: ['No ofrece plan gratuito permanente.', 'No soporta claves foráneas tradicionales a nivel de motor de almacenamiento (las delega al ORM).'],
      sacrifices: ['Sacrificas el tier gratuito $0/mes para MVPs tempranos.'],
      idealFor: ['Empresas en fase de tracción con tráfico masivo', 'Sistemas MySQL a gran escala'],
      avoidIf: ['Proyectos bootstrapping de presupuesto $0 estricto'],
    },
  }),
  defineTech({
    id: 'tidb',
    name: 'TiDB Cloud',
    category: 'database',
    tagline: 'Base de datos HTAP serverless distribuida compatible con MySQL para transacciones y analítica.',
    description: 'Motor híbrido transaccional y analítico distribuido que procesa consultas transaccionales ACID y analítica en tiempo real sin ETL.',
    website: 'https://en.pingcap.com/tidb-cloud',
    badgeText: 'HTAP Hybrid SQL',
    license: 'Apache-2.0',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Serverless plan gratuito con hasta 5 GB de datos y cómputo incluido.' },
    tradeoffs: {
      pros: ['Une OLTP y OLAP en un solo motor sin duplicar datos en un data warehouse.', 'Compatible con drivers MySQL existentes.'],
      cons: ['Menor adopción comunitaria en startups occidentales frente a PostgreSQL.'],
      sacrifices: ['Sacrificas el ecosistema nativo de extensiones de PostgreSQL.'],
      idealFor: ['Plataformas que necesitan analítica en tiempo real sobre transacciones activas'],
      avoidIf: ['Aplicaciones con equipos casados estrictamente con PostgreSQL'],
    },
  }),
  defineTech({
    id: 'nhost',
    name: 'Nhost',
    category: 'database',
    tagline: 'La alternativa de código abierto a Firebase construida sobre PostgreSQL y Hasura GraphQL.',
    description: 'Backend serverless open-source que proporciona PostgreSQL, GraphQL instantáneo con Hasura, Storage S3 y autenticación.',
    website: 'https://nhost.io',
    badgeText: 'GraphQL BaaS',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 4, community: 3, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Starter plan gratuito para desarrollo y prototipado.' },
    tradeoffs: {
      pros: ['APIs GraphQL completas generadas automáticamente a partir de tablas SQL.', 'Permisos granulares con Hasura.', 'Auto-hospedable con Docker.'],
      cons: ['Curva de diseño de esquemas en GraphQL si el equipo está acostumbrado a REST.'],
      sacrifices: ['Sacrificas la simplicidad de REST en llamadas sencillas.'],
      idealFor: ['Apps basadas en GraphQL', 'Proyectos móviles con consultas de datos anidadas complejas'],
      avoidIf: ['Equipos que no deseen utilizar GraphQL'],
    },
  }),
  defineTech({
    id: 'aiven',
    name: 'Aiven Cloud Data',
    category: 'database',
    tagline: 'Servicios de datos open-source totalmente gestionados en AWS, GCP y Azure.',
    description: 'Plataforma multi-cloud que gestiona PostgreSQL, Apache Kafka, OpenSearch y Redis con backups y SLAs de nivel corporativo.',
    website: 'https://aiven.io',
    badgeText: 'Enterprise Managed Data',
    license: 'Proprietary',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'high', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Tier gratuito permanente para PostgreSQL, MySQL y Redis en la nube.' },
    tradeoffs: {
      pros: ['Portabilidad multi-nube total sin vendor lock-in en la capa de datos.', 'SLA garantizado del 99.99%.', 'Migraciones automatizadas.'],
      cons: ['Costes de planes avanzados orientados a presupuestos corporativos.'],
      sacrifices: ['Sacrificas extensiones propietarias optimizadas para serverless efímero.'],
      idealFor: ['Empresas que requieren bases de datos open source gestionadas sin atarse a un solo hyperscaler'],
      avoidIf: ['Startups que buscan features PaaS todo-en-uno con auth y storage integrado'],
    },
  }),
  defineTech({
    id: 'scylladb',
    name: 'ScyllaDB',
    category: 'database',
    tagline: 'Base de datos NoSQL distribuida ultra-rápida compatible con Cassandra en C++.',
    description: 'Reimplementación en C++ de Apache Cassandra y DynamoDB que exprime cada ciclo de hardware con latencia consistente en microsegundos.',
    website: 'https://scylladb.com',
    badgeText: 'Low Latency NoSQL',
    license: 'AGPL-3.0',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Versión open-source gratuita; ScyllaDB Cloud ofrece créditos iniciales.' },
    tradeoffs: {
      pros: ['Throughput masivo de millones de operaciones por segundo.', 'Elimina pausas de recolección de basura de la JVM de Cassandra.', 'Compatible con drivers CQL.'],
      cons: ['Requiere hardware moderno con NVMe para exprimir su arquitectura asíncrona.'],
      sacrifices: ['Sacrificas transacciones relacionales ACID con múltiples joins entre tablas.'],
      idealFor: ['IoT a gran escala', 'Series temporales de telemetría masiva', 'Detección de fraude en tiempo real'],
      avoidIf: ['Aplicaciones CRUD convencionales'],
    },
  }),
  defineTech({
    id: 'clickhouse',
    name: 'ClickHouse Cloud',
    category: 'database',
    tagline: 'El sistema gestor de bases de datos columnar más rápido del mundo para analítica.',
    description: 'Motor de base de datos columnar open-source diseñado para procesar peticiones analíticas sobre miles de millones de filas en milisegundos.',
    website: 'https://clickhouse.com',
    badgeText: 'Columnar Analytics Speed',
    license: 'Apache-2.0',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source auto-hospedable sin coste; ClickHouse Cloud ofrece prueba con créditos.' },
    tradeoffs: {
      pros: ['Compresión de datos extrema (hasta 80%).', 'Rendimiento de agregación analítica órdenes de magnitud superior a Postgres o MySQL.'],
      cons: ['No está diseñado para mutaciones puntuales frecuentes (UPDATE / DELETE individuales).'],
      sacrifices: ['Sacrificas transacciones OLTP orientadas a actualización de registros individuales.'],
      idealFor: ['Plataformas de analítica web (tipo PostHog o Plausible)', 'Logs de auditoría', 'Métricas de infraestructura'],
      avoidIf: ['Almacén transaccional primario de usuarios y carritos de compra'],
    },
  }),
  defineTech({
    id: 'duckdb',
    name: 'DuckDB',
    category: 'database',
    tagline: 'El SQLite del análisis de datos: motor OLAP vectorial integrado en memoria.',
    description: 'Sistema de base de datos analítica columnar embebido sin dependencias externas, ideal para Python, Node.js y navegadores con WebAssembly.',
    website: 'https://duckdb.org',
    badgeText: 'In-Process OLAP',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Totalmente open source; corre directamente en memoria del proceso de la app.' },
    tradeoffs: {
      pros: ['Cero infraestructura de servidor para analítica.', 'Lectura directa y ultrarrápida de archivos Parquet y CSV.', 'Corre dentro de scripts de Python o en WASM.'],
      cons: ['No está diseñado para concurrencia masiva de escrituras distribuidas.'],
      sacrifices: ['Sacrificas escalabilidad horizontal distribuida.'],
      idealFor: ['Data science en aplicaciones', 'Procesamiento de exportes analíticos bajo demanda', 'Dashboards locales'],
      avoidIf: ['Almacén central compartido por 100 servidores concurrentes simultáneos'],
    },
  }),
  defineTech({
    id: 'cassandra',
    name: 'Apache Cassandra',
    category: 'database',
    tagline: 'Disponibilidad continua sin puntos únicos de fallo para datos a escala planetaria.',
    description: 'Base de datos distribuida NoSQL diseñada para manejar grandes volúmenes de datos a través de múltiples nodos y centros de datos.',
    website: 'https://cassandra.apache.org',
    badgeText: 'Masterless Distributed',
    license: 'Apache-2.0',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Código abierto bajo Apache 2.0.' },
    tradeoffs: {
      pros: ['Arquitectura masterless: cualquier nodo puede atender lecturas y escrituras.', 'Escalabilidad lineal probada por Apple y Netflix.'],
      cons: ['Mantenimiento operativo complejo.', 'Consumo de recursos de JVM.'],
      sacrifices: ['Sacrificas simplicidad operativa de bases de datos relacionales.'],
      idealFor: ['Grandes sistemas globales con escrituras incesantes', 'Logs de actividad continua'],
      avoidIf: ['Proyectos pequeños con menos de 10 millones de registros'],
    },
  }),
  defineTech({
    id: 'dynamodb',
    name: 'Amazon DynamoDB',
    category: 'database',
    tagline: 'Base de datos NoSQL serverless de latencia predecible de un solo dígito de milisegundo.',
    description: 'Servicio de base de datos de clave-valor y documentos totalmente gestionado por AWS con escalado automático y rendimiento uniforme.',
    website: 'https://aws.amazon.com/dynamodb',
    badgeText: 'AWS Serverless NoSQL',
    license: 'Proprietary',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 5 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Free tier perpetuo de AWS con 25 GB de almacenamiento y 25 WCU/RCU.' },
    tradeoffs: {
      pros: ['Rendimiento constante independientemente del tamaño de la tabla.', 'Cero mantenimiento de servidores.', 'Integración nativa con AWS Lambda y EventBridge.'],
      cons: ['Requiere dominar Single-Table Design.', 'Vendor lock-in absoluto con el ecosistema de Amazon Web Services.'],
      sacrifices: ['Sacrificas portabilidad fuera de AWS y consultas SQL dinámicas.'],
      idealFor: ['Arquitecturas 100% serverless en AWS', 'Servicios de comercio electrónico de alta concurrencia'],
      avoidIf: ['Esquemas relacionales que requieran consultas ad-hoc cambiantes'],
    },
  }),
  defineTech({
    id: 'couchdb',
    name: 'Apache CouchDB',
    category: 'database',
    tagline: 'Base de datos NoSQL centrada en sincronización bidireccional y resiliencia offline.',
    description: 'Base de datos orientada a documentos JSON con protocolo de sincronización HTTP/REST diseñado para conectividad intermitente.',
    website: 'https://couchdb.apache.org',
    badgeText: 'Sync & Offline First',
    license: 'Apache-2.0',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 4, community: 3, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source bajo licencia Apache 2.0.' },
    tradeoffs: {
      pros: ['Protocolo de sincronización de datos líder.', 'Se integra perfectamente con PouchDB en el navegador para modo sin conexión.'],
      cons: ['Modelado de vistas MapReduce puede resultar poco intuitivo frente a SQL.'],
      sacrifices: ['Sacrificas rendimiento en queries analíticas complejas.'],
      idealFor: ['Aplicaciones móviles de campo con trabajo offline', 'Sistemas de sincronización peer-to-peer'],
      avoidIf: ['Backends con miles de actualizaciones transaccionales ACID simultáneas por segundo'],
    },
  }),
  defineTech({
    id: 'neo4j',
    name: 'Neo4j Graph Database',
    category: 'database',
    tagline: 'La base de datos de grafos nativa líder para relaciones complejas y detección de patrones.',
    description: 'Base de datos de grafos ACID con lenguaje de consulta Cypher optimizado para navegar relaciones altamente conectadas sin joins costosos.',
    website: 'https://neo4j.com',
    badgeText: 'Native Graph Engine',
    license: 'GPL-3.0',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Neo4j AuraDB ofrece tier gratuito en la nube para grafos pequeños.' },
    tradeoffs: {
      pros: ['Consultas sobre grafos y rutas entre nodos en milisegundos.', 'Lenguaje Cypher intuitivo y expresivo.', 'Modelado natural de redes.'],
      cons: ['No es óptimo para operaciones CRUD tabulares simples.'],
      sacrifices: ['Sacrificas velocidad en consultas masivas de listas planas de registros.'],
      idealFor: ['Redes sociales', 'Motores de recomendación personalizada', 'Detección de fraude y grafos de conocimiento para IA'],
      avoidIf: ['Aplicaciones transaccionales convencionales de facturas y usuarios'],
    },
  }),
  defineTech({
    id: 'surrealdb',
    name: 'SurrealDB',
    category: 'database',
    tagline: 'Base de datos multi-modelo revolucionaria en Rust: relacional, documental, grafo y vectorial.',
    description: 'Base de datos multi-paradigma con sintaxis SurrealQL, permisos de seguridad integrados y sincronización WebSocket nativa.',
    website: 'https://surrealdb.com',
    badgeText: 'Multi-Model SurrealQL',
    license: 'BSL',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 3, community: 4, maturity: 3, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Binario único en Rust desplegable en cualquier infraestructura o nube Surreal Cloud.' },
    tradeoffs: {
      pros: ['Unifica tablas relacionales, grafos, documentos y embeddings en una sola consulta.', 'Conexión directa desde clientes web segura.'],
      cons: ['Ecosistema joven en comparación con PostgreSQL.'],
      sacrifices: ['Sacrificas décadas de herramientas de optimización SQL maduras.'],
      idealFor: ['Nuevos proyectos que quieran evitar usar 4 bases de datos diferentes', 'Apps colaborativas'],
      avoidIf: ['Entornos corporativos que exijan soporte de proveedores tradicionales'],
    },
  }),
  defineTech({
    id: 'pocketbase',
    name: 'PocketBase',
    category: 'database',
    tagline: 'Backend open-source completo en un único archivo ejecutable escrito en Go.',
    description: 'Base de datos SQLite embebida con autenticación de usuarios, subida de archivos y suscripciones en tiempo real servida en un solo binario.',
    website: 'https://pocketbase.io',
    badgeText: '1-File Go Backend',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 1, scalability: 3, ecosystem: 3, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Corre en un VPS de $3.5/mes o en cualquier máquina local.' },
    tradeoffs: {
      pros: ['Despliegue trivial: un solo archivo .exe o binario Linux.', 'Panel de administración web intuitivo.', 'SDKs limpios para JS y Dart.'],
      cons: ['Monolito de nodo único sobre SQLite; no escala horizontalmente a múltiples servidores.'],
      sacrifices: ['Sacrificas escalabilidad a clusters distribuidos de alta disponibilidad.'],
      idealFor: ['MVPs rápidos', 'Apps móviles de escala modesta', 'Herramientas internas y prototipos'],
      avoidIf: ['Aplicaciones que proyecten millones de usuarios concurrentes en múltiples continentes'],
    },
  }),
];
