import type { Technology } from '../types';
import { defineTech } from './builder';

export const EMAIL_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'resend',
    name: 'Resend',
    category: 'email',
    tagline: 'API de correo electronico para desarrolladores impulsada por React Email.',
    description: 'La forma moderna de enviar correos transaccionales y de marketing utilizando componentes de React nativos, con entregabilidad excelente y una interfaz minimalista.',
    website: 'https://resend.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'React Email',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '3,000 correos al mes gratis (100 por dia) con un dominio personalizado.' },
    tradeoffs: {
      pros: ['Creacion de plantillas con componentes familiares de React Email', 'Documentacion y SDKs de TypeScript excepcionales', 'Entregabilidad de alta calidad y verificacion DNS simplificada'],
      cons: ['Menos herramientas avanzadas de automatizacion de marketing complejas que plataformas CRM tradicionales', 'Costo por correo mas alto que AWS SES puro a volumenes de millones'],
      sacrifices: ['Sacrificas el coste irrisorio por millon de SES a cambio de productividad y estetica en el diseno de correos.'],
      idealFor: ['Next.js y fullstack TypeScript apps', 'SaaS modernos', 'Correos de verificacion y bienvenida'],
      avoidIf: ['Envio masivo de boletines de millones de correos con margenes minusculos'],
    },
  }),
  defineTech({
    id: 'loops',
    name: 'Loops',
    category: 'email',
    tagline: 'Plataforma de correo electronico disenada especificamente para startups y SaaS modernos.',
    description: 'Herramienta de envio que combina correos transaccionales directos desde API con automatizaciones de marketing y campanas de onboarding visuales.',
    website: 'https://loops.so/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Built for SaaS',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Plan gratuito de hasta 1,000 contactos y 2,000 correos al mes.' },
    tradeoffs: {
      pros: ['Editor visual moderno con experiencia similar a Notion', 'Facilidad para orquestar secuencias de onboarding de nuevos usuarios', 'Integracion directa con eventos de producto'],
      cons: ['Enfocado principalmente en SaaS (menos adecuado para e-commerce clasico)', 'Ecosistema de conectores aun en expansion comparado con Mailchimp'],
      sacrifices: ['Sacrificas modulos gigantes de CRM a favor de flujos directos de producto.'],
      idealFor: ['Startups B2B y SaaS', 'Secuencias de activacion de usuarios', 'Boletines de producto'],
      avoidIf: ['Comercio electronico con catalogos masivos de productos variables'],
    },
  }),
  defineTech({
    id: 'brevo',
    name: 'Brevo (Sendinblue)',
    category: 'email',
    tagline: 'Plataforma integral multicanal de correo transaccional, marketing y CRM.',
    description: 'Solucion europea todo-en-uno que factura por numero de correos enviados en lugar de por tamano de la lista de contactos, con soporte para SMS y WhatsApp.',
    website: 'https://www.brevo.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'European All-in-One',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '300 correos al dia con contactos ilimitados en el plan gratuito permanente.' },
    tradeoffs: {
      pros: ['No penaliza por tener bases de datos grandes de contactos inactivos', 'Soporte multicanal (Email, WhatsApp, SMS, Chat web)', 'Centros de datos en Europa con estricto cumplimiento del RGPD'],
      cons: ['Limite diario en plan gratuito (no acumulable mensualmente)', 'Disenador de plantillas visuales mas tradicional que React Email'],
      sacrifices: ['Sacrificas la estetica hipermoderna orientada a desarrolladores a cambio de amplitud multicanal y costes fijos controlados.'],
      idealFor: ['Empresas europeas', 'Negocios con grandes listas de contactos pero envios esporadicos', 'Multicanal'],
      avoidIf: ['Equipos tecnicos que solo quieren escribir codigo en React para sus correos'],
    },
  }),
  defineTech({
    id: 'postmark',
    name: 'Postmark',
    category: 'email',
    tagline: 'Entregabilidad hiperrapida y aislada para correos transaccionales criticos.',
    description: 'Servicio de correo obsesionado con la velocidad de entrega en bandeja de entrada, separando fisicamente los servidores de correo transaccional de los de marketing.',
    website: 'https://postmarkapp.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Inbox Speed',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '100 correos al mes para pruebas de desarrollo gratuitas.' },
    tradeoffs: {
      pros: ['Tiempo de entrega de correos de reseteo de contrasena y 2FA en cuestion de segundos', 'Reputacion de IP impecable al aislar trafico transaccional', 'Registro historico detallado de apertura, rebote y contenido de correos'],
      cons: ['Precios superiores a proveedores masivos generalistas', 'Reglas estrictas contra cualquier tipo de spam o marketing no solicitado'],
      sacrifices: ['Sacrificas precio bajo a cambio de la mejor reputacion y velocidad de entrega del mercado.'],
      idealFor: ['Recibos de compra, restablecimiento de contrasenas, alertas de seguridad criticas'],
      avoidIf: ['Campanas de prospeccion en frio o listas masivas de newsletters'],
    },
  }),
  defineTech({
    id: 'aws-ses',
    name: 'AWS SES',
    category: 'email',
    tagline: 'Servicio de envio de correo electronico masivo ultrabarato y de alta escalabilidad.',
    description: 'Amazon Simple Email Service permite enviar millones de correos a un costo casi insignificante ($0.10 por cada 1,000 correos), integrado con la infraestructura AWS.',
    website: 'https://aws.amazon.com/ses/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Lowest Cost Email',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '62,000 correos al mes gratuitos si se envia desde instancias EC2 de AWS.' },
    tradeoffs: {
      pros: ['El costo por envio mas bajo del mercado por un margen abrumador', 'Capacidad para gestionar volumenes de cientos de millones de envios sin saturarse', 'Integracion con SNS, S3 y CloudWatch para analisis detallado'],
      cons: ['Configuracion de sandbox inicial tediosa con solicitud de aprobacion a soporte', 'Sin editor de plantillas amigable ni dashboards de marketing integrados', 'La gestion de reputacion e IPs recae completamente en el usuario'],
      sacrifices: ['Sacrificas ergonomia para el desarrollador y herramientas de diseno a cambio del costo de infra mas bajo posible.'],
      idealFor: ['Envio de millones de notificaciones automaticas', 'Boletines de escala masiva', 'Equipos con infraestructura AWS'],
      avoidIf: ['Startups en etapa temprana que quieren enviar su primer correo en 5 minutos sin configurar DNS complejos'],
    },
  }),
  defineTech({
    id: 'sendgrid',
    name: 'SendGrid (Twilio)',
    category: 'email',
    tagline: 'Infraestructura de correo cloud empresarial para transaccional y marketing.',
    description: 'Pionero en APIs de correo en la nube, capaz de procesar mas de 100 mil millones de correos al mes con herramientas analiticas y subcuentas para agencias.',
    website: 'https://sendgrid.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Enterprise Scale',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '100 correos al dia gratuitos para siempre.' },
    tradeoffs: {
      pros: ['Escalabilidad masiva y soporte corporativo de primer nivel respaldado por Twilio', 'Soporte robusto para subusuarios y control granular de permisos', 'Biblioteca en todos los lenguajes de programacion existentes'],
      cons: ['La reputacion de sus IPs compartidas ha tenido altibajos historicos', 'La interfaz de usuario puede resultar pesada y burocratica'],
      sacrifices: ['Sacrificas agilidad moderna por un proveedor clasico corporativo.'],
      idealFor: ['Grandes corporaciones', 'Plataformas SaaS que gestionan correos de multiples clientes via subcuentas'],
      avoidIf: ['Equipos pequenos que buscan disenos de correos en React modernos'],
    },
  }),
  defineTech({
    id: 'mailjet',
    name: 'Mailjet (Sinch)',
    category: 'email',
    tagline: 'Plataforma europea de correo con diseno colaborativo y cumplimiento RGPD.',
    description: 'Servicio de envio transaccional y boletines con certificacion ISO 27001, servidores en Europa y editor de plantillas en tiempo real estilo Google Docs.',
    website: 'https://www.mailjet.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'GDPR Compliant',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '6,000 correos al mes gratuitos (limite de 200 correos por dia).' },
    tradeoffs: {
      pros: ['Cumplimiento riguroso de normativas de privacidad europeas', 'Edicion visual de plantillas multiusuario en simultaneo', 'Precios accesibles por volumen'],
      cons: ['Limite diario estricto en el plan gratuito', 'SDKs menos actualizados a las ultimas versiones de TypeScript'],
      sacrifices: ['Sacrificas novedades tecnicas punteras a cambio de solidez legal en la UE.'],
      idealFor: ['Equipos mixtos de desarrolladores y redactores de marketing en Europa', 'Agencias'],
      avoidIf: ['Flujos que requieren envios instantaneos con componentes JSX'],
    },
  }),
  defineTech({
    id: 'mailtrap',
    name: 'Mailtrap',
    category: 'email',
    tagline: 'Sandbox seguro para pruebas de correo en desarrollo y envio a produccion.',
    description: 'Entorno de pruebas que intercepta correos en entornos de staging sin enviarlos a usuarios reales, con analisis de spam, vista previa de renderizado y envio a produccion.',
    website: 'https://mailtrap.io/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Testing Sandbox',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100 correos de prueba en sandbox y 1,000 correos de produccion gratis al mes.' },
    tradeoffs: {
      pros: ['Elimina el riesgo catastrofico de enviar correos de prueba de desarrollo a clientes reales', 'Verificacion automatica de puntuacion de spam y soporte HTML en diferentes clientes de correo', 'Paso transparente de sandbox a envio de produccion real'],
      cons: ['Plan gratuito limitado para equipos con multiples entornos de CI', 'Menor variedad de automatizaciones de campanas complejas'],
      sacrifices: ['Sacrificas campanas visuales avanzadas por excelencia en entornos de QA y pruebas.'],
      idealFor: ['Cualquier equipo de desarrollo durante las fases de creacion y testing', 'Pipelines de integracion continua (CI/CD)'],
      avoidIf: ['Equipos que unicamente buscan campanas visuales de marketing masivo'],
    },
  }),
  defineTech({
    id: 'plunk',
    name: 'Plunk',
    category: 'email',
    tagline: 'Plataforma de correo transaccional open source impulsada por AWS SES.',
    description: 'Alternativa de codigo abierto a los servicios comerciales de email marketing, que anade una capa moderna de automatizaciones y APIs sobre tu propia cuenta de AWS SES.',
    website: 'https://www.useplunk.com/',
    license: 'MIT',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Open Source Email',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Plan cloud gratuito hasta 3,000 correos o auto-alojable de forma ilimitada.' },
    tradeoffs: {
      pros: ['Codigo abierto con opcion de auto-alojar en servidores propios', 'Aprovecha las tarifas microscopicas de AWS SES con una interfaz atractiva', 'API transparente y ligera'],
      cons: ['Proyecto mas reciente con una comunidad en fase de expansion', 'Requiere configurar y mantener la cuenta de AWS SES'],
      sacrifices: ['Sacrificas soporte corporativo 24/7 por codigo abierto e independencia.'],
      idealFor: ['Desarrolladores apasionados por el open source', 'Startups que quieren combinar precios de SES con buena DX'],
      avoidIf: ['Organizaciones que demandan SLAs contractuales estrictos'],
    },
  }),
  defineTech({
    id: 'courier',
    name: 'Courier',
    category: 'email',
    tagline: 'Infraestructura de notificaciones unificada para Email, SMS, Push, Slack y WhatsApp.',
    description: 'API unica para disenar y enviar notificaciones a traves de cualquier canal, con enrutamiento inteligente de mensajes, preferencias de usuario y bandejas de entrada in-app.',
    website: 'https://www.courier.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Multi-Channel Inbox',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '10,000 notificaciones gratis al mes en todos los canales soportados.' },
    tradeoffs: {
      pros: ['Una sola llamada API despacha a traves de Email, SMS, Push, Slack o Discord segun la preferencia del receptor', 'Componente de campanita de notificaciones in-app listo para usar', 'Elimina la necesidad de integrar multiples SDKs dispares'],
      cons: ['Costo por mensaje mas alto al anadir su capa de orquestacion', 'Depende de tus propias cuentas en los proveedores subyacentes'],
      sacrifices: ['Sacrificas llamadas directas simples a cambio de una capa potente de gobernanza de notificaciones.'],
      idealFor: ['Plataformas SaaS colaborativas', 'Apps que envian alertas por multiples canales simultaneos'],
      avoidIf: ['Proyectos simples que unicamente envian un correo de confirmacion'],
    },
  }),
  defineTech({
    id: 'customerio',
    name: 'Customer.io',
    category: 'email',
    tagline: 'Plataforma de automatizacion de mensajes basada en el comportamiento real del usuario.',
    description: 'Motor de campanas impulsado por datos que permite crear secuencias complejas multicanal disparadas por las acciones concretas que los usuarios realizan en la aplicacion.',
    website: 'https://customer.io/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Behavioral Messaging',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 4 },
    cost: { initialCost: 'medium', operationalCost: 'high', scalingRisk: 'medium', hasFreeTier: false, limitsDescription: 'Prueba gratuita de 14 dias; planes orientados a empresas en crecimiento.' },
    tradeoffs: {
      pros: ['Segmentacion por comportamiento de producto extremadamente sofisticada', 'Editor de flujos de trabajo visual de maxima potencia', 'Excelente soporte de envio de datos en tiempo real via webhooks y SDKs'],
      cons: ['Sin plan gratuito permanente; precios altos para startups en etapa muy temprana', 'Requiere una instrumentacion de eventos de producto rigurosa'],
      sacrifices: ['Sacrificas bajo coste a cambio del motor de automatizacion de retencion mas potente.'],
      idealFor: ['Scaleups SaaS con estrategia Product-Led Growth (PLG)', 'Equipos dedicados de Growth y Retention'],
      avoidIf: ['Proyectos que apenas estan validando el problema o sin presupuesto mensual'],
    },
  }),
  defineTech({
    id: 'onesignal',
    name: 'OneSignal',
    category: 'email',
    tagline: 'Lider mundial en notificaciones push web y moviles, email y mensajes in-app.',
    description: 'Plataforma que entrega mas de 12 mil millones de notificaciones al dia, permitiendo sincronizar campanas de notificaciones push moviles, web push y correos electronicos.',
    website: 'https://onesignal.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Push & Email Leader',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Dispositivos web push ilimitados y hasta 10,000 suscriptores de email en el plan gratis.' },
    tradeoffs: {
      pros: ['Estandar indiscutible para notificaciones push en navegadores y apps nativas', 'Plan gratuito muy generoso para arrancar proyectos', 'Integracion rapida con SDKs para React Native, Flutter, iOS y Android'],
      cons: ['La capacidad de email es secundaria frente a su potencia en notificaciones push', 'Precios de suscripcion crecen con rapidez al escalar millones de usuarios'],
      sacrifices: ['Sacrificas sofisticacion en plantillas de correo a favor de una suite push integral.'],
      idealFor: ['Aplicaciones moviles', 'Medios y periodicos digitales', 'Web apps que dependen de retencion por push'],
      avoidIf: ['Backends que unicamente requieren correos transaccionales B2B'],
    },
  }),
];
