import type { Technology } from '../types';
import { defineTech } from './builder';

export const FRONTEND_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'nextjs',
    name: 'Next.js',
    category: 'frontend',
    tagline: 'El estándar de la industria para React full-stack con SSR y Server Components.',
    description: 'Framework React full-stack con App Router, SSR/SSG híbrido, Server Actions y optimizaciones automáticas.',
    website: 'https://nextjs.org',
    badgeText: 'Industry Standard',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Despliegue gratuito en Vercel Hobby con invocaciones generosas.' },
    tradeoffs: {
      pros: ['Ecosistema inmenso con librerías listas.', 'Híbrido SSR/SSG real.', 'Server Actions integradas.'],
      cons: ['Curva de App Router.', 'Acoplamiento preferente con Vercel.', 'Bundle considerable en proyectos grandes.'],
      sacrifices: ['Sacrificas portabilidad trivial fuera de Node/Docker.', 'Sacrificas simplicidad mental frente a una SPA estática pura.'],
      idealFor: ['SaaS B2B/B2C', 'E-commerce interactivo', 'Plataformas web con SEO crítico'],
      avoidIf: ['Sitios puramente estáticos donde Astro es 10x más ligero'],
    },
  }),
  defineTech({
    id: 'react-vite',
    name: 'React + Vite',
    category: 'frontend',
    tagline: 'SPA ultra-rápida y desacoplada con cero magia en servidor.',
    description: 'Single Page Application pura construida con Vite, TypeScript y React. Compila a assets estáticos.',
    website: 'https://vite.dev',
    badgeText: 'Decoupled SPA',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Hosting 100% gratuito en cualquier CDN estático (Cloudflare Pages, Vercel).' },
    tradeoffs: {
      pros: ['HMR sub-segundo instantáneo.', 'Desacoplamiento total del backend.', 'Cero complejidad operativa.'],
      cons: ['SEO público limitado sin prerender.', 'Descarga de bundle JS inicial obligatoria.'],
      sacrifices: ['Sacrificas SEO dinámico listo para indexar.', 'Sacrificas SSR nativo.'],
      idealFor: ['Dashboards y paneles internos', 'SaaS autenticado', 'Apps colaborativas'],
      avoidIf: ['Blogs públicos o landing pages con SEO como canal principal'],
    },
  }),
  defineTech({
    id: 'astro',
    name: 'Astro',
    category: 'frontend',
    tagline: 'Zero-JS por defecto con arquitectura de islas para máxima velocidad.',
    description: 'Framework orientado a contenido y sitios web rápidos con Islands Architecture y soporte multi-framework.',
    website: 'https://astro.build',
    badgeText: 'Content & Islands',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Hospedaje gratuito en Cloudflare Pages, Netlify o Vercel.' },
    tradeoffs: {
      pros: ['Zero JavaScript enviado por defecto.', 'Arquitectura de islas aisladas.', 'Puntajes 100 en Core Web Vitals.'],
      cons: ['Menos intuitivo para aplicaciones altamente mutables.', 'Manejo de estado global entre islas requiere tiendas externas.'],
      sacrifices: ['Sacrificas ecosistema de SPA monolítica con estado reactivo universal.'],
      idealFor: ['Blogs, sitios de contenido, documentación', 'E-commerce estático', 'Landing pages'],
      avoidIf: ['Aplicaciones de dashboard altamente reactivas tipo Linear o Figma'],
    },
  }),
  defineTech({
    id: 'sveltekit',
    name: 'SvelteKit',
    category: 'frontend',
    tagline: 'Reactividad sin Virtual DOM compilada a JavaScript vanilla ultraligero.',
    description: 'Framework full-stack impulsado por Svelte con compilación ahead-of-time y ergonomía sintáctica superior.',
    website: 'https://svelte.dev',
    badgeText: 'Zero Virtual DOM',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 3, community: 3, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Exportable a Node.js, Cloudflare Workers o Vercel sin coste de licencia.' },
    tradeoffs: {
      pros: ['Código hasta 40% más conciso que React.', 'Reactividad basada en runas sin Virtual DOM.', 'Bundle diminuto.'],
      cons: ['Ecosistema de librerías de componentes más reducido.', 'Menor volumen de talento en el mercado laboral.'],
      sacrifices: ['Sacrificas la inmensidad del ecosistema npm de librerías React.'],
      idealFor: ['SaaS de rendimiento crítico', 'PWA ligeras', 'Equipos pequeños ágiles'],
      avoidIf: ['Proyectos enterprise que requieran cientos de componentes UI prehechos en React'],
    },
  }),
  defineTech({
    id: 'nuxt',
    name: 'Nuxt 3',
    category: 'frontend',
    tagline: 'El framework fullstack intuitivo para el ecosistema Vue 3.',
    description: 'Framework híbrido SSR/SSG con auto-imports, renderizado universal Nitro y sistema de módulos completo.',
    website: 'https://nuxt.com',
    badgeText: 'Vue Fullstack',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Desplegable en Vercel, Cloudflare o Node.js sin coste inicial.' },
    tradeoffs: {
      pros: ['Auto-importación de componentes y composables.', 'Motor Nitro ultraportátil.', 'Excelente DX.'],
      cons: ['Ecosistema Vue menor que React en Occidente.'],
      sacrifices: ['Sacrificas compatibilidad con librerías exclusivas de React.'],
      idealFor: ['SaaS con Vue 3', 'Portales de contenido con SEO', 'E-commerce'],
      avoidIf: ['Equipos con especialización estricta en React/JSX'],
    },
  }),
  defineTech({
    id: 'vue-vite',
    name: 'Vue 3 + Vite',
    category: 'frontend',
    tagline: 'SPA reactiva progresiva con Composition API y velocidad instantánea.',
    description: 'Single Page Application desacoplada con Vue 3, Composition API y Vite para máxima ligereza y ergonomía.',
    website: 'https://vuejs.org',
    badgeText: 'Progressive SPA',
    license: 'MIT',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Hospedaje estático gratuito en Cloudflare Pages o Netlify.' },
    tradeoffs: {
      pros: ['Curva de aprendizaje muy suave.', 'Sintaxis Single File Component limpia.', 'Rendimiento excelente.'],
      cons: ['No incluye SSR out-of-the-box sin Nuxt.'],
      sacrifices: ['Sacrificas SEO público dinámico listo para indexar.'],
      idealFor: ['Paneles de administración', 'Aplicaciones B2B internas', 'MVPs rápidos'],
      avoidIf: ['Portales orientados a SEO masivo'],
    },
  }),
  defineTech({
    id: 'remix',
    name: 'Remix',
    category: 'frontend',
    tagline: 'Renderizado web centrado en estándares web HTTP y formularios nativos.',
    description: 'Framework React con arquitectura basada en estándares web, loaders, actions y nested routes eficientes.',
    website: 'https://remix.run',
    badgeText: 'Web Standards',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Adaptable a cualquier host Node.js o Edge.' },
    tradeoffs: {
      pros: ['Manejo de mutaciones y formularios web nativo.', 'Excelente resiliencia a redes lentas.', 'Portabilidad real.'],
      cons: ['Ecosistema de templates menor que Next.js.'],
      sacrifices: ['Sacrificas Server Components propietarios de React 19.'],
      idealFor: ['Aplicaciones transaccionales densas', 'SaaS con formularios complejos'],
      avoidIf: ['Sitios web puramente estáticos'],
    },
  }),
  defineTech({
    id: 'solidstart',
    name: 'SolidStart',
    category: 'frontend',
    tagline: 'Rendimiento reactivo granular extremo con sintaxis JSX sin Virtual DOM.',
    description: 'Framework full-stack sobre SolidJS con reactividad a nivel de átomo sin diffing ni recreación de árboles.',
    website: 'https://start.solidjs.com',
    badgeText: 'Fine-grained Reactive',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Genera bundles mínimos y corre en cualquier host.' },
    tradeoffs: {
      pros: ['Throughput y velocidad récord en benchmarks de navegador.', 'Zero Virtual DOM overhead.', 'Sintaxis JSX familiar.'],
      cons: ['Ecosistema joven con menos librerías de UI preparadas.'],
      sacrifices: ['Sacrificas la inercia del mercado masivo de React.'],
      idealFor: ['Dashboards en tiempo real con miles de actualizaciones por segundo', 'Apps de streaming'],
      avoidIf: ['Proyectos que dependan de paquetes React existentes'],
    },
  }),
  defineTech({
    id: 'angular',
    name: 'Angular',
    category: 'frontend',
    tagline: 'Plataforma enterprise completa con Signals, inyección de dependencias y CLI robusto.',
    description: 'Framework empresarial completo de Google con tipado estricto, Angular Signals, routing avanzado y SSR integrado.',
    website: 'https://angular.dev',
    badgeText: 'Enterprise Platform',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source sin costes de licencia.' },
    tradeoffs: {
      pros: ['Estructura estandarizada en equipos grandes.', 'Herramientas y pruebas integradas de fábrica.', 'Soporte LTS corporativo.'],
      cons: ['Curva de aprendizaje empinada con RxJS y TypeScript avanzado.'],
      sacrifices: ['Sacrificas agilidad de prototipado rápido en solitario.'],
      idealFor: ['Grandes corporaciones', 'Sistemas bancarios y ERPs', 'Equipos de 10+ devs'],
      avoidIf: ['MVPs tempranos de 1 developer'],
    },
  }),
  defineTech({
    id: 'qwik',
    name: 'Qwik City',
    category: 'frontend',
    tagline: 'Reanudabilidad instantánea (Resumability) con carga progresiva de 0 kB JS inicial.',
    description: 'Framework web revolucionario que serializa el estado en HTML y descarga solo el código de los eventos ejecutados.',
    website: 'https://qwik.dev',
    badgeText: 'Resumable Architecture',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Desplegable en edge CDNs con costes insignificantes.' },
    tradeoffs: {
      pros: ['Cero tiempo de hidratación.', 'Core Web Vitals perfectos garantizados.', 'Carga bajo demanda absoluta.'],
      cons: ['Paradigma de serialización requiere adaptación mental.'],
      sacrifices: ['Sacrificas plugins de tooling maduros existentes.'],
      idealFor: ['E-commerce a gran escala', 'Medios de noticias masivos con millones de visitas'],
      avoidIf: ['Paneles internos donde el arranque inicial no importa'],
    },
  }),
  defineTech({
    id: 'deno-fresh',
    name: 'Deno Fresh',
    category: 'frontend',
    tagline: 'Framework moderno en el Edge sin paso de compilación para Deno runtime.',
    description: 'Framework full-stack de última generación con renderizado Just-In-Time e islas de interactividad.',
    website: 'https://fresh.deno.dev',
    badgeText: 'Zero-Build Edge',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Deno Deploy ofrece tier gratuito generoso a nivel global.' },
    tradeoffs: {
      pros: ['Zero paso de compilación en desarrollo local.', 'Arranque sub-10ms en el edge.', 'Seguridad estricta de permisos.'],
      cons: ['Dependencia del runtime Deno.'],
      sacrifices: ['Sacrificas compatibilidad con herramientas legacy de Node.js.'],
      idealFor: ['Micro-frontends en el edge', 'Herramientas para desarrolladores', 'APIs ligeras con frontend'],
      avoidIf: ['Proyectos que requieran dependencias nativas de npm con binarios C++'],
    },
  }),
  defineTech({
    id: 'htmx-alpine',
    name: 'HTMX + Alpine.js',
    category: 'frontend',
    tagline: 'Simplicidad radical hipermedia impulsada por HTML sin SPAs complejas.',
    description: 'Arquitectura hipermedia moderna que traslada el estado al servidor y utiliza atributos HTML para interactividad.',
    website: 'https://htmx.org',
    badgeText: 'Hypermedia Modern',
    license: 'BSD-2-Clause',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Cero costes de frontend; se sirve desde cualquier backend.' },
    tradeoffs: {
      pros: ['Elimina capas de serialización JSON innecesarias.', 'Curva de aprendizaje casi nula.', 'Código ligero.'],
      cons: ['Menos adecuado para interfaces tipo canvas con lógica cliente densa.'],
      sacrifices: ['Sacrificas el ecosistema de componentes de interfaz cliente en React/Vue.'],
      idealFor: ['Aplicaciones CRUD orientadas a servidor (Django, Rails, Go, Laravel)', 'SaaS B2B'],
      avoidIf: ['Aplicaciones offline-first o editores gráficos interactivos en el navegador'],
    },
  }),
  defineTech({
    id: 'lit',
    name: 'Lit Web Components',
    category: 'frontend',
    tagline: 'Componentes web estándar ligeros con reactividad nativa del navegador.',
    description: 'Librería de Google para crear Web Components reutilizables conformes a estándares web sin atarse a frameworks.',
    website: 'https://lit.dev',
    badgeText: 'Web Components Native',
    license: 'BSD-3-Clause',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Código abierto y sin costes de runtime.' },
    tradeoffs: {
      pros: ['Interoperable con cualquier framework (React, Vue, Angular o vanilla).', 'Peso ínfimo (~5 kB).'],
      cons: ['SSR requiere adaptadores específicos.'],
      sacrifices: ['Sacrificas la ergonomía de un meta-framework todo en uno.'],
      idealFor: ['Design systems compartidos entre múltiples tecnologías', 'Micro-frontends'],
      avoidIf: ['Aplicaciones completas donde se busque enrutamiento y SSR de fábrica'],
    },
  }),
  defineTech({
    id: 'preact',
    name: 'Preact',
    category: 'frontend',
    tagline: 'Alternativa rápida de 3 kB a React con la misma API moderna.',
    description: 'Librería ligera compatible con React que ofrece renderizado virtual DOM eficiente con huella de descarga mínima.',
    website: 'https://preactjs.com',
    badgeText: 'Ultra-light 3kB',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Totalmente gratuito y open source.' },
    tradeoffs: {
      pros: ['Tamaño insignificante (3 kB gzip).', 'Compatible con librerías React mediante preact/compat.'],
      cons: ['Pequeñas diferencias en casos borde de React 19.'],
      sacrifices: ['Sacrificas novedades experimentales de React antes de que sean estandarizadas.'],
      idealFor: ['Widgets embedibles', 'Sitios móviles con restricciones de ancho de banda'],
      avoidIf: ['Aplicaciones que dependan fuertemente de React Server Components nativos'],
    },
  }),
  defineTech({
    id: 'ember',
    name: 'Ember.js',
    category: 'frontend',
    tagline: 'Framework con convenciones estrictas y estabilidad sin sorpresas para equipos senior.',
    description: 'Framework maduro de frontend con arquitectura basada en convenciones, enrutador probado y data-layer integrado.',
    website: 'https://emberjs.com',
    badgeText: 'Convention First',
    license: 'MIT',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 4, community: 3, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Open source bajo licencia MIT.' },
    tradeoffs: {
      pros: ['Convenciones estrictas que previenen disputas de arquitectura.', 'Actualizaciones de versión sin breaking changes.'],
      cons: ['Menor adopción en startups en comparación con Next.js.'],
      sacrifices: ['Sacrificas la flexibilidad desestructurada de ecosistemas minimalistas.'],
      idealFor: ['Aplicaciones corporativas con ciclos de vida de 5-10 años'],
      avoidIf: ['Prototipos rápidos que requieran paquetes modernos de moda'],
    },
  }),
];
