import type { Technology } from '../types';
import { defineTech } from './builder';

export const HOSTING_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'vercel',
    name: 'Vercel',
    category: 'hosting',
    tagline: 'Plataforma Frontend Cloud optimizada para frameworks React, Next.js y Edge Computing.',
    description: 'Despliegues instantaneos por Git, previsualizaciones por Pull Request, CDN global AnyCast y ejecucion serverless / edge automatizada con soporte de primer nivel para Next.js.',
    website: 'https://vercel.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Next.js Native',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'high', hasFreeTier: true, limitsDescription: 'Plan Hobby gratuito para proyectos personales con limites generosos de ancho de banda.' },
    tradeoffs: {
      pros: ['Experiencia de desarrollador (DX) inigualable', 'Optimizacion de imagenes y funciones edge integradas', 'Previsualizaciones instantaneas por cada commit'],
      cons: ['Costes de escalado en planes Pro y Enterprise elevados', 'Restricciones de tiempo de ejecucion en serverless functions'],
      sacrifices: ['Sacrificas previsibilidad de costes en hipercrecimiento frente a VPS fijos.'],
      idealFor: ['Next.js apps', 'Startups en fase MVP', 'Landing pages y aplicaciones web de alto trafico visual'],
      avoidIf: ['Servicios backend con conexiones WebSocket persistentes o procesos de larga duracion'],
    },
  }),
  defineTech({
    id: 'cloudflare-pages',
    name: 'Cloudflare Pages',
    category: 'hosting',
    tagline: 'Hosting estatico y fullstack hiperrapido en la red Edge de Cloudflare.',
    description: 'Plataforma Jamstack y fullstack impulsada por Cloudflare Workers, con despliegues automaticos por Git, ancho de banda ilimitado y proteccion DDoS de nivel mundial.',
    website: 'https://pages.cloudflare.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Edge Global',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Builds ilimitados y ancho de banda gratuito sin costes ocultos de egress.' },
    tradeoffs: {
      pros: ['Trafico y ancho de banda completamente ilimitados en plan gratuito', 'Ejecucion ultrarrapida en mas de 300 ciudades globales', 'Excelente suite de seguridad y proteccion anti-bot'],
      cons: ['Entorno de ejecucion basado en V8 Workers (no soporte completo para APIs de Node nativas)', 'Configuracion de builds mas estricta en monorrepos complejos'],
      sacrifices: ['Sacrificas soporte para librerias de Node con dependencias nativas en C++.'],
      idealFor: ['Sitios Astro, Svelte, Remix y Next estatico', 'SaaS conscientes de costos de trafico', 'APIs ligeras en el Edge'],
      avoidIf: ['Monolitos basados en Node.js que requieren el runtime completo del sistema operativo'],
    },
  }),
  defineTech({
    id: 'render',
    name: 'Render',
    category: 'hosting',
    tagline: 'Nube unificada para crear y ejecutar aplicaciones web, workers y bases de datos.',
    description: 'Alternativa moderna y elegante a Heroku con soporte para Docker, servicios web continuos, cron jobs, background workers y bases de datos Postgres gestionadas con SSL automatico.',
    website: 'https://render.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Modern Cloud',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Servicios web gratuitos con reposo tras inactividad y Postgres gratis temporal.' },
    tradeoffs: {
      pros: ['Configuracion declarativa mediante archivo render.yaml', 'Soporte nativo para contenedores Docker personalizados', 'Gestion transparente de certificados SSL y dominios'],
      cons: ['Instancias gratuitas sufren de ' + 'cold starts' + ' significativos', 'Menos regiones geograficas disponibles que AWS o GCP'],
      sacrifices: ['Sacrificas despliegues multirregion complejos a cambio de simplicidad de operacion.'],
      idealFor: ['APIs en FastAPI, Express, Django o NestJS', 'Background workers y colas en Redis', 'Startups'],
      avoidIf: ['Workloads que requieren clusters Kubernetes multi-nodo avanzados'],
    },
  }),
  defineTech({
    id: 'flyio',
    name: 'Fly.io',
    category: 'hosting',
    tagline: 'Despliega contenedores Docker cerca de tus usuarios en microVMs globales.',
    description: 'Convierte contenedores Docker en microVMs ligeras basadas en Firecracker que arrancan en milisegundos en centros de datos distribuidos por todo el mundo, con red privada WireGuard integrada.',
    website: 'https://fly.io/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Global MicroVMs',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Credito inicial gratuito para micro-instancias en varias regiones.' },
    tradeoffs: {
      pros: ['Baja latencia al desplegar codigo cerca de los usuarios en cualquier continente', 'Soporta cualquier stack empaquetado en Docker sin restricciones de runtime', 'Red interna WireGuard cifrada nativa'],
      cons: ['CLI obligatoria para operaciones avanzadas con curva de aprendizaje', 'Gestion manual de volumenes persistentes si no se usa arquitectura stateless'],
      sacrifices: ['Sacrificas interfaces visuales amigables por una experiencia centrada en terminal y CLI.'],
      idealFor: ['Aplicaciones Phoenix / Elixir con WebSockets en tiempo real', 'APIs en Go o Rust', 'Bases de datos distribuidas'],
      avoidIf: ['Equipos sin experiencia en Docker y gestion de contenedores'],
    },
  }),
  defineTech({
    id: 'railway',
    name: 'Railway',
    category: 'hosting',
    tagline: 'Plataforma de infraestructura instantanea para desplegar codigo y bases de datos.',
    description: 'Entorno de despliegue ultrarrapido que detecta automaticamente el lenguaje de programacion, conecta bases de datos con un clic y escala mediante cobro por uso real de CPU y memoria.',
    website: 'https://railway.app/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Instant Deploy',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Credito mensual de $5 USD en plan gratuito sin necesidad de tarjeta.' },
    tradeoffs: {
      pros: ['Experiencia de usuario y canvas interactivo de infraestructura de maximo nivel', 'Facturacion granular por recursos consumidos por segundo', 'Aprovisionamiento de Redis, Postgres y MySQL en 5 segundos'],
      cons: ['El modelo de precios por consumo puede resultar variable con cargas inesperadas', 'Menos controles de red avanzados para configuraciones enterprise complejas'],
      sacrifices: ['Sacrificas previsiones de facturacion fijas por flexibilidad por consumo.'],
      idealFor: ['Proyectos personales y MVPs rapidos', 'Hackathons y prototipos', 'Microservicios interconectados'],
      avoidIf: ['Grandes monolitos con alto consumo constante de memoria RAM que resultan mas economicos en un VPS dedicado'],
    },
  }),
  defineTech({
    id: 'hetzner-vps',
    name: 'Hetzner Cloud',
    category: 'hosting',
    tagline: 'Servidores cloud y VPS de alto rendimiento con la mejor relacion calidad-precio de Europa.',
    description: 'Proveedor aleman lider en infraestructura con procesadores AMD EPYC y ARM Ampere a costes ultra reducidos, discos NVMe de alta velocidad y trafico de 20 TB incluido por servidor.',
    website: 'https://www.hetzner.com/cloud',
    license: 'Proprietary',
    isManaged: false,
    isOpenSource: false,
    badgeText: 'Unbeatable Value',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 3, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'low', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: false, limitsDescription: 'Instancias desde 4 euros al mes con 2 vCPU, 4GB RAM y 20 TB de trafico.' },
    tradeoffs: {
      pros: ['Relacion potencia-precio inigualable en el mercado cloud mundial', 'Trafico mensual inmenso (20 TB) sin sorpresas en la factura', 'Centros de datos en Europa y Estados Unidos con estricto RGPD'],
      cons: ['Gestion de infraestructura 100% manual (requiere configurar Linux, firewall y Docker)', 'Sin soporte gestionado de plataforma PaaS por defecto (a menos que se use Coolify)'],
      sacrifices: ['Sacrificas automatizacion de despliegues y PaaS a cambio de un ahorro economico de hasta el 80%.'],
      idealFor: ['Equipos con conocimientos de Sysadmin / DevOps', 'Empresas conscientes de costes', 'Clusters Kubernetes autogestionados'],
      avoidIf: ['Equipos solo de frontend que no quieren tocar configuraciones de Linux o SSH'],
    },
  }),
  defineTech({
    id: 'netlify',
    name: 'Netlify',
    category: 'hosting',
    tagline: 'Plataforma para desarrollo web moderno, arquitectura composable y edge functions.',
    description: 'Pioneros del concepto Jamstack, ofrece despliegues continuos desde Git, formularios sin backend, identity gestionada y edge functions distribuidas.',
    website: 'https://www.netlify.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Composable Web',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '100 GB de ancho de banda y 300 minutos de build al mes gratis.' },
    tradeoffs: {
      pros: ['Gran suite de herramientas para sitios web estaticos y arquitectura composable', 'Formularios y gestion de autenticacion integrados sin servidor', 'Previsualizaciones colaborativas con comentarios en pantalla'],
      cons: ['Tarifas de anadidos y miembros de equipo costosas', 'Rendimiento en serverless SSR algo inferior al soporte nativo de Next.js en Vercel'],
      sacrifices: ['Sacrificas optimizacion interna para frameworks propietarios frente a estandares estaticos.'],
      idealFor: ['Sitios web corporativos Jamstack', 'Documentaciones en Hugo, Docusaurus o Astro', 'E-commerce composable'],
      avoidIf: ['Backends complejos orientados a sockets o computacion intensiva'],
    },
  }),
  defineTech({
    id: 'koyeb',
    name: 'Koyeb',
    category: 'hosting',
    tagline: 'Plataforma serverless para desplegar contenedores y workers a escala global.',
    description: 'PaaS serverless moderna para contenedores con autoscaling de cero a infinito, balanceo de carga en Anycast y despliegues sin interrupciones.',
    website: 'https://www.koyeb.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Global Serverless',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Un servicio gratuito con micro-instancia continua y 5.5 GB de RAM compartida.' },
    tradeoffs: {
      pros: ['Redireccion Anycast global integrada de serie', 'Autoscaling veloz basado en trafico entrante', 'Soporte directo para imagenes de Docker y repositorios Git'],
      cons: ['Comunidad y catalogo de complementos menor que AWS o Render', 'Menos trayectoria en grandes infraestructuras corporativas'],
      sacrifices: ['Sacrificas la madurez del ecosistema a cambio de sencillez extrema y rendimiento Anycast.'],
      idealFor: ['APIs REST y GraphQL en contenedores', 'Microservicios con requerimientos de baja latencia global'],
      avoidIf: ['Sistemas monoliticos gigantes con bases de datos relacionales locales'],
    },
  }),
  defineTech({
    id: 'northflank',
    name: 'Northflank',
    category: 'hosting',
    tagline: 'Plataforma para desarrolladores para ejecutar microservicios y bases de datos sobre Kubernetes.',
    description: 'Combina la facilidad de uso de Heroku con el poder de Kubernetes, permitiendo desplegar en su nube o conectar tu propio cluster en AWS, GCP o Azure.',
    website: 'https://northflank.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Kubernetes PaaS',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 3, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Plan para desarrolladores gratuito con 2 servicios y 1 base de datos.' },
    tradeoffs: {
      pros: ['Poder de Kubernetes sin necesidad de escribir cientos de lineas de YAML', 'Capacidad de llevar tu propio cluster (BYOC - Bring Your Own Cloud)', 'Soporte integral para pipelines CI/CD y despliegues de ramas efimeras'],
      cons: ['Interfaz rica pero con curva de comprension para no iniciados en DevOps', 'Precios para equipos superiores a opciones basicas de VPS'],
      sacrifices: ['Sacrificas sencillez basica a cambio de capacidades de orquestacion enterprise.'],
      idealFor: ['Startups en fase de escalado', 'Equipos que planean migrar a Kubernetes pero quieren una interfaz amigable'],
      avoidIf: ['Sitios web estaticos o proyectos individuales muy pequenos'],
    },
  }),
  defineTech({
    id: 'aws-ecs',
    name: 'AWS ECS / Fargate',
    category: 'hosting',
    tagline: 'Orquestacion de contenedores gestionada de alta escalabilidad en AWS.',
    description: 'Amazon Elastic Container Service permite ejecutar aplicaciones en contenedores a escala sin administrar servidores utilizando AWS Fargate serverless compute.',
    website: 'https://aws.amazon.com/ecs/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'AWS Containers',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'ECS es gratuito, solo pagas por los recursos de computo EC2 o Fargate consumidos.' },
    tradeoffs: {
      pros: ['Integracion nativa con toda la red privada VPC, IAM y CloudWatch de AWS', 'Fargate elimina la necesidad de parches y gestion de maquinas virtuales', 'Soporta cargas de trabajo masivas con certificaciones de seguridad'],
      cons: ['Curva de aprendizaje empinada con definiciones de tareas y servicios de red', 'Configuracion inicial compleja comparada con un PaaS moderno'],
      sacrifices: ['Sacrificas rapidez de configuracion inicial a cambio de control enterprise total.'],
      idealFor: ['Empresas con infraestructura ya establecida en AWS', 'Microservicios con altas exigencias de seguridad'],
      avoidIf: ['Equipos pequenos sin experiencia en AWS o proyectos de prototipado veloz'],
    },
  }),
  defineTech({
    id: 'gcp-cloudrun',
    name: 'Google Cloud Run',
    category: 'hosting',
    tagline: 'Contenedores serverless totalmente gestionados que escalan de cero a miles.',
    description: 'Ejecuta contenedores en la infraestructura de Google Cloud con facturacion exacta por milisegundo de peticion, escalado a cero cuando no hay trafico y soporte HTTPS automatico.',
    website: 'https://cloud.google.com/run',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Scale-to-Zero',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '2 millones de solicitudes gratuitas al mes y 360,000 GB-segundos de memoria.' },
    tradeoffs: {
      pros: ['Escalado automatico a cero que minimiza el gasto en aplicaciones con trafico variable', 'Soporta cualquier imagen Docker sin restricciones de lenguaje', 'Excelente velocidad de cold-start para contenedores optimizados'],
      cons: ['Requiere configurar proyectos y permisos IAM en Google Cloud Console', 'No apto para procesos en segundo plano continuos que no reciben trafico HTTP'],
      sacrifices: ['Sacrificas ejecucion en segundo plano no activada por peticiones o eventos.'],
      idealFor: ['APIs con trafico oscilante o intermitente', 'Webhooks y procesadores de eventos', 'Microservicios modernos'],
      avoidIf: ['Bases de datos en contenedor o procesos continuos sin endpoints'],
    },
  }),
  defineTech({
    id: 'digitalocean',
    name: 'DigitalOcean App Platform',
    category: 'hosting',
    tagline: 'PaaS sencilla y predecible construida sobre la infraestructura de DigitalOcean.',
    description: 'Plataforma para compilar y desplegar aplicaciones web y bases de datos desde repositorios de GitHub con precios fijos, sin sorpresas y documentacion de gran claridad.',
    website: 'https://www.digitalocean.com/products/app-platform',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Developer Cloud',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Hosting gratuito para hasta 3 sitios web estaticos.' },
    tradeoffs: {
      pros: ['Facturacion fija predecible sin costos inesperados por peticion', 'Excelente documentacion y tutoriales accesibles para cualquier nivel', 'Bases de datos gestionadas de Postgres, MySQL y Redis en un clic'],
      cons: ['Menos caracteristicas avanzadas de orquestacion que AWS o Google Cloud', 'Despliegues ligeramente mas lentos que plataformas especializadas en Edge'],
      sacrifices: ['Sacrificas capacidades de edge computing hiperlocalizadas.'],
      idealFor: ['Desarrolladores independientes y agencias', 'Startups en crecimiento temprano', 'Aplicaciones web monoliticas'],
      avoidIf: ['Infraestructuras multinube con requerimientos de latencia extrema'],
    },
  }),
  defineTech({
    id: 'scaleway',
    name: 'Scaleway',
    category: 'hosting',
    tagline: 'Proveedor cloud europeo con servidores dedicados, Kubernetes y Serverless.',
    description: 'Alternativa europea completa a los tres grandes proveedores cloud, con centros de datos ecologicos en Francia, Paises Bajos y Polonia, cumpliendo al 100% con las normativas europeas.',
    website: 'https://www.scaleway.com/',
    license: 'Proprietary',
    isManaged: false,
    isOpenSource: false,
    badgeText: 'European Cloud',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 3, community: 4, maturity: 4, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Capa gratuita generosa en serverless functions, bases de datos y registros Docker.' },
    tradeoffs: {
      pros: ['Cumplimiento estricto con la soberania de datos europea y estandares medioambientales', 'Precios muy competitivos en servidores dedicados e instancias ARM', 'Kubernetes gestionado (Kapsule) con plano de control gratuito'],
      cons: ['Menor red de centros de datos fuera del continente europeo', 'Ecosistema de tutoriales de terceros mas reducido'],
      sacrifices: ['Sacrificas cobertura geografica en Asia y Latinoamerica.'],
      idealFor: ['Empresas europeas con requisitos legales de proteccion de datos', 'Proyectos enfocados en sostenibilidad energetica'],
      avoidIf: ['Aplicaciones enfocadas exclusivamente en mercados de Estados Unidos o Asia'],
    },
  }),
  defineTech({
    id: 'linode',
    name: 'Linode (Akamai)',
    category: 'hosting',
    tagline: 'Infraestructura cloud fiable acelerada por la red de distribucion global de Akamai.',
    description: 'Servicios de computacion en la nube con precios transparentes, soporte tecnico por humanos 24/7 y la potencia de la red CDN y seguridad perimetral de Akamai.',
    website: 'https://www.linode.com/',
    license: 'Proprietary',
    isManaged: false,
    isOpenSource: false,
    badgeText: 'Akamai Cloud',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 2 },
    cost: { initialCost: 'low', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: false, limitsDescription: 'Planes de servidores virtuales desde $5 USD al mes con soporte incluido.' },
    tradeoffs: {
      pros: ['Soporte al cliente por telefono y ticket de calidad superior', 'Precios planos y transparentes en todas las regiones mundiales', 'Conectividad directa con el backbone perimetral de Akamai'],
      cons: ['Menor oferta de servicios serverless especializados que los gigantes cloud', 'Plataforma PaaS menos integrada que alternativas modernas'],
      sacrifices: ['Sacrificas automatizacion de nivel PaaS a favor de maquinas virtuales robustas.'],
      idealFor: ['Empresas que valoran soporte directo y fiabilidad historica', 'Servidores web tradicionales y clusters autogestionados'],
      avoidIf: ['Equipos que buscan entornos ' + 'no-ops' + ' completamente delegados'],
    },
  }),
  defineTech({
    id: 'coolify',
    name: 'Coolify',
    category: 'hosting',
    tagline: 'Alternativa de codigo abierto y auto-hospedable a Heroku, Netlify y Vercel.',
    description: 'Panel de control de despliegue todo-en-uno que se instala en cualquier servidor Linux (Hetzner, DigitalOcean, VPS propio) y permite desplegar aplicaciones, bases de datos y servicios con un clic.',
    website: 'https://coolify.io/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Self-Hosted PaaS',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto sin limites artificiales en tu propio hardware.' },
    tradeoffs: {
      pros: ['Libertad total sin vendor lock-in ni costos por usuario o peticion', 'Soporta despliegues desde GitHub, GitLab y registros Docker', 'Gestion automatica de certificados SSL mediante Traefik y Let\'s Encrypt'],
      cons: ['La seguridad, backups y mantenimiento del servidor base recaen en el usuario', 'Requiere un VPS con un minimo de 2GB de RAM para operar comodamente'],
      sacrifices: ['Sacrificas soporte gestionado 24/7 a cambio de soberania y costes fijos minusculos.'],
      idealFor: ['Desarrolladores independientes con varios proyectos', 'Agencias y consultoras de software', 'Startups conscientes del flujo de caja'],
      avoidIf: ['Equipos corporativos con politicas que prohiben software auto-alojado sin contratos SLA'],
    },
  }),
];
