import type { Technology } from '../types';
import { defineTech } from './builder';

export const MOBILE_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'react-native-expo',
    name: 'React Native (Expo)',
    category: 'mobile',
    tagline: 'El estandar moderno para construir aplicaciones nativas universales con React.',
    description: 'Permite compilar una sola base de codigo en JavaScript/TypeScript a aplicaciones nativas reales para iOS, Android y Web, con compilaciones en la nube (EAS), actualizaciones OTA y Expo Router basado en archivos.',
    website: 'https://expo.dev/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Universal React',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Framework 100% de codigo abierto; Expo Application Services (EAS) incluye compilaciones gratuitas.' },
    tradeoffs: {
      pros: ['Reutilizacion masiva de logica, componentes y habilidades del equipo de React', 'Expo Router lleva la arquitectura moderna de rutas de Next.js al mundo nativo movil', 'Capacidad de actualizar la app al instante mediante Over-The-Air (OTA) updates sin pasar de nuevo por revision de Apple/Google'],
      cons: ['Depuracion ocasional de puentes nativos con librerias de C++ o Kotlin muy especializadas', 'Rendimiento en animaciones hipercomplejas de 120 FPS que requiere optimizaciones con react-native-reanimated'],
      sacrifices: ['Sacrificas rendimiento nativo crudo en aplicaciones 3D por una velocidad de desarrollo y reutilizacion de equipo insuperables.'],
      idealFor: ['Startups y empresas con equipos familiarizados con React y TypeScript', 'Aplicaciones SaaS con version movil complementaria', 'E-commerce multiplataforma'],
      avoidIf: ['Juegos 3D intensivos o apps con procesamiento de senales de hardware en tiempo real estricto'],
    },
  }),
  defineTech({
    id: 'flutter',
    name: 'Flutter',
    category: 'mobile',
    tagline: 'Kit de herramientas de UI multiplataforma de Google compilado a codigo nativo.',
    description: 'Motor de renderizado propio (Impeller) que dibuja cada pixel en pantalla con el lenguaje Dart, garantizando disenos identicos, animaciones fluidas a 60/120 FPS en iOS, Android, Desktop y Web.',
    website: 'https://flutter.dev/',
    license: 'BSD-3-Clause',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'High Performance UI',
    metrics: { dx: 5, learningCurve: 3, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% software libre y gratuito respaldado por Google.' },
    tradeoffs: {
      pros: ['Rendimiento grafico consistente y fluido sin depender de los componentes visuales nativos del sistema operativo', 'Excelente herramienta de recarga en caliente (Hot Reload) durante el desarrollo', 'Unico codigo fuente que compila verdaderamente a iOS, Android, Linux, macOS y Windows'],
      cons: ['Requiere aprender el lenguaje de programacion Dart', 'La experiencia de renderizado en web (Flutter Web) es mas pesada en tamano de descarga que una aplicacion web tradicional en HTML/CSS'],
      sacrifices: ['Sacrificas ligereza y SEO en navegadores web a cambio de una perfeccion grafica total en moviles y escritorio.'],
      idealFor: ['Aplicaciones moviles con disenos y animaciones visuales sumamente personalizados', 'Apps financieras y bancarias', 'Equipos que quieren cubrir iOS y Android con una sola tecnologia'],
      avoidIf: ['Proyectos orientados primordialmente a navegadores web de escritorio donde el SEO es critico'],
    },
  }),
  defineTech({
    id: 'capacitor',
    name: 'Capacitor',
    category: 'mobile',
    tagline: 'Runtime nativo multiplataforma que convierte cualquier aplicacion web moderna en app nativa.',
    description: 'El sucesor moderno de Cordova/PhoneGap creado por el equipo de Ionic: envuelve tu aplicacion web construida con React, Vue, Svelte o Angular en un WebView nativo con acceso completo a hardware mediante plugins.',
    website: 'https://capacitorjs.com/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Web to Native',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% gratuito y de codigo abierto.' },
    tradeoffs: {
      pros: ['Permite empaquetar una web app existente para la App Store y Google Play en cuestion de horas', 'Acceso a camara, notificaciones, biometria y almacenamiento local con plugins estandar en JavaScript', 'Cero necesidad de rehacer la interfaz de usuario en otro lenguaje'],
      cons: ['Rendimiento limitado por el motor WebView del navegador del sistema operativo', 'Las animaciones pesadas o listas infinitas pueden sentirse menos fluidas que en React Native o Flutter'],
      sacrifices: ['Sacrificas sensacion nativa al 100% a favor del menor tiempo y costo posible de salida a las tiendas de apps.'],
      idealFor: ['Startups con una aplicacion web existente que necesitan publicar en App Store y Google Play rapido', 'Paneles de administracion y apps de gestion interna'],
      avoidIf: ['Juegos, herramientas de edicion de video o apps que requieran 120 FPS fluidos'],
    },
  }),
  defineTech({
    id: 'tauri',
    name: 'Tauri',
    category: 'mobile',
    tagline: 'Crea aplicaciones de escritorio y moviles mas pequenas, rapidas y seguras con Rust y frontend web.',
    description: 'Alternativa moderna a Electron: utiliza el backend de alto rendimiento y seguridad de Rust junto con los motores WebView del sistema operativo, reduciendo ejecutables a pocos megabytes y consumo minimo de RAM.',
    website: 'https://tauri.app/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Rust + Web',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% software libre y de codigo abierto.' },
    tradeoffs: {
      pros: ['Tamano del instalador diminuto (a menudo menos de 5 MB frente a los 100+ MB de Electron)', 'Consumo de memoria RAM insignificante y seguridad reforzada por el sistema de tipos de Rust', 'Soporta cualquier framework web en el frontend (React, Vue, Svelte, Solid) y compila a macOS, Windows, Linux, iOS y Android en Tauri 2.0'],
      cons: ['Escribir logica de sistema o plugins avanzados requiere conocimientos de Rust', 'Diferencias sutiles de renderizado entre navegadores del sistema (WebKit en macOS, WebView2 en Windows)'],
      sacrifices: ['Sacrificas la homogeneidad de Chromium integrado a cambio de una reduccion drastica de memoria y espacio en disco.'],
      idealFor: ['Aplicaciones de escritorio modernas para macOS/Windows/Linux', 'Herramientas para desarrolladores y utilidades de productividad', 'Apps locales que cuidan el consumo de recursos'],
      avoidIf: ['Equipos con cero interes o capacidad para compilar entornos en Rust'],
    },
  }),
  defineTech({
    id: 'swift-ios',
    name: 'Swift / SwiftUI (iOS)',
    category: 'mobile',
    tagline: 'Desarrollo nativo puro para el ecosistema Apple (iOS, iPadOS, macOS, watchOS, visionOS).',
    description: 'El lenguaje moderno, seguro y expresivo disenado por Apple, complementado con el framework declarativo SwiftUI para crear interfaces fluidas y profundamente integradas con el hardware de Apple.',
    website: 'https://developer.apple.com/swift/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Apple Native',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 4 },
    cost: { initialCost: 'low', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Swift es de codigo abierto; la membresia Apple Developer Program para publicar en App Store cuesta $99 USD/ano.' },
    tradeoffs: {
      pros: ['Acceso el dia 0 a cada nueva funcionalidad y API anunciada por Apple (Dynamic Island, Widgets, Apple Silicon, Vision Pro)', 'Rendimiento y consumo de bateria optimos sin capas intermedias', 'SwiftUI permite una composicion declarativa limpia y reactiva'],
      cons: ['Exclusivo del ecosistema Apple (no permite generar aplicaciones para Android)', 'Requiere obligatoriamente un ordenador Mac para compilar y probar'],
      sacrifices: ['Sacrificas soporte multiplataforma para Android a favor de la mejor experiencia de usuario posible en dispositivos Apple.'],
      idealFor: ['Aplicaciones donde la calidad visual y la experiencia en iOS son el principal factor competitivo', 'Juegos nativos y apps con integracion profunda de hardware Apple'],
      avoidIf: ['Startups que necesitan validar hipotesis simultaneamente en Android y web con poco presupuesto'],
    },
  }),
  defineTech({
    id: 'kotlin-android',
    name: 'Kotlin / Jetpack Compose (Android)',
    category: 'mobile',
    tagline: 'El estandar oficial y preferido por Google para el desarrollo nativo moderno en Android.',
    description: 'Lenguaje conciso y seguro contra nulos (null-safety) que reemplazo a Java, combinado con el toolkit declarativo Jetpack Compose para acelerar la construccion de interfaces nativas en Android.',
    website: 'https://developer.android.com/jetpack/compose',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Android Native',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto; cuota unica de registro en Google Play de $25 USD.' },
    tradeoffs: {
      pros: ['Soporte oficial incondicional de Google con Android Studio como entorno de desarrollo lider', 'Jetpack Compose simplifica drasticamente la creacion de UI reactiva y animaciones en Android', 'Interoperabilidad bidireccional total con bibliotecas Java historicas'],
      cons: ['Limitado al sistema operativo Android (a menos que se use Kotlin Multiplatform)', 'Tiempos de compilacion en proyectos masivos de Android Studio que pueden ser elevados'],
      sacrifices: ['Sacrificas alcance directo a usuarios de iPhone a cambio del dominio absoluto del 70% del mercado global de dispositivos moviles.'],
      idealFor: ['Apps con uso intensivo de servicios en segundo plano de Android', 'Hardware personalizado (terminales POS, televisores Android TV)', 'Equipos dedicados a la plataforma Android'],
      avoidIf: ['Equipos pequenos que no tienen capacidad para mantener dos bases de codigo separadas para iOS y Android'],
    },
  }),
  defineTech({
    id: 'electron',
    name: 'Electron',
    category: 'mobile',
    tagline: 'Construye aplicaciones de escritorio multiplataforma con JavaScript, HTML y CSS.',
    description: 'Empaqueta Chromium y Node.js en un ejecutable de escritorio, impulsando algunas de las herramientas mas utilizadas del planeta como VS Code, Slack, Discord y Figma.',
    website: 'https://www.electronjs.org/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Desktop Giant',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito.' },
    tradeoffs: {
      pros: ['Permite que desarrolladores web construyan software de escritorio potente sin aprender C++ o Rust', 'Garantiza que el diseno se vea exactamente igual en macOS, Windows y Linux', 'Ecosistema gigantesco con soluciones probadas para actualizadores automaticos, menus nativos y bandeja del sistema'],
      cons: ['Alto consumo de memoria RAM al ejecutar una instancia completa de Chromium por cada aplicacion', 'Tamano de instalador grande (generalmente mas de 80 MB)'],
      sacrifices: ['Sacrificas ligereza y ahorro de memoria a favor de estabilidad y homogeneidad visual multiplataforma.'],
      idealFor: ['Software de escritorio complejo (editores de codigo, mensajeria, suites creativas)', 'Equipos con amplia experiencia en frontend web'],
      avoidIf: ['Pequenas utilidades en segundo plano que deben consumir menos de 20 MB de RAM'],
    },
  }),
  defineTech({
    id: 'kmp',
    name: 'Kotlin Multiplatform (KMP)',
    category: 'mobile',
    tagline: 'Comparte logica de negocio y redes entre iOS y Android manteniendo UIs nativas.',
    description: 'Tecnologia de JetBrains que permite escribir el modelo de datos, la capa de red, la base de datos local y la logica de negocio en Kotlin una sola vez, manteniendo la interfaz 100% nativa (SwiftUI en iOS y Compose en Android).',
    website: 'https://www.jetbrains.com/kotlin-multiplatform/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Shared Logic',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y libre de licencias.' },
    tradeoffs: {
      pros: ['No impone un motor de UI no estandar: los desarrolladores de iOS siguen usando SwiftUI y los de Android Jetpack Compose', 'Elimina la duplicacion propensa a errores en logica de validaciones, autenticacion y algoritmos', 'Respaldado por Google y adoptado por companias como Netflix, McDonald\'s y Cash App'],
      cons: ['Curva de configuracion inicial de Gradle y bindings entre Swift y Kotlin', 'Menos plugins prefabricados de terceros que en el ecosistema React Native'],
      sacrifices: ['Sacrificas una interfaz de usuario unica compartida a favor de interfaces autenticamente nativas con logica compartida.'],
      idealFor: ['Empresas con equipos separados de iOS y Android que buscan unificar logica sin degradar la UI nativa', 'Apps financieras de alta complejidad'],
      avoidIf: ['Proyectos individuales rapidos donde el desarrollador busca una sola tecnologia para UI y logica a la vez'],
    },
  }),
  defineTech({
    id: 'ionic',
    name: 'Ionic Framework',
    category: 'mobile',
    tagline: 'Biblioteca de componentes de UI movil optimizados para aplicaciones web e hibridas.',
    description: 'Coleccion completa de componentes visuales (listas, tabs, modales, drawers) que adaptan su estilo automaticamente a iOS (Cupertino) o Android (Material Design) ejecutandose en la web o empaquetados con Capacitor.',
    website: 'https://ionicframework.com/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'UI Components',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Framework de componentes 100% gratuito y de codigo abierto.' },
    tradeoffs: {
      pros: ['Componentes de interfaz movil listos para usar con comportamiento tactil nativo', 'Compatible con React, Angular y Vue.js', 'Excelente para aplicaciones web progresivas (PWAs) que tambien se publican en tiendas'],
      cons: ['Sensacion de renderizado web en transiciones de navegacion complejas', 'Mayor sobrecarga de CSS que componentes nativos puros'],
      sacrifices: ['Sacrificas la autenticidad nativa de bajo nivel a cambio de una velocidad de diseno de interfaces inmediata.'],
      idealFor: ['Desarrolladores con experiencia previa en Angular o Vue', 'PWAs moviles', 'Prototipos de aplicaciones de negocio'],
      avoidIf: ['Aplicaciones de alta gama visual donde cada microinteraccion debe ser estrictamente nativa'],
    },
  }),
];
