import type { Technology } from '../types';
import { defineTech } from './builder';

export const MONITORING_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'sentry',
    name: 'Sentry',
    category: 'monitoring',
    tagline: 'Seguimiento de errores y rendimiento de aplicaciones de extremo a extremo en tiempo real.',
    description: 'La plataforma de observabilidad para desarrolladores mas utilizada, capaz de capturar excepciones en frontend, backend y movil con stack traces desofuscados con Source Maps.',
    website: 'https://sentry.io/',
    license: 'FSL-1.1-Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Error Tracking Standard',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '5,000 errores, 10,000 transacciones y 50 sesiones de replay gratis al mes en plan Developer.' },
    tradeoffs: {
      pros: ['Soporte de Source Maps y recreacion visual de la sesion del usuario previa al error (Session Replay)', 'SDKs de integracion trivial en practicamente cualquier framework moderno', 'Excelente agrupacion automatica y reduccion de ruido de alertas'],
      cons: ['Las cuotas mensuales de eventos pueden agotarse rapidamente durante picos anómalos si no se configura ' + 'sampling' + ' adecuado', 'La version auto-alojada en Docker exige considerables recursos de memoria RAM'],
      sacrifices: ['Sacrificas consumo de cuota si no configuras reglas de filtrado de errores irrelevantes en el cliente.'],
      idealFor: ['Cualquier aplicacion web, API o app movil moderna en produccion', 'Depuracion de bugs frontend'],
      avoidIf: ['Entornos aislados de red donde no es posible enviar telemetria externa y no hay recursos para self-hosting'],
    },
  }),
  defineTech({
    id: 'betterstack',
    name: 'Better Stack',
    category: 'monitoring',
    tagline: 'Monitoreo de uptime y gestion de logs hiperrapida basada en ClickHouse.',
    description: 'Combina monitorizacion de tiempo de actividad con guardias de incidentes telefonicos (Better Stack Uptime) y busqueda de logs en tiempo real SQL (Better Stack Logs).',
    website: 'https://betterstack.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Modern Observability',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '10 monitores de uptime con revisiones cada 3 minutos y 1 GB de logs gratis al mes.' },
    tradeoffs: {
      pros: ['Interfaz de usuario visualmente impresionante, fluida y con modo oscuro impecable', 'Consultas sobre logs a velocidad instantanea gracias a la base de datos ClickHouse subyacente', 'Paginas de estado publicas hermosas incluidas de serie'],
      cons: ['Catalogo de integraciones de APM profundo menor que Datadog', 'Periodo de retencion de logs limitado en los planes inferiores'],
      sacrifices: ['Sacrificas metricas de profiling de codigo hipercomplejas a favor de sencillez radical y velocidad.'],
      idealFor: ['Startups y scaleups modernas', 'Equipos que necesitan saber de inmediato si su web o API se cayo', 'Paginas de estado para usuarios'],
      avoidIf: ['Infraestructuras monoliticas legacy de telecomunicaciones que requieren agentes SNMP'],
    },
  }),
  defineTech({
    id: 'posthog',
    name: 'PostHog',
    category: 'monitoring',
    tagline: 'Suite todo-en-uno de analitica de producto, grabacion de sesiones, feature flags y A/B tests.',
    description: 'La navaja suiza para el crecimiento de software: combina analitica de eventos, mapas de calor, reproduccion de sesiones de usuario, pruebas A/B y despliegues por feature flags.',
    website: 'https://posthog.com/',
    license: 'MIT',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Product Analytics',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '1 millon de eventos analiticos y 5,000 grabaciones de sesion gratis cada mes.' },
    tradeoffs: {
      pros: ['Reemplaza hasta 5 herramientas separadas (Mixpanel, LaunchDarkly, FullStory, Hotjar y Optimizely)', 'Capa gratuita mensual extremadamente generosa que cubre la mayoria de proyectos en arranque', 'Codigo abierto con opcion de despliegue en tu propia infraestructura'],
      cons: ['El script del cliente web puede anadir peso al bundle si se activan todas las funciones a la vez', 'Curva de aprendizaje para crear ' + 'funnels' + ' y cohortes avanzadas'],
      sacrifices: ['Sacrificas un bundle ultraligero a cambio de un arsenal de medicion de producto sin rival.'],
      idealFor: ['Startups SaaS enfocadas en producto y conversion', 'Equipos que realizan experimentos continuos y feature flags'],
      avoidIf: ['Sitios de contenido puramente estatico donde solo importa contar visitas basicas'],
    },
  }),
  defineTech({
    id: 'umami',
    name: 'Umami',
    category: 'monitoring',
    tagline: 'Analitica web respetuosa con la privacidad, ligera y alternativa a Google Analytics.',
    description: 'Herramienta de analitica de codigo abierto que no recopila datos personales, no utiliza cookies, cumple estrictamente con el RGPD y se auto-aloja en una simple base de datos Postgres o MySQL.',
    website: 'https://umami.is/',
    license: 'MIT',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Privacy Analytics',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% gratuito para self-hosting o 10,000 eventos/mes en Umami Cloud gratis.' },
    tradeoffs: {
      pros: ['No requiere mostrar molestos banners de aceptacion de cookies en la Union Europea', 'Script de seguimiento diminuto (menos de 2 KB) que no penaliza las puntuaciones de Core Web Vitals', 'Interfaz limpia, rapida y facil de compartir publicamente'],
      cons: ['No incluye analisis de cohortes profundas ni perfiles de usuario individuales complejos', 'No pensado para atribucion de campanas publicitarias multinivel avanzadas'],
      sacrifices: ['Sacrificas metricas intrusivas de rastreo publicitario a favor de privacidad y respeto al usuario.'],
      idealFor: ['Blogs personales, documentaciones tecnicas, portales corporativos y SaaS independientes'],
      avoidIf: ['Agencias de marketing digital que dependen del seguimiento publicitario entre sitios de Google Ads'],
    },
  }),
  defineTech({
    id: 'grafana',
    name: 'Grafana',
    category: 'monitoring',
    tagline: 'La plataforma de codigo abierto de visualizacion y paneles de observabilidad lider del mundo.',
    description: 'Permite consultar, visualizar, alertar y comprender metricas sin importar donde esten almacenadas (Prometheus, InfluxDB, Elasticsearch, PostgreSQL, Loki).',
    website: 'https://grafana.com/',
    license: 'AGPL-3.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Open Observability',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Completamente gratis para self-hosting o plan Grafana Cloud con 10k metricas gratis.' },
    tradeoffs: {
      pros: ['Capacidad ilimitada de personalizacion grafica de cualquier flujo de datos del planeta', 'Soporta mas de 100 fuentes de datos dispares sin obligar a migrar tus bases de datos', 'Ecosistema gigantesco de dashboards creados por la comunidad listos para importar'],
      cons: ['Configuracion de alertas y paneles requiere familiaridad con lenguajes de consulta como PromQL o LogQL', 'Mantenimiento del stack completo (Grafana + Prometheus + Loki) si se corre on-premise'],
      sacrifices: ['Sacrificas configuracion automatica sin esfuerzo a cambio de control visual y analitico absoluto.'],
      idealFor: ['Equipos DevOps y de infraestructura', 'Monitorizacion de servidores, clusters Kubernetes y bases de datos'],
      avoidIf: ['Equipos que solo quieren instalar un paquete npm y ver graficas prediseñadas en 2 minutos'],
    },
  }),
  defineTech({
    id: 'axiom',
    name: 'Axiom',
    category: 'monitoring',
    tagline: 'Analitica de logs serverless ultrarrapida a una fraccion del costo tradicional.',
    description: 'Plataforma para capturar peticiones, eventos y registros de logs de cualquier tamano, optimizada para arquitecturas serverless como Vercel, AWS Lambda y Cloudflare.',
    website: 'https://axiom.co/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Serverless Logs',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '0.5 TB de ingestion de logs y 30 dias de retencion gratuitos cada mes.' },
    tradeoffs: {
      pros: ['Ingestion y almacenamiento de terabytes de logs a costes drasticamente inferiores a Datadog', 'Integracion en 1 clic con Vercel para monitorizar todas las funciones serverless', 'Sintaxis de consulta similar a Kusto (KQL) rapida y expresiva'],
      cons: ['Menor enfoque en trazado distribuido profundo (APM) a nivel de metodos internos', 'Herramienta mas reciente en el cuadrante de observabilidad'],
      sacrifices: ['Sacrificas APM granular de codigo a cambio de retencion masiva de logs a bajo costo.'],
      idealFor: ['Despliegues en Vercel y Cloudflare Workers', 'SaaS con alto volumen de solicitudes HTTP', 'Auditorias de logs'],
      avoidIf: ['Infraestructuras basadas en Java / mainframe que requieren agentes de instrumentacion clasicos'],
    },
  }),
  defineTech({
    id: 'datadog',
    name: 'Datadog',
    category: 'monitoring',
    tagline: 'Plataforma de observabilidad, rendimiento (APM), redes y seguridad a nivel enterprise.',
    description: 'El estandar dorado corporativo para monitorizar la totalidad de la pila tecnologica: infraestructura de servidores, trazas de microservicios, seguridad en tiempo real y gestion de red.',
    website: 'https://www.datadoghq.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Enterprise Leader',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'high', scalingRisk: 'high', hasFreeTier: true, limitsDescription: 'Capa gratuita limitada a 5 hosts; luego facturacion por host y volumen de metricas.' },
    tradeoffs: {
      pros: ['Cobertura de observabilidad integral inigualable con mas de 600 integraciones oficiales', 'Correlacion instantanea entre logs, trazas de APM y metricas de CPU/memoria', 'Capacidades de deteccion de anomalias con machine learning incorporadas'],
      cons: ['Coste economico notablemente alto que puede descontrolarse con mal uso de metricas custom', 'Curva de configuracion y gobernanza corporativa rigurosa'],
      sacrifices: ['Sacrificas contencion de costes a cambio de la suite de monitorizacion corporativa mas madura.'],
      idealFor: ['Grandes empresas cotizadas', 'Equipos con cientos de microservicios distribuidos en Kubernetes'],
      avoidIf: ['Startups en etapa inicial con presupuestos operativos reducidos'],
    },
  }),
  defineTech({
    id: 'newrelic',
    name: 'New Relic',
    category: 'monitoring',
    tagline: 'Plataforma de observabilidad integral con modelo de precios basado en consumo de datos.',
    description: 'Permite a los ingenieros recopilar y analizar toda la telemetria en un solo lugar con 100 GB de datos gratuitos cada mes y agentes especializados para Node, Python, Java y Go.',
    website: 'https://newrelic.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Full-Stack Telemetry',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '100 GB de ingestion de datos gratuitos al mes para siempre con 1 usuario Full Platform.' },
    tradeoffs: {
      pros: ['Modelo de 100 GB gratuitos al mes muy atractivo para equipos pequenos', 'Trazabilidad profunda de consultas de base de datos lentas y cuellos de botella', 'Visualizacion clara de mapas de dependencias de servicios'],
      cons: ['La interfaz web historica ha sufrido redisenos que alteran la navegacion habitual', 'El coste por usuario con permisos de edicion (Full Platform User) es elevado'],
      sacrifices: ['Sacrificas simplicidad de licencias por usuario a favor de una cuota de datos generosa.'],
      idealFor: ['Equipos tecnicos que quieren APM avanzado sin pagar desde el primer dia', 'Monolitos en Ruby on Rails o Django'],
      avoidIf: ['Equipos muy numerosos que necesitan conceder acceso completo a decenas de desarrolladores'],
    },
  }),
  defineTech({
    id: 'glitchtip',
    name: 'GlitchTip',
    category: 'monitoring',
    tagline: 'Rastreador de errores de codigo abierto compatible con el SDK de Sentry.',
    description: 'Alternativa libre y ligera a Sentry centrada exclusivamente en la captura sencilla de excepciones y tiempos de actividad, sin la sobrecarga ni el peso de servicios innecesarios.',
    website: 'https://glitchtip.com/',
    license: 'GPL-3.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Sentry Alternative',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% gratuito para self-hosting o plan GlitchTip Cloud a precios accesibles.' },
    tradeoffs: {
      pros: ['Funciona directamente con los SDKs oficiales de Sentry sin cambiar una linea de logica', 'Consumo de recursos en servidor minimo (corre con una fraccion de la RAM de Sentry)', 'Software libre comprometido con la sencillez'],
      cons: ['Menos caracteristicas accesorias avanzadas (sin session replay ni profiling profundo)', 'Equipo de desarrollo mas reducido que el de las grandes corporaciones'],
      sacrifices: ['Sacrificas funciones de grabacion visual por un sistema ligero y economico.'],
      idealFor: ['Desarrolladores que prefieren alojar sus propias herramientas sin complejidad excesiva', 'Startups con poco presupuesto de infraestructura'],
      avoidIf: ['Equipos que requieren grabacion en video de la sesion del usuario para reproducir bugs visuales'],
    },
  }),
  defineTech({
    id: 'cronitor',
    name: 'Cronitor',
    category: 'monitoring',
    tagline: 'Monitorizacion elegante de tareas programadas (cron jobs), microservicios y latencia.',
    description: 'Asegura que tus tareas en segundo plano, backups y procesos batch se ejecuten a tiempo y no se queden congelados silenciosamente sin avisar al equipo.',
    website: 'https://cronitor.io/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Cron Monitoring',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '5 monitores gratuitos para siempre con alertas en Slack, Discord o Telegram.' },
    tradeoffs: {
      pros: ['Detecta no solo si una tarea falla sino tambien si tardo demasiado tiempo o nunca comenzo', 'Integracion con una sola linea envolviendo el comando en el crontab o mediante API', 'Alertas multicanal precisas'],
      cons: ['Especializado en un caso de uso concreto (no reemplaza un APM completo)', 'El numero de monitores en el plan gratis es ajustado si tienes muchas tareas'],
      sacrifices: ['Sacrificas una herramienta global por un especialista de alta precision en tareas batch.'],
      idealFor: ['Cualquier sistema con scripts de cron criticos, generacion de facturas o sincronizaciones'],
      avoidIf: ['Aplicaciones 100% orientadas a eventos en tiempo real sin tareas programadas'],
    },
  }),
  defineTech({
    id: 'checkly',
    name: 'Checkly',
    category: 'monitoring',
    tagline: 'Monitoreo sintetico y verificacion activa de APIs impulsado por Playwright.',
    description: 'Ejecuta scripts de prueba de extremo a extremo (E2E) con Playwright y revisiones de APIs HTTP a intervalos regulares desde centros de datos de todo el mundo (Monitoring as Code).',
    website: 'https://www.checklyhq.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Playwright Synthetics',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Plan gratuito con revisiones de APIs cada minuto y ejecuciones Playwright programadas.' },
    tradeoffs: {
      pros: ['Permite simular el flujo real de un usuario (login, compra, checkout) cada pocos minutos', 'Enfoque ' + 'Monitoring as Code' + ' gestionado directamente desde el repositorio Git', 'Alertas antes de que los clientes reales noten que una ruta crucial fallo'],
      cons: ['Escribir y mantener pruebas sinteticas de navegador requiere esfuerzo de testing continuo', 'Mayor coste por ejecucion de navegador Playwright que simples pings HTTP'],
      sacrifices: ['Sacrificas mantenimiento de tests a cambio de certeza absoluta en flujos criticos de negocio.'],
      idealFor: ['Flujos criticos de e-commerce (carrito y checkout)', 'Plataformas SaaS con integraciones API complejas'],
      avoidIf: ['Sitios web que solo necesitan una simple comprobacion de si el servidor devuelve codigo 200'],
    },
  }),
  defineTech({
    id: 'uptimerobot',
    name: 'UptimeRobot',
    category: 'monitoring',
    tagline: 'El servicio lider y mas popular para verificar el estado de sitios web y APIs.',
    description: 'Revisa tus servidores y endpoints HTTP, puertos y certificados SSL cada pocos minutos y envia notificaciones instantaneas por email, SMS o webhook en caso de caida.',
    website: 'https://uptimerobot.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Uptime Classic',
    metrics: { dx: 4, learningCurve: 1, scalability: 4, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '50 monitores con revisiones cada 5 minutos completamente gratis.' },
    tradeoffs: {
      pros: ['50 monitores en el plan gratuito que cubren las necesidades de practicamente cualquier desarrollador', 'Configuracion en 30 segundos sin necesidad de instalar agentes ni modificar codigo', 'Supervisión de fecha de caducidad de certificados SSL'],
      cons: ['El intervalo de chequeo del plan gratuito es de 5 minutos (puede tardar en alertar caidas breves)', 'No realiza simulaciones complejas dentro del navegador'],
      sacrifices: ['Sacrificas rapidez de alerta de 30 segundos a favor de una gran cantidad de monitores gratuitos.'],
      idealFor: ['Portafolios, APIs, sitios personales y pequenas empresas', 'Seguimiento de certificados SSL'],
      avoidIf: ['Sistemas de alta frecuencia donde una caida de 3 minutos supone perdidas millonarias'],
    },
  }),
  defineTech({
    id: 'healthchecks',
    name: 'Healthchecks.io',
    category: 'monitoring',
    tagline: 'Servicio ligero de monitorizacion tipo cron y latido de corazon (Heartbeat).',
    description: 'Servicio de ' + 'Dead Man\'s Snitch' + ' minimalista y de codigo abierto: tu servidor realiza un ping HTTP periodico al finalizar un script; si el ping no llega a tiempo, se dispara la alarma.',
    website: 'https://healthchecks.io/',
    license: 'BSD-3-Clause',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Heartbeat Ping',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '20 comprobaciones gratuitas en la nube oficial o 100% gratis en self-hosting.' },
    tradeoffs: {
      pros: ['Concepto de ' + 'escucha pasiva' + ' extremadamente confiable para backups y tareas nocturnas', 'Sin dependencias externas complejas ni librerias pesadas (basta una simple llamada con curl)', 'Codigo abierto disponible para ejecutar en cualquier servidor propio'],
      cons: ['Disenado exclusivamente para avisar de tareas que no llegaron (no captura excepciones detalladas)', 'No reemplaza una herramienta de APM o analitica'],
      sacrifices: ['Sacrificas telemetria rica a favor de una garantia simple e inquebrantable de ejecucion.'],
      idealFor: ['Backups de bases de datos', 'Scripts nocturnos de sincronizacion', 'Tareas cron en servidores Linux'],
      avoidIf: ['Monitorizacion del tiempo de carga visual de paginas web'],
    },
  }),
  defineTech({
    id: 'aptabase',
    name: 'Aptabase',
    category: 'monitoring',
    tagline: 'Analitica ligera y orientada a la privacidad para aplicaciones moviles, desktop y web.',
    description: 'Alternativa de codigo abierto a Google Analytics y Firebase Analytics, pensada para que las apps moviles y de escritorio no infrinjan la privacidad de sus usuarios.',
    website: 'https://aptabase.com/',
    license: 'AGPL-3.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'App Analytics',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 3, operationalComplexity: 1, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '20,000 eventos gratuitos al mes en el cloud o auto-alojamiento ilimitado.' },
    tradeoffs: {
      pros: ['SDK nativo diminuto para Flutter, React Native, Swift, Kotlin, Tauri y Electron', 'No recopila identificadores de publicidad invasivos (IDFA / GAID)', 'Totalmente alineado con los requisitos estrictos de la App Store y Google Play'],
      cons: ['Herramienta en rapido desarrollo con menor volumen de funciones que Firebase', 'No incluye mensajeria push integrada'],
      sacrifices: ['Sacrificas la suite masiva de Google Firebase a cambio de privacidad y ligereza.'],
      idealFor: ['Aplicaciones moviles y de escritorio (Tauri, Electron)', 'Desarrolladores independientes que venden apps'],
      avoidIf: ['Grandes juegos moviles que requieren atribucion compleja de redes publicitarias'],
    },
  }),
  defineTech({
    id: 'mixpanel',
    name: 'Mixpanel',
    category: 'monitoring',
    tagline: 'Analitica de producto basada en eventos enfocada en retencion, conversion y funnels.',
    description: 'Pionero en el analisis profundo de las acciones de los usuarios dentro de aplicaciones digitales, con informes interactivos de conversion, retencion y desgloses de comportamiento.',
    website: 'https://mixpanel.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Event Analytics',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Hasta 20 millones de eventos mensuales gratis en el plan gratuito para startups.' },
    tradeoffs: {
      pros: ['Capacidades de segmentacion y analisis de conversion de usuario lideres del sector', 'Informes visuales faciles de interpretar por fundadores, disennadores y marketing', 'Integraciones directas con almacenes de datos (Snowflake, BigQuery)'],
      cons: ['Requiere planificacion deliberada del esquema de nombres de eventos para evitar caos', 'Las funcionalidades avanzadas de modelos predictivos requieren planes de pago'],
      sacrifices: ['Sacrificas grabacion de pantallas a cambio de informes estadisticos ultra precisos.'],
      idealFor: ['Startups SaaS y aplicaciones moviles que buscan validar Product-Market Fit', 'Optimizacion de embudos de registro'],
      avoidIf: ['Sitios de comercio electronico muy simples o blogs'],
    },
  }),
  defineTech({
    id: 'amplitude',
    name: 'Amplitude',
    category: 'monitoring',
    tagline: 'Plataforma de inteligencia de producto para analizar el ciclo de vida del usuario.',
    description: 'Herramienta de analitica avanzada utilizada por empresas de primer nivel para comprender que caracteristicas de un producto impulsan la retencion y el valor del cliente a largo plazo.',
    website: 'https://amplitude.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Product Intelligence',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'high', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Plan inicial gratuito con hasta 50,000 usuarios activos mensuales (MTUs).' },
    tradeoffs: {
      pros: ['Analisis de cohortes y correlacion de comportamiento del cliente de alta precision', 'Recomendaciones y graficas predictivas orientadas a la reduccion del churn', 'Gran reputacion en companias tecnicas consolidadas'],
      cons: ['Precios elevados una vez que se superan las cuotas del plan gratuito', 'Curva de adopcion que requiere entrenamiento del equipo no tecnico'],
      sacrifices: ['Sacrificas rapidez de configuracion inicial a favor de sofisticacion analitica a largo plazo.'],
      idealFor: ['Empresas digitales medianas y grandes', 'Equipos dedicados de ingenieria y analistas de datos'],
      avoidIf: ['Proyectos individuales en sus primeros dias de ideacion'],
    },
  }),
];
