import type { Technology } from '../types';
import { defineTech } from './builder';

export const PAYMENT_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'stripe',
    name: 'Stripe',
    category: 'payments',
    tagline: 'Infraestructura financiera global y pasarela de pagos estandar para desarrolladores.',
    description: 'La API de pagos mas potente del mundo, con soporte para tarjetas de credito, debito, transferencias bancarias, suscripciones recurrentes, facturacion B2B y prevencion de fraude con Radar.',
    website: 'https://stripe.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Industry Standard',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Sin cuotas fijas mensuales; comision estandar de ~2.9% + 30c por transaccion exitosa.' },
    tradeoffs: {
      pros: ['APIs, webhooks y documentacion tecnica consideradas el patron de oro de la industria', 'Soporte global para mas de 135 divisas y metodos de pago locales', 'Suite de productos completa: Billing, Connect, Invoicing, Tax y Radar'],
      cons: ['No actua como Merchant of Record (MoR) en el plan basico (requiere que el usuario liquide IVA/impuestos locales)', 'Cuentas sujetas a revisiones estrictas en sectores de alto riesgo'],
      sacrifices: ['Sacrificas delegacion de responsabilidad fiscal internacional (a menos que uses Stripe Tax o un MoR).'],
      idealFor: ['Startups con entidad legal constituida', 'E-commerce a gran escala', 'Marketplaces con payouts a terceros via Stripe Connect'],
      avoidIf: ['Creadores en solitario que no quieren lidiar con declaraciones de IVA internacional en 80 paises'],
    },
  }),
  defineTech({
    id: 'lemonsqueezy',
    name: 'Lemon Squeezy',
    category: 'payments',
    tagline: 'Merchant of Record todo-en-uno para venta de software y SaaS con gestion fiscal automatica.',
    description: 'Gestiona la venta de productos digitales, licencias de software y suscripciones SaaS asumiendo la responsabilidad legal y fiscal del cobro de impuestos globales (IVA, VAT, sales tax).',
    website: 'https://www.lemonsqueezy.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Merchant of Record',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Sin coste fijo mensual; comision de ~5% + 50c por transaccion procesada.' },
    tradeoffs: {
      pros: ['Elimina la pesadilla del IVA y los impuestos de venta transfronterizos actuando como MoR', 'Portal del cliente, recuperacion de carritos y generacion de claves de licencia listos para usar', 'Integracion veloz con webhooks y SDKs modernos'],
      cons: ['Comision porcentual por venta ligeramente mas alta que la pasarela cruda de Stripe', 'Retiros de fondos sujetos a periodos de retencion y liquidacion programada'],
      sacrifices: ['Sacrificas unos puntos porcentuales de margen a cambio de eliminar la carga fiscal administrativa.'],
      idealFor: ['Indie hackers y desarrolladores en solitario', 'Micro-SaaS', 'Venta de plantillas, libros o cursos de software'],
      avoidIf: ['Comercios fisicos o negocios con margenes de beneficio sumamente estrechos'],
    },
  }),
  defineTech({
    id: 'paddle',
    name: 'Paddle',
    category: 'payments',
    tagline: 'Plataforma de pagos y Merchant of Record especializada en SaaS B2B y B2C a escala global.',
    description: 'Solucion MoR de grado corporativo que combina pasarela de pago, gestion de suscripciones, cumplimiento tributario mundial y prevencion de churn involuntario.',
    website: 'https://www.paddle.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'SaaS MoR',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Comision porcentual fija sobre transacciones sin costos iniciales de alta.' },
    tradeoffs: {
      pros: ['Soporte fiscal y de facturacion corporativa internacional impecable', 'Gestion avanzada de suscripciones y facturas B2B (invoicing)', 'Optimizacion de retencion y recobros automaticos'],
      cons: ['Proceso de aprobacion y KYC mas riguroso para nuevas empresas', 'Menos maleabilidad en la interfaz de checkout que Stripe Elements nativo'],
      sacrifices: ['Sacrificas rapidez de alta inmediata por una estructura fiscal madura para SaaS enterprise.'],
      idealFor: ['Empresas de software SaaS B2B en crecimiento', 'Venta de software descargable de escritorio'],
      avoidIf: ['Venta de bienes fisicos o marketplaces multipartes'],
    },
  }),
  defineTech({
    id: 'mercadopago',
    name: 'Mercado Pago',
    category: 'payments',
    tagline: 'La pasarela de pagos lider y mas extendida en America Latina.',
    description: 'Solucion regional imprescindible para procesar pagos en Argentina, Brasil, Mexico, Colombia, Chile y Uruguay, con soporte para pagos en efectivo locales, transferencias y cuotas con tarjeta.',
    website: 'https://www.mercadopago.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'LatAm Leader',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Sin costo de apertura; comisiones variables por pais y plazo de liberacion del dinero.' },
    tradeoffs: {
      pros: ['Tasas de conversion imbatibles en Latinoamerica gracias a su confianza masiva', 'Soporta metodos de pago locales (Pix en Brasil, Oxxo en Mexico, PSE en Colombia)', 'Opciones de pago en cuotas (con o sin interes)'],
      cons: ['Documentacion y SDKs en ocasiones menos consistentes entre distintas regiones', 'Comisiones por liberacion inmediata de fondos mas elevadas'],
      sacrifices: ['Sacrificas alcance fuera de Latinoamerica.'],
      idealFor: ['Cualquier aplicacion, SaaS o e-commerce que tenga a Latinoamerica como mercado principal'],
      avoidIf: ['Negocios orientados exclusivamente a Norteamerica o Europa'],
    },
  }),
  defineTech({
    id: 'paypal',
    name: 'PayPal',
    category: 'payments',
    tagline: 'Marca de pagos con el mayor reconocimiento de confianza por parte de los consumidores.',
    description: 'Boton de pago rapido y universal que reduce la friccion para millones de compradores que prefieren no introducir los datos de su tarjeta directamente en sitios desconocidos.',
    website: 'https://www.paypal.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Consumer Trust',
    metrics: { dx: 3, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Comision por transaccion estandar mas tarifas por conversion de divisas.' },
    tradeoffs: {
      pros: ['Aumenta las ventas al ofrecer un metodo de pago en el que confian millones de usuarios', 'Pagos ' + 'one-click' + ' a traves del saldo de la cuenta PayPal del usuario', 'Presencia en practicamente cualquier pais del planeta'],
      cons: ['Historico de documentacion fragmentada y APIs de generacion mixta', 'Comisiones por cambio de divisa relativamente altas'],
      sacrifices: ['Sacrificas una experiencia de checkout 100% personalizada en tu propia marca.'],
      idealFor: ['Opcion de pago secundaria o de respaldo junto a Stripe', 'Venta minorista y e-commerce B2C'],
      avoidIf: ['Modelos de suscripcion corporativos complejos que requieren facturacion fiscal detallada'],
    },
  }),
  defineTech({
    id: 'chargebee',
    name: 'Chargebee',
    category: 'payments',
    tagline: 'Motor de facturacion recurrente, gestion de ingresos y suscripciones a nivel de empresa.',
    description: 'Capa de orquestacion que se sitúa por encima de multiples pasarelas de pago (Stripe, Adyen, PayPal) para gestionar planes complejos, cupones, prorrateos y reconocimiento contable de ingresos.',
    website: 'https://www.chargebee.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Billing Engine',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'high', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: 'Plan inicial gratuito hasta los primeros $250,000 USD de facturacion acumulada.' },
    tradeoffs: {
      pros: ['Permite alternar y enrutar pagos entre multiples pasarelas sin rehacer la logica de negocio', 'Herramientas contables avanzadas con cumplimiento de ASC 606 e IFRS 15', 'Gestion sofisticada de retenciones y expiracion de tarjetas'],
      cons: ['Coste elevado una vez se supera la facturacion gratuita inicial', 'Configuracion inicial compleja con cientos de parametros posibles'],
      sacrifices: ['Sacrificas sencillez a cambio de una suite financiera de nivel corporativo.'],
      idealFor: ['Scaleups SaaS con equipos financieros dedicados', 'Modelos hibridos de suscripcion y uso'],
      avoidIf: ['Startups en etapa semilla que solo necesitan un boton de pago basico'],
    },
  }),
  defineTech({
    id: 'braintree',
    name: 'Braintree',
    category: 'payments',
    tagline: 'Pasarela de pagos internacional respaldada por la red y seguridad de PayPal.',
    description: 'Solucion para procesar tarjetas de credito, PayPal, Venmo, Apple Pay y Google Pay con una sola integracion de codigo unificada.',
    website: 'https://www.braintreepayments.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'PayPal Enterprise',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Tarifa estandar de ~2.59% + 49c por transaccion sin costos mensuales de mantenimiento.' },
    tradeoffs: {
      pros: ['Integracion combinada de tarjetas y PayPal en una misma biblioteca de checkout', 'Excelente soporte de tokenizacion y seguridad PCI-DSS', 'Aceptado y respetado por grandes comercios globales (Uber, Airbnb en sus inicios)'],
      cons: ['Menor velocidad de publicacion de features novedosas que Stripe', 'Panel de administracion con diseno mas sobrio y formal'],
      sacrifices: ['Sacrificas la amplitud del ecosistema No-Code de Stripe.'],
      idealFor: ['Comercios que requieren soporte integral de PayPal y tarjetas con un solo contrato', 'Grandes aplicaciones moviles'],
      avoidIf: ['SaaS que buscan automatizar declaraciones fiscales internacionales completas sin esfuerzo'],
    },
  }),
  defineTech({
    id: 'dodo-payments',
    name: 'Dodo Payments',
    category: 'payments',
    tagline: 'Merchant of Record developer-first para productos digitales y herramientas de IA.',
    description: 'Plataforma MoR moderna disenada especificamente para startups de inteligencia artificial y software digital, con checkout integrado, cobro de impuestos mundiales y payouts internacionales rapidos.',
    website: 'https://dodopayments.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'AI MoR',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 3, community: 3, maturity: 3, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Comisiones competitivas sin costos mensuales de suscripcion.' },
    tradeoffs: {
      pros: ['Enfoque nativo en modelos de uso por tokens y micropagos de IA', 'API extremadamente directa y amigable para desarrolladores de TypeScript y Python', 'Soporte fiscal y de facturacion global'],
      cons: ['Compania mas joven en el sector con menor historial que Stripe o Paddle', 'Ecosistema de plugins para CMS tradicionales en desarrollo'],
      sacrifices: ['Sacrificas la trayectoria decenal de pasarelas tradicionales a cambio de innovacion y trato directo.'],
      idealFor: ['Wrappers de IA', 'Herramientas SaaS modernas', 'Desarrolladores independientes que monetizan proyectos rapidos'],
      avoidIf: ['Empresas multinacionales con contratos de compras corporativas rigidos'],
    },
  }),
  defineTech({
    id: 'mollie',
    name: 'Mollie',
    category: 'payments',
    tagline: 'Especialista en pagos y metodos locales para el mercado de la Union Europea.',
    description: 'Pasarela europea con soporte impecable para iDEAL, Bancontact, Sofort, SEPA, Cartes Bancaires y tarjetas de credito, con panel de control intuitivo y onboarding veloz.',
    website: 'https://www.mollie.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'European Payments',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Pagas solo por transaccion con tarifas reducidas para transferencias locales como iDEAL.' },
    tradeoffs: {
      pros: ['Conversion sobresaliente en Europa continental gracias a metodos de transferencia directa', 'Proceso de activacion y verificacion transparente y rapido', 'Tarifas muy competitivas en pagos locales SEPA e iDEAL'],
      cons: ['Menor presencia y penetracion fuera de la Union Europea y Reino Unido', 'Menos funcionalidades avanzadas de facturacion B2B compleja'],
      sacrifices: ['Sacrificas cobertura nativa en Asia o Latinoamerica.'],
      idealFor: ['E-commerce y servicios enfocados en consumidores europeos', 'Startups en Paises Bajos, Belgica, Alemania y Francia'],
      avoidIf: ['Negocios con mercado primario en Norteamerica o America Latina'],
    },
  }),
  defineTech({
    id: 'adyen',
    name: 'Adyen',
    category: 'payments',
    tagline: 'Motor de pagos omnicanal de grado corporativo a nivel mundial.',
    description: 'Plataforma integral utilizada por las mayores multinacionales (Spotify, Microsoft, Uber) que unifica pagos online, en tiendas fisicas (TPV/POS) y en aplicaciones moviles en una sola cuenta.',
    website: 'https://www.adyen.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Global Omnichannel',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 4 },
    cost: { initialCost: 'medium', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: false, limitsDescription: 'Tarifa fija por transaccion mas comision de intercambio (modelo interchange++).' },
    tradeoffs: {
      pros: ['Conexion directa con las redes de tarjetas sin intermediarios, lo que maximiza la autorizacion', 'Unificacion total de pagos digitales y terminales fisicos de punto de venta', 'Tarifas altamente eficientes a volumenes de decenas de millones mensuales'],
      cons: ['Requisitos minimos de volumen de transaccion para ser admitido como cliente', 'Proceso de integracion y certificacion prolongado'],
      sacrifices: ['Sacrificas accesibilidad inmediata para proyectos pequenos a cambio de ventajas a mega-escala.'],
      idealFor: ['Grandes empresas consolidadas', 'Marcas globales con tiendas fisicas y online unificadas', 'Hipervolumenes'],
      avoidIf: ['Startups tempranas, proyectos independientes o facturacion inferior a $50k/mes'],
    },
  }),
];
