import type { Technology } from '../types';
import { defineTech } from './builder';

export const QUEUES_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'bullmq',
    name: 'BullMQ',
    category: 'queues',
    tagline: 'La biblioteca de colas de mensajes en TypeScript para Node.js mas rapida y robusta, basada en Redis.',
    description: 'Gestiona tareas en segundo plano, trabajos programados repetitivos (cron), reintentos con retraso exponencial, limitacion de tasa (rate limiting) y priorizacion con alto rendimiento sobre Redis.',
    website: 'https://bullmq.io/',
    license: 'MIT',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Node.js Standard',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito sobre cualquier instancia de Redis.' },
    tradeoffs: {
      pros: ['Diseno nativo en TypeScript con tipado riguroso de payloads y resultados', 'Soporta tareas padre/hijo complejas (flows) y distribucion equilibrada de carga entre workers', 'Extremadamente veloz al aprovechar las operaciones atomicas en memoria de Redis'],
      cons: ['Requiere mantener una instancia o cluster de Redis activo en todo momento', 'No disenado para entornos puramente serverless donde no hay procesos trabajadores de larga duracion'],
      sacrifices: ['Sacrificas compatibilidad serverless pura a favor de rendimiento por segundo insuperable en workers dedicados.'],
      idealFor: ['Aplicaciones Node.js, Express y NestJS', 'Envio de correos masivos y generacion de reportes PDF en background', 'Web scraping'],
      avoidIf: ['Entornos de serverless functions efimeras sin instancias de workers permanentes'],
    },
  }),
  defineTech({
    id: 'upstash-qstash',
    name: 'Upstash QStash',
    category: 'queues',
    tagline: 'Colas de mensajes serverless con invocacion HTTP disenadas para Edge y Vercel.',
    description: 'Sistema de mensajeria y programador de tareas que no requiere mantener ningun worker encendido: recibe tu mensaje y realiza una peticion HTTP al endpoint de tu API en el momento programado.',
    website: 'https://upstash.com/docs/qstash/overall/getstarted',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Serverless Queues',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '500 mensajes gratuitos al dia en el plan libre de Upstash.' },
    tradeoffs: {
      pros: ['Resuelve por completo el problema de ejecutar colas en Vercel, Next.js y Cloudflare Workers', 'Cero servidores o procesos worker que mantener encendidos 24/7', 'Firma criptografica automatica de mensajes para verificar la autenticidad de las peticiones recibidas'],
      cons: ['Las tareas deben poder completarse dentro de los limites de tiempo maximo de peticion HTTP del endpoint receptor', 'Dependencia del servicio en la nube de Upstash'],
      sacrifices: ['Sacrificas procesamiento de tareas de varias horas de duracion a cambio de integracion serverless perfecta.'],
      idealFor: ['Next.js y serverless stacks', 'Tareas diferidas (enviar un correo 30 minutos despues del registro)', 'Webhooks fiables'],
      avoidIf: ['Transcodificacion de video pesada que requiere horas de CPU ininterrumpida'],
    },
  }),
  defineTech({
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'queues',
    tagline: 'El broker de mensajes de codigo abierto mas extendido del mundo (soporte AMQP y MQTT).',
    description: 'Intermediario de mensajeria altamente fiable y versatil que ofrece enrutamiento complejo mediante intercambios (direct, topic, fanout, headers) y garantias estrictas de entrega.',
    website: 'https://www.rabbitmq.com/',
    license: 'MPL-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'AMQP Standard',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% software libre y gratuito para desplegar en cualquier infraestructura.' },
    tradeoffs: {
      pros: ['Flexibilidad de enrutamiento inigualable para arquitecturas desacopladas y políglotas', 'Garantias solidas de confirmacion de entrega (ACKs) y manejo de mensajes no procesables (Dead Letter Queues)', 'Panel web de gestion intuitivo y completo para monitorizar colas y tasas de trafico'],
      cons: ['Menos optimizado para streaming masivo de gigabytes por segundo en comparacion con Kafka', 'Requiere comprension detallada de conceptos de enrutamiento AMQP para disenar arquitecturas limpias'],
      sacrifices: ['Sacrificas almacenamiento historico indefinido de mensajes a cambio de enrutamiento inteligente en tiempo real.'],
      idealFor: ['Microservicios políglotas (mezcla de Java, Go, Node y Python)', 'Comandos y eventos transaccionales empresariales'],
      avoidIf: ['Sistemas de big data con procesamiento de eventos a escala de terabytes continuos'],
    },
  }),
  defineTech({
    id: 'aws-sqs',
    name: 'AWS SQS',
    category: 'queues',
    tagline: 'Servicio de colas de mensajes totalmente gestionado, escalable y fiable en AWS.',
    description: 'Amazon Simple Queue Service permite desacoplar microservicios, sistemas distribuidos y aplicaciones serverless con colas estandar de rendimiento casi ilimitado y colas FIFO de orden estricto.',
    website: 'https://aws.amazon.com/sqs/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'AWS Standard',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '1 millon de solicitudes gratuitas al mes para siempre en AWS Free Tier.' },
    tradeoffs: {
      pros: ['Escala automaticamente de forma infinita sin requerir ningun ajuste manual de capacidad', 'Integracion nativa directa con AWS Lambda para procesamiento serverless automatico', 'Cero administracion de parches, servidores o software'],
      cons: ['Las colas estandar no garantizan orden estricto de mensajes (requiere colas FIFO con menor limite de transacciones)', 'Retrasos ocasionales de pocos segundos en entrega de mensajes frente a brokers en memoria'],
      sacrifices: ['Sacrificas milisegundos de latencia a favor de resiliencia infinita y mantenimiento nulo.'],
      idealFor: ['Arquitecturas nativas en AWS', 'Eventos asincronos desacoplados', 'Picos masivos e imprevistos de mensajes'],
      avoidIf: ['Sistemas que requieren mensajeria de latencia sub-milisegundo o desarrollo 100% independiente de la nube'],
    },
  }),
  defineTech({
    id: 'kafka',
    name: 'Apache Kafka',
    category: 'queues',
    tagline: 'Plataforma de transmision de eventos distribuida de alto rendimiento y durabilidad.',
    description: 'El estandar de la industria para streaming de eventos en tiempo real: almacena streams de registros en un log inmutable distribuido, permitiendo reproducir datos historicos a velocidades colosales.',
    website: 'https://kafka.apache.org/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Event Streaming',
    metrics: { dx: 3, learningCurve: 4, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 5, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito (opciones gestionadas como Confluent Cloud o Upstash Kafka).' },
    tradeoffs: {
      pros: ['Rendimiento masivo capaz de procesar millones de eventos por segundo con durabilidad garantizada', 'Capacidad de retener y reproducir mensajes pasados (event sourcing y analytics)', 'Ecosistema inmenso de conectores con Kafka Connect y procesamiento con Kafka Streams'],
      cons: ['Complejidad operativa formidable para desplegar y mantener clusters en produccion sin un proveedor gestionado', 'Concepto diferente a una cola de mensajes tradicional (el consumidor gestiona sus offsets)'],
      sacrifices: ['Sacrificas simplicidad operativa a cambio del motor de eventos mas potente jamas disenado.'],
      idealFor: ['Empresas con ingestion masiva de telemetria, clickstreams y analitica en tiempo real', 'Bancos y auditoria financiera'],
      avoidIf: ['Simple cola de envios de emails de bienvenida de una aplicacion web estandar'],
    },
  }),
  defineTech({
    id: 'nats',
    name: 'NATS',
    category: 'queues',
    tagline: 'Sistema de mensajeria cloud-native ultraligero y de alta velocidad para microservicios y Edge.',
    description: 'Broker de comunicacion escrito en Go con huella de recursos microscopica, soporte de mensajeria Publish-Subscribe ultrarrapida y persistencia duradera con NATS JetStream.',
    website: 'https://nats.io/',
    license: 'Apache-2.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Cloud Native',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% software libre de la Cloud Native Computing Foundation (CNCF).' },
    tradeoffs: {
      pros: ['Consumo ridiculo de memoria (un binario de pocos megabytes) y latencias inferiores a un milisegundo', 'Topologias globales multirregion con ' + 'superclusters' + ' de configuracion trivial', 'JetStream combina la agilidad de NATS con colas persistentes y deduplicacion'],
      cons: ['Comunidad general mas pequena que la de Redis o Kafka', 'Menos bibliotecas de integracion prefabricadas para frameworks legacy'],
      sacrifices: ['Sacrificas la ubicuidad absoluta de Redis a favor de un diseno de red nativo y ultraligero.'],
      idealFor: ['Microservicios modernos en Go, Rust o Node', 'Internet de las cosas (IoT) y computacion Edge', 'Comunicacion interna entre pods'],
      avoidIf: ['Equipos que unicamente conocen y tienen infraestructura basada en Redis'],
    },
  }),
  defineTech({
    id: 'inngest',
    name: 'Inngest',
    category: 'queues',
    tagline: 'Colas en segundo plano, tareas programadas y workflows sin infraestructura para TypeScript.',
    description: 'Permite escribir funciones en segundo plano duraderas con reintentos automaticos, esperas de tiempo (sleep), limitacion de concurrencia y orquestacion paso a paso directamente en tu aplicacion web.',
    website: 'https://www.inngest.com/',
    license: 'Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Durable Workflows',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Plan gratuito generoso para desarrolladores sin tarjeta de credito.' },
    tradeoffs: {
      pros: ['Escribe funciones en segundo plano complejas que pueden pausarse dias sin requerir servidores workers activos', 'Funciona sin fisuras en Vercel, Next.js, Remix y cualquier servidor tradicional', 'Dev Server local interactivo con una interfaz visual excelente para depurar pasos y reintentos'],
      cons: ['Modelo mental de ejecucion durable paso a paso que requiere comprender como se retoman los pasos', 'Servicio cloud gestionado para la coordinacion de estados en produccion (o self-hosted de su core)'],
      sacrifices: ['Sacrificas brokers tradicionales a cambio de una experiencia de desarrollo de flujos increiblemente productiva.'],
      idealFor: ['SaaS moderno con TypeScript', 'Automatizaciones complejas de onboarding o recordatorios programados', 'Procesos con pasos dependientes'],
      avoidIf: ['Sistemas en C++ o entornos industriales desconectados de internet'],
    },
  }),
  defineTech({
    id: 'temporal',
    name: 'Temporal',
    category: 'queues',
    tagline: 'Plataforma de ejecucion durable para orquestar workflows criticos y tolerantes a fallos.',
    description: 'Garantiza que el codigo de tus flujos de trabajo se ejecute con fiabilidad matematica sin importar que los servidores se caigan, se reinicien o la red falle en mitad del proceso.',
    website: 'https://temporal.io/',
    license: 'MIT',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'Mission Critical',
    metrics: { dx: 4, learningCurve: 4, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto para self-hosting o Temporal Cloud gestionado.' },
    tradeoffs: {
      pros: ['Fiabilidad absoluta para flujos de transacciones financieras o provision de infraestructura critica', 'Elimina para siempre la logica defensiva de reintentos fragmentados, timers y deadlocks en bases de datos', 'SDKs maduros para TypeScript, Go, Java y Python'],
      cons: ['Curva de aprendizaje exigente: el codigo de los workflows debe ser estrictamente determinista', 'Operar el cluster de Temporal en servidores propios exige Cassandra o PostgreSQL bien optimizados'],
      sacrifices: ['Sacrificas rapidez informal de programacion a cambio de garantia matematicamente infalible de ejecucion.'],
      idealFor: ['Pasarelas de pago y orquestacion bancaria', 'Sistemas de pedidos en e-commerce complejo', 'Provisionamiento de maquinas en la nube'],
      avoidIf: ['Simples tareas de envio de un email o procesos donde un fallo es irrelevante'],
    },
  }),
  defineTech({
    id: 'celery',
    name: 'Celery',
    category: 'queues',
    tagline: 'La cola de tareas asincronas distribuida estandar para el ecosistema Python.',
    description: 'La biblioteca de background processing mas utilizada en Python y Django, con soporte para brokers como RabbitMQ o Redis, programacion periodica con Celery Beat y ejecucion concurrente.',
    website: 'https://docs.celeryq.dev/',
    license: 'BSD-3-Clause',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Python Standard',
    metrics: { dx: 4, learningCurve: 3, scalability: 4, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 3, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito sin restricciones.' },
    tradeoffs: {
      pros: ['Estandar indiscutible en el ecosistema Django y FastAPI con mas de una decada de madurez', 'Amplia comunidad con respuestas documentadas para practicamente cualquier duda', 'Soporta tareas periodicas, cadenas de ejecucion y tareas concurrentes en hilos o procesos'],
      cons: ['Configuracion de serializadores y opciones de conexion que puede resultar laberintica', 'Depurar fugas de memoria en workers de Python de larga duracion requiere monitorizacion con Flower'],
      sacrifices: ['Sacrificas ergonomia moderna a favor de integracion perfecta con Python tradicional.'],
      idealFor: ['Aplicaciones Django, Flask o FastAPI', 'Modelos de Machine Learning ejecutados en segundo plano', 'Pipelines de scraping en Python'],
      avoidIf: ['Equipos con stack 100% basado en TypeScript o JavaScript donde BullMQ o Inngest son superiores'],
    },
  }),
  defineTech({
    id: 'sidekiq',
    name: 'Sidekiq',
    category: 'queues',
    tagline: 'Procesamiento en segundo plano simple y sumamente eficiente para Ruby on Rails.',
    description: 'Procesa cientos de miles de tareas por segundo utilizando hilos concurrentes en lugar de procesos pesados sobre Redis, considerado un pilar indiscutible del ecosistema Rails.',
    website: 'https://sidekiq.org/',
    license: 'LGPL-3.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Ruby on Rails Standard',
    metrics: { dx: 5, learningCurve: 1, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: 'Version comunitaria de codigo abierto 100% gratuita para produccion.' },
    tradeoffs: {
      pros: ['Eficiencia de memoria insuperable en Ruby gracias a su arquitectura multihilo', 'Integracion perfecta con ActiveJob de Ruby on Rails', 'Dashboard web interactivo claro para inspeccionar colas, reintentos y fallos'],
      cons: ['Exclusivo del ecosistema de Ruby', 'Algunas funciones avanzadas (como lotes de tareas o periodicidad fina) estan reservadas a la version comercial Sidekiq Pro'],
      sacrifices: ['Sacrificas versatilidad políglota por la maxima excelencia dentro del mundo Ruby.'],
      idealFor: ['Cualquier aplicacion moderna construida con Ruby on Rails'],
      avoidIf: ['Cualquier stack no basado en el lenguaje Ruby'],
    },
  }),
];
