import type { Technology } from '../types';
import { defineTech } from './builder';

export const STORAGE_TECHNOLOGIES: Technology[] = [
  defineTech({
    id: 'cloudflare-r2',
    name: 'Cloudflare R2',
    category: 'storage',
    tagline: 'Almacenamiento de objetos compatible con S3 sin costos por transferencia de salida (egress).',
    description: 'Object storage distribuido a nivel global en la red Edge de Cloudflare, disenado para eliminar las tarifas abusivas de egress y facilitar migraciones directas desde AWS S3.',
    website: 'https://www.cloudflare.com/developer-platform/r2/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Zero Egress Fees',
    metrics: { dx: 5, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 4, operationalComplexity: 1, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '10 GB/mes de almacenamiento y millones de operaciones de lectura/escritura gratis.' },
    tradeoffs: {
      pros: ['Zero costos de transferencia de salida (egress fees)', 'API compatible con AWS S3', 'Integracion nativa con Cloudflare Workers'],
      cons: ['Menor cantidad de features complejas comparado con AWS S3 tradicional', 'Ecosistema de plugins especificos aun en expansion'],
      sacrifices: ['Sacrificas ecosistema de politicas complejas de AWS IAM.'],
      idealFor: ['SaaS moderno de medios', 'Descargas masivas de archivos', 'Archivos de backups y multimedia'],
      avoidIf: ['Infraestructura 100% atada a politicas de cumplimiento avanzadas exclusivas de AWS'],
    },
  }),
  defineTech({
    id: 'aws-s3',
    name: 'AWS S3',
    category: 'storage',
    tagline: 'El estandar de la industria para almacenamiento de objetos cloud de alta durabilidad.',
    description: 'Amazon Simple Storage Service ofrece durabilidad del 99.999999999% (11 9s), clases de almacenamiento por niveles (Glacier, Intelligent-Tiering) y politicas de seguridad granulares.',
    website: 'https://aws.amazon.com/s3/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Cloud Standard',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'high', hasFreeTier: true, limitsDescription: '5 GB de almacenamiento estandar durante 12 meses en AWS Free Tier.' },
    tradeoffs: {
      pros: ['Durabilidad insuperable y resiliencia probada en produccion global', 'Ecosistema de integraciones masivo con cualquier herramienta', 'Clases de almacenamiento inteligente y archivado economico'],
      cons: ['Tarifas de egress bandwidth potencialmente muy costosas a gran escala', 'Consola y configuracion de politicas IAM complejas'],
      sacrifices: ['Sacrificas previsibilidad de facturacion si no monitoreas el trafico de salida.'],
      idealFor: ['Grandes empresas', 'Data lakes', 'Backups criticos y cumplimiento normativo'],
      avoidIf: ['Proyectos con presupuesto limitado que distribuyen terabytes de contenido multimedia directamente'],
    },
  }),
  defineTech({
    id: 'supabase-storage',
    name: 'Supabase Storage',
    category: 'storage',
    tagline: 'Almacenamiento de archivos con seguridad basada en Row Level Security (RLS) de Postgres.',
    description: 'Servicio de almacenamiento compatible con S3 integrado nativamente con la base de datos Supabase, transformacion de imagenes al vuelo y politicas de control de acceso directas en SQL.',
    website: 'https://supabase.com/storage',
    license: 'Apache-2.0',
    isManaged: true,
    isOpenSource: true,
    badgeText: 'RLS Native',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 5, maturity: 4, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '1 GB de almacenamiento y 2 GB de ancho de banda gratis al mes.' },
    tradeoffs: {
      pros: ['Control de acceso a archivos mediante politicas SQL RLS familiares', 'Transformacion de imagenes al vuelo integrada', 'SDK cliente unificado para auth y storage'],
      cons: ['Vinculado principalmente al ecosistema de proyectos Supabase', 'Llego mas recientemente que S3 para workloads petabyte-scale'],
      sacrifices: ['Sacrificas independencia si decides migrar tu base de datos fuera de Supabase.'],
      idealFor: ['Aplicaciones fullstack con Supabase', 'Avatares, documentos de usuarios protegidos por login'],
      avoidIf: ['Arquitecturas desacopladas sin Postgres o necesidades de streaming a hiperescala'],
    },
  }),
  defineTech({
    id: 'uploadthing',
    name: 'UploadThing',
    category: 'storage',
    tagline: 'Subida de archivos con seguridad tipada de extremo a extremo para React y Next.js.',
    description: 'Capa de subida de archivos orientada al desarrollador frontend, que maneja rutas de subida, validacion de esquemas tipados y almacenamiento backend con maxima ergonomia.',
    website: 'https://uploadthing.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Type-Safe Uploads',
    metrics: { dx: 5, learningCurve: 1, scalability: 4, ecosystem: 4, community: 4, maturity: 3, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '2 GB de almacenamiento gratuito y 500 subidas al mes.' },
    tradeoffs: {
      pros: ['Configuracion minima en minutos con hooks de React', 'Seguridad y tipos TypeScript end-to-end', 'Sin lidiar con presigned URLs de bajo nivel'],
      cons: ['Vendor lock-in moderado a la plataforma de UploadThing', 'No optimizado para storage empresarial no centrado en la web'],
      sacrifices: ['Sacrificas control granular de infraestructura de almacenamiento subyacente.'],
      idealFor: ['Next.js apps', 'Startups que necesitan subida de archivos rapida y segura'],
      avoidIf: ['Sistemas backend sin TypeScript o pipelines de ingestion de datos masivos'],
    },
  }),
  defineTech({
    id: 'cloudinary',
    name: 'Cloudinary',
    category: 'storage',
    tagline: 'Plataforma integral de gestion, optimizacion y transformacion de medios visuales.',
    description: 'Solucion lider para hosting, optimizacion dinamica automatica (f_auto, q_auto) y transformacion de imagenes y videos a traves de parametros en URLs de CDN.',
    website: 'https://cloudinary.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Media Optimization',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 4, maturity: 5, operationalComplexity: 1, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'high', hasFreeTier: true, limitsDescription: '25 creditos mensuales gratuitos (~25,000 transformaciones o 25 GB net).' },
    tradeoffs: {
      pros: ['Optimizacion automatica de imagenes para WebP/AVIF con maxima reduccion de peso', 'Potente motor de edicion, recorte inteligente con IA y marcas de agua en URL', 'CDN global de entrega rapida'],
      cons: ['Facturacion por creditos que puede volverse confusa y costosa al escalar', 'Vendor lock-in significativo en sintaxis de URLs'],
      sacrifices: ['Sacrificas costes bajos a cambio de automatizacion total de pipelines multimedia.'],
      idealFor: ['E-commerce', 'Portales de medios', 'Plataformas de moda o fotografia'],
      avoidIf: ['Almacenamiento generico de documentos crudos o presupuestos fijos estrictos'],
    },
  }),
  defineTech({
    id: 'backblaze',
    name: 'Backblaze B2',
    category: 'storage',
    tagline: 'Almacenamiento de objetos S3 ultrabarato con integracion Cloudflare Bandwidth Alliance.',
    description: 'Almacenamiento de datos compatible con S3 que ofrece un coste por GB significativamente inferior a AWS S3 y transferencia gratuita a traves de la red de Cloudflare.',
    website: 'https://www.backblaze.com/b2/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Low Cost S3',
    metrics: { dx: 4, learningCurve: 2, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 2, vendorLockin: 2 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '10 GB de almacenamiento gratis y 1 GB diario de descarga libre.' },
    tradeoffs: {
      pros: ['Coste de almacenamiento base una fraccion de AWS S3', 'Integracion con Cloudflare para transferencia de salida sin costo', 'API compatible con herramientas estandar de S3'],
      cons: ['Menor catalogo de herramientas complementarias que AWS o Azure', 'Latencias de primer byte ligeramente superiores en regiones unicas'],
      sacrifices: ['Sacrificas opciones de procesamiento computacional dentro de la misma red cloud.'],
      idealFor: ['Backups de gran volumen', 'Archivos de medios a largo plazo', 'Startups conscientes del coste'],
      avoidIf: ['Requerimiento estricto de multirregion sincronizada a nivel de milisegundos'],
    },
  }),
  defineTech({
    id: 'imagekit',
    name: 'ImageKit',
    category: 'storage',
    tagline: 'Optimizacion de imagenes y entrega por CDN en tiempo real con DAM integrado.',
    description: 'Servicio de entrega de imagenes con optimizacion automatica de formato, transformaciones visuales, compresion inteligente y almacenamiento de activos digitales.',
    website: 'https://imagekit.io/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Realtime CDN',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 4, community: 3, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'low', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '20 GB de ancho de banda gratuito mensual y almacenamiento generoso.' },
    tradeoffs: {
      pros: ['Alternativa accesible y moderna a Cloudinary', 'Conexion directa con tus propios buckets S3 o Google Cloud Storage', 'CDN global de 6 continentes de serie'],
      cons: ['Menos herramientas complejas de video que los gigantes del sector', 'Soporte empresarial restringido a planes superiores'],
      sacrifices: ['Sacrificas soporte avanzado de video codecs complejos.'],
      idealFor: ['SaaS blogs', 'Marketplaces con catalogos de productos', 'Apps moviles ricas en imagenes'],
      avoidIf: ['Streaming de video en directo o almacenamiento de datos planos'],
    },
  }),
  defineTech({
    id: 'uploadcare',
    name: 'Uploadcare',
    category: 'storage',
    tagline: 'Widget de subida universal, pipeline de procesamiento y CDN global.',
    description: 'Plataforma completa de carga de archivos que incluye un widget de seleccion desde redes sociales y almacenamiento en la nube, procesamiento de imagenes y CDN ultrarrapido.',
    website: 'https://uploadcare.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Universal Widget',
    metrics: { dx: 5, learningCurve: 2, scalability: 4, ecosystem: 3, community: 3, maturity: 4, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '3,000 subidas al mes y 30 GB de trafico en el plan comunitario.' },
    tradeoffs: {
      pros: ['Widget de subida ' + 'drop-in' + ' con soporte para camaras, Drive, Dropbox e Instagram', 'Procesamiento automatico y red CDN global', 'Facil implementacion sin codigo de backend'],
      cons: ['Coste por operacion mas alto que proveedores de almacenamiento crudo', 'Personalizacion de la interfaz del widget con ciertas limitaciones'],
      sacrifices: ['Sacrificas flexibilidad de pipeline interno a cambio de velocidad de implementacion.'],
      idealFor: ['Formularios con recepcion de CVs, fotos o documentos', 'Proyectos no-code y low-code'],
      avoidIf: ['Cargas internas server-to-server masivas'],
    },
  }),
  defineTech({
    id: 'filestack',
    name: 'Filestack',
    category: 'storage',
    tagline: 'API de subida de archivos, transformaciones y OCR para aplicaciones web.',
    description: 'API y picker modular de subida de archivos con deteccion de virus, OCR para documentos y procesamiento de documentos e imagenes.',
    website: 'https://www.filestack.com/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'File API',
    metrics: { dx: 4, learningCurve: 2, scalability: 4, ecosystem: 3, community: 3, maturity: 5, operationalComplexity: 1, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'medium', hasFreeTier: true, limitsDescription: '500 subidas y 1 GB de ancho de banda gratuito al mes.' },
    tradeoffs: {
      pros: ['Capacidades avanzadas como conversion de documentos y OCR', 'Integracion veloz con bibliotecas cliente', 'Analisis de seguridad y virus integrado'],
      cons: ['Planes de pago con saltos de precio pronunciados', 'Interfaz de administracion algo envejecida'],
      sacrifices: ['Sacrificas economia de escala a gran volumen.'],
      idealFor: ['Plataformas legales o de recursos humanos que procesan PDFs y documentos'],
      avoidIf: ['Infraestructuras que requieren control total de soberania de datos en servidores propios'],
    },
  }),
  defineTech({
    id: 'minio',
    name: 'MinIO',
    category: 'storage',
    tagline: 'Almacenamiento de objetos compatible con S3 de alto rendimiento para self-hosting.',
    description: 'Servidor de almacenamiento de objetos escrito en Go de codigo abierto compatible con S3, ideal para nubes privadas, Kubernetes y centros de datos propios.',
    website: 'https://min.io/',
    license: 'AGPL-3.0',
    isManaged: false,
    isOpenSource: true,
    badgeText: 'Self-Hosted S3',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 4, community: 5, maturity: 5, operationalComplexity: 4, vendorLockin: 1 },
    cost: { initialCost: 'free', operationalCost: 'free', scalingRisk: 'low', hasFreeTier: true, limitsDescription: '100% de codigo abierto y gratuito para self-hosting.' },
    tradeoffs: {
      pros: ['Compatible al 100% con la API de AWS S3', 'Rendimiento sobresaliente en hardware local o clusters Kubernetes', 'Soberania absoluta de datos y cumplimiento RGPD estricto'],
      cons: ['Licencia AGPL-3.0 que requiere atencion en distribuciones comerciales', 'Responsabilidad completa del mantenimiento de discos, replicacion y backups'],
      sacrifices: ['Sacrificas la conveniencia de la gestion delegada de una nube publica.'],
      idealFor: ['Infraestructura on-premise', 'Bancos, sanidad o entornos con estricta soberania de datos', 'Clusters Kubernetes'],
      avoidIf: ['Equipos sin ingenieros de infraestructura dedicados'],
    },
  }),
  defineTech({
    id: 'gcs',
    name: 'Google Cloud Storage',
    category: 'storage',
    tagline: 'Almacenamiento unificado de objetos con consistencia fuertemente garantizada.',
    description: 'Servicio de almacenamiento de Google Cloud con replicacion global multirregion, consistencia fuerte e integracion con BigQuery y Vertex AI.',
    website: 'https://cloud.google.com/storage',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Google Cloud',
    metrics: { dx: 4, learningCurve: 3, scalability: 5, ecosystem: 5, community: 5, maturity: 5, operationalComplexity: 2, vendorLockin: 3 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'high', hasFreeTier: true, limitsDescription: '5 GB de almacenamiento estandar al mes en el Free Tier de GCP.' },
    tradeoffs: {
      pros: ['Consistencia fuerte inmediata para operaciones de lectura tras escritura', 'Integracion sin fisuras con analitica en BigQuery y modelos de IA en GCP', 'Excelente infraestructura de red troncal global'],
      cons: ['Costos de transferencia de red (egress) a otras nubes', 'Consola Cloud de Google con curva de aprendizaje pronunciada'],
      sacrifices: ['Sacrificas simplicidad operativa si solo necesitas un bucket aislado.'],
      idealFor: ['Pipelines de datos y machine learning en GCP', 'Empresas que aprovechan el ecosistema de Google Cloud'],
      avoidIf: ['Desarrollo web rapido sin dependencias del ecosistema de Google'],
    },
  }),
  defineTech({
    id: 'azure-blob',
    name: 'Azure Blob Storage',
    category: 'storage',
    tagline: 'Almacenamiento de objetos masivo y altamente seguro para cargas empresariales.',
    description: 'Solucion de almacenamiento masivo no estructurado de Microsoft Azure, con niveles de acceso caliente, frio y archivo, y compatibilidad con Azure Active Directory.',
    website: 'https://azure.microsoft.com/products/storage/blobs/',
    license: 'Proprietary',
    isManaged: true,
    isOpenSource: false,
    badgeText: 'Azure Enterprise',
    metrics: { dx: 3, learningCurve: 3, scalability: 5, ecosystem: 4, community: 4, maturity: 5, operationalComplexity: 3, vendorLockin: 4 },
    cost: { initialCost: 'free', operationalCost: 'medium', scalingRisk: 'high', hasFreeTier: true, limitsDescription: '5 GB de almacenamiento LRS durante 12 meses en Azure Free Account.' },
    tradeoffs: {
      pros: ['Integracion corporativa de primer nivel con Active Directory / Entra ID', 'Soporte nativo para sistemas de archivos distribuidos Data Lake Storage Gen2', 'Altos estandares de cumplimiento corporativo y bancario'],
      cons: ['Ecosistema de SDKs menos intuitivo en TypeScript en comparacion con AWS o Cloudflare', 'Complejidad en gestion de suscripciones y recursos de Azure'],
      sacrifices: ['Sacrificas rapidez de prototipado frente a soluciones developer-first.'],
      idealFor: ['Grandes corporaciones', 'Entornos Microsoft .NET empresariales', 'Data lakes analiticos'],
      avoidIf: ['Startups agiles o desarrollos JAMstack independientes'],
    },
  }),
];
