import type { StackRecommendation } from '../engine/types';
import { TECH_BY_ID } from '../engine/catalog';

export function generateMermaidDiagram(recommendation: StackRecommendation): string {
  const { slots } = recommendation;

  const frontend = slots.frontend ? TECH_BY_ID[slots.frontend] : null;
  const backend = slots.backend ? TECH_BY_ID[slots.backend] : null;
  const database = slots.database ? TECH_BY_ID[slots.database] : null;
  const auth = slots.auth ? TECH_BY_ID[slots.auth] : null;
  const storage = slots.storage ? TECH_BY_ID[slots.storage] : null;
  const hosting = slots.hosting ? TECH_BY_ID[slots.hosting] : null;
  const payments = slots.payments ? TECH_BY_ID[slots.payments] : null;
  const email = slots.email ? TECH_BY_ID[slots.email] : null;
  const monitoring = slots.monitoring ? TECH_BY_ID[slots.monitoring] : null;
  const cicd = slots.cicd ? TECH_BY_ID[slots.cicd] : null;

  const lines: string[] = [
    'flowchart TD',
    '    %% Generated by StackForge (Tech Stack Architect)',
    '    classDef clientLayer fill:#1E293B,stroke:#38BDF8,stroke-width:2px,color:#F8FAFC;',
    '    classDef appLayer fill:#0F172A,stroke:#60A5FA,stroke-width:2px,color:#F8FAFC;',
    '    classDef dataLayer fill:#0B132B,stroke:#10B981,stroke-width:2px,color:#F8FAFC;',
    '    classDef serviceLayer fill:#1C1917,stroke:#F59E0B,stroke-width:2px,color:#F8FAFC;',
    '    classDef infraLayer fill:#18181B,stroke:#A855F7,stroke-width:2px,color:#F8FAFC;',
    '',
    '    subgraph Clients["1. Ingress & Clients"]',
  ];

  if (frontend) {
    lines.push(`        Client["📱/💻 ${frontend.name} (Client)"]:::clientLayer`);
  }
  lines.push('    end', '', '    subgraph Application["2. Application & API"]');

  if (backend) {
    lines.push(`        API["⚙️ ${backend.name} (API Server)"]:::appLayer`);
  } else if (frontend) {
    lines.push(`        API["⚡ ${frontend.name} Route Handlers (Serverless)"]:::appLayer`);
  }
  lines.push('    end', '', '    subgraph DataState["3. Data & State Layer"]');

  if (database) {
    lines.push(`        DB[("🗄️ ${database.name}")]:::dataLayer`);
  }
  if (storage) {
    lines.push(`        Storage["📦 ${storage.name}"]:::dataLayer`);
  }
  lines.push('    end', '', '    subgraph ThirdParty["4. Services & Auth"]');

  if (auth) {
    lines.push(`        Auth["🔑 ${auth.name}"]:::serviceLayer`);
  }
  if (payments) {
    lines.push(`        Payments["💳 ${payments.name}"]:::serviceLayer`);
  }
  if (email) {
    lines.push(`        Email["✉️ ${email.name}"]:::serviceLayer`);
  }
  lines.push('    end', '', '    subgraph InfraOps["5. Hosting & Ops"]');

  if (hosting) {
    lines.push(`        Host["☁️ ${hosting.name}"]:::infraLayer`);
  }
  if (monitoring) {
    lines.push(`        Observability["📊 ${monitoring.name}"]:::infraLayer`);
  }
  if (cicd) {
    lines.push(`        CI["🚀 ${cicd.name}"]:::infraLayer`);
  }
  lines.push('    end', '');

  // Conexiones
  lines.push('    Client -->|HTTPS / JSON| API');
  if (database) lines.push('    API -->|Queries / Pool| DB');
  if (auth) lines.push('    API -->|Session / Tokens| Auth');
  if (storage) lines.push('    API -->|Assets / Presigned| Storage');
  if (payments) lines.push('    API -->|Webhooks / Checkout| Payments');
  if (email) lines.push('    API -->|Transactional Mail| Email');
  if (hosting) lines.push('    API -.->|Edge Deploy| Host');
  if (monitoring) lines.push('    API -.->|Telemetry & Errors| Observability');
  if (cicd) lines.push('    CI -.->|Automated Push| Host');

  return lines.join('\n');
}
